-- Catalogo oficial de requisitos das classes (gerado por scripts/gerar-seed-classes.mjs).
-- Classes incluidas: Amigo, Companheiro. Total de linhas: 385.

DELETE FROM public.classes_requisitos_catalogo
WHERE classe_nome IN ('Amigo', 'Companheiro');

INSERT INTO public.classes_requisitos_catalogo
  (classe_nome, secao, secao_ordem, ordem, codigo, codigo_raiz, subitem, texto, tipo, pagina, especialidade_nome, avancada, pontua)
VALUES
  ('Amigo', 'I. Geral', 1, 1, '1', '1', NULL, 'Ter no mínimo 10 anos de idade.', 'Requisito', 4, NULL, false, true),
  ('Amigo', 'I. Geral', 1, 2, '2', '2', NULL, 'Ser membro ativo do Clube de Desbravadores.', 'Requisito', 4, NULL, false, true),
  ('Amigo', 'I. Geral', 1, 3, '2', '2', 'a', 'Ao final do ano, faça um relatório das atividades que você fez no Clube.', 'Atividade', 4, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 4, '2', '2', 'b', 'Cole as fotos dos momentos mais marcantes.', 'Atividade', 4, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 5, '3', '3', NULL, 'Memorizar e explicar o Voto e a Lei do Desbravador.', 'Requisito', 5, NULL, false, true),
  ('Amigo', 'I. Geral', 1, 6, '3', '3', 'Voto', 'Pela graça de Deus, serei puro, bondoso e leal, guardarei a Lei do Desbravador, serei servo de Deus e amigo de todos.', 'Texto de referência', 5, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 7, '3', '3', 'a', 'Explique com suas palavras o significado do voto.', 'Questão', 5, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 8, '3', '3', 'b', 'Ilustre o voto através de fotos, desenhos ou colagens.', 'Atividade', 5, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 9, '3', '3', 'c', 'Encontre um verso bíblico que confirme o significado do voto.', 'Questão', 5, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 10, '3', '3', 'Lei', 'A Lei do Desbravador ordena-me: Observar a devoção matinal; cumprir fielmente a parte que me corresponde; cuidar de meu corpo; manter a consciência limpa; ser cortês e obediente; andar com reverência na casa de Deus; ter sempre um cântico no coração; ir aonde Deus mandar.', 'Texto de referência', 6, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 11, '3', '3', 'd', 'Explique com suas palavras o significado da lei.', 'Questão', 6, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 12, '3', '3', 'e', 'Ilustre a lei através de fotos, desenhos ou colagens.', 'Atividade', 6, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 13, '3', '3', 'f', 'Encontre um verso bíblico que confirme o significado da lei.', 'Questão', 6, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 14, '4', '4', NULL, 'Ler o livro do Curso de Leitura do ano.', 'Requisito', 7, NULL, false, true),
  ('Amigo', 'I. Geral', 1, 15, '4', '4', '1', 'Qual o título do livro?', 'Questão', 7, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 16, '4', '4', '2', 'Qual(is) o(s) autor(es) do livro?', 'Questão', 7, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 17, '4', '4', '3', 'Qual a editora?', 'Questão', 7, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 18, '4', '4', '4', 'Qual o nome do personagem principal?', 'Questão', 7, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 19, '4', '4', '5', 'Use o espaço abaixo para fazer um resumo do livro.', 'Atividade', 7, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 20, '5', '5', NULL, 'Ler o livro Vaso de Barro.', 'Requisito', 8, NULL, false, true),
  ('Amigo', 'I. Geral', 1, 21, '5', '5', 'a', 'Faça um breve relato dos pontos que mais chamaram sua atenção.', 'Atividade', 8, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 22, '5', '5', 'b', 'Escreva um parágrafo sobre a influência da leitura do livro para sua vida.', 'Atividade', 8, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 23, '6', '6', NULL, 'Participar ativamente da Classe Bíblica do seu Clube.', 'Requisito', 9, NULL, false, true),
  ('Amigo', 'I. Geral', 1, 24, '6', '6', 'a', 'Data de início da classe bíblica.', 'Campo/questão', 9, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 25, '6', '6', 'b', 'Data de término da classe bíblica.', 'Campo/questão', 9, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 26, '6', '6', 'c', 'Estudo bíblico utilizado.', 'Campo/questão', 9, NULL, false, false),
  ('Amigo', 'I. Geral', 1, 27, '6', '6', 'd', 'Escreva um parágrafo sobre o assunto estudado que você achou mais interessante. Explique por quê.', 'Campo/questão', 9, NULL, false, false),
  ('Amigo', 'II. Descoberta espiritual', 2, 28, '1', '1', NULL, 'Memorizar e demonstrar o seu conhecimento:', 'Requisito', 10, NULL, false, true),
  ('Amigo', 'II. Descoberta espiritual', 2, 29, '1', '1', 'a', 'Criação: o que Deus criou em cada dia da Criação.', 'Requisito', 10, NULL, false, false),
  ('Amigo', 'II. Descoberta espiritual', 2, 30, '1', '1', 'b', '10 Pragas: quais as pragas que caíram sobre o Egito.', 'Requisito', 10, NULL, false, false),
  ('Amigo', 'II. Descoberta espiritual', 2, 31, '1', '1', 'c', '12 Tribos: o nome de cada uma das 12 tribos de Israel.', 'Requisito', 10, NULL, false, false),
  ('Amigo', 'II. Descoberta espiritual', 2, 32, '1', '1', 'd', '39 livros do Antigo Testamento e demonstrar habilidade para encontrar qualquer um deles.', 'Requisito', 10, NULL, false, false),
  ('Amigo', 'II. Descoberta espiritual', 2, 33, '1', '1', 'a.1', 'Escreva o que Deus criou em cada dia da Criação e ilustre através de fotos, desenhos ou colagens.', 'Atividade', 10, NULL, false, false),
  ('Amigo', 'II. Descoberta espiritual', 2, 34, '1', '1', 'b.1', 'Circule, dentre as palavras, as 10 pragas que caíram sobre o Egito. Depois, localize-as no caça-palavras. Confira lendo Êxodo 7:14 a Êxodo 12:36.', 'Atividade', 11, NULL, false, false),
  ('Amigo', 'II. Descoberta espiritual', 2, 35, '1', '1', 'c.1', 'Escreva o nome de cada uma das 12 tribos de Israel.', 'Atividade', 12, NULL, false, false),
  ('Amigo', 'II. Descoberta espiritual', 2, 36, '1', '1', 'd.1', 'Localize no caça-palavras os 39 livros do Antigo Testamento.', 'Atividade', 12, NULL, false, false),
  ('Amigo', 'II. Descoberta espiritual', 2, 37, '1', '1', 'd.2', 'Escreva cada um dos 39 livros do Antigo Testamento dentro do grupo a que ele pertence: Pentateuco, Históricos, Profetas Maiores, Poéticos e Profetas Menores.', 'Atividade', 13, NULL, false, false),
  ('Amigo', 'II. Descoberta espiritual', 2, 38, '2', '2', NULL, 'Ler e explicar os versos abaixo: João 3:16; Efésios 6:1-3; II Timóteo 3:16; Salmo 1.', 'Requisito', 14, NULL, false, true),
  ('Amigo', 'II. Descoberta espiritual', 2, 39, '2', '2', 'a', 'Ilustre o significado dos versos através de fotos, desenhos ou colagens.', 'Atividade', 14, NULL, false, false),
  ('Amigo', 'II. Descoberta espiritual', 2, 40, '3', '3', NULL, 'Leitura bíblica: cumprir a lista de leituras indicada em Gênesis e Êxodo.', 'Leitura', 15, NULL, false, true),
  ('Amigo', 'III. Servindo a outros', 3, 41, '1', '1', NULL, 'Dedicar duas horas ajudando alguém em sua comunidade, através de duas das seguintes atividades:', 'Requisito', 15, NULL, false, true),
  ('Amigo', 'III. Servindo a outros', 3, 42, '1', '1', 'a', 'Visitar alguém que precisa de amizade e orar com essa pessoa.', 'Requisito', 15, NULL, false, false),
  ('Amigo', 'III. Servindo a outros', 3, 43, '1', '1', 'b', 'Oferecer alimento a alguém carente.', 'Requisito', 15, NULL, false, false),
  ('Amigo', 'III. Servindo a outros', 3, 44, '1', '1', 'c', 'Participar de um projeto ecológico ou educativo.', 'Requisito', 15, NULL, false, false),
  ('Amigo', 'III. Servindo a outros', 3, 45, '1', '1', 'd', 'Faça um relatório das atividades realizadas: pessoa ajudada, data e o que você fez.', 'Relatório', 15, NULL, false, false),
  ('Amigo', 'III. Servindo a outros', 3, 46, '1', '1', 'e', 'Projeto realizado: data e o que você fez.', 'Relatório', 16, NULL, false, false),
  ('Amigo', 'III. Servindo a outros', 3, 47, '1', '1', 'f', 'Procure o diretor da ADRA ou ASA da sua igreja, pergunte como funciona esse departamento e descreva o último projeto realizado pela ADRA ou ASA.', 'Atividade', 16, NULL, false, false),
  ('Amigo', 'III. Servindo a outros', 3, 48, '2', '2', NULL, 'Escrever uma redação explicando como ser um bom cidadão no lar e na escola.', 'Requisito', 17, NULL, false, true),
  ('Amigo', 'III. Servindo a outros', 3, 49, '2', '2', 'a', 'Escolha, das palavras apresentadas, apenas aquelas que representam o caráter de um bom cidadão e com elas preencha a cruzadinha.', 'Atividade', 18, NULL, false, false),
  ('Amigo', 'III. Servindo a outros', 3, 50, '2', '2', 'b', 'Explique, em suas próprias palavras, o significado da declaração que Jesus fez em Mateus 22:21.', 'Questão', 18, NULL, false, false),
  ('Amigo', 'IV. Desenvolvendo amizade', 4, 51, '1', '1', NULL, 'Mencionar dez qualidades de um bom amigo e apresentar quatro situações diárias onde você praticou a Regra Áurea de Mateus 7:12.', 'Requisito', 19, NULL, false, true),
  ('Amigo', 'IV. Desenvolvendo amizade', 4, 52, '1', '1', 'a', 'Preencha os quadradinhos e descubra a Regra Áurea. Para números iguais, letras iguais.', 'Atividade', 19, NULL, false, false),
  ('Amigo', 'IV. Desenvolvendo amizade', 4, 53, '1', '1', 'b', 'Escreva uma lista com 10 itens que farão de você um bom amigo.', 'Atividade', 19, NULL, false, false),
  ('Amigo', 'IV. Desenvolvendo amizade', 4, 54, '1', '1', 'c', 'Peça a seus amigos para escreverem dez características suas. Cada amigo só pode escrever uma qualidade.', 'Atividade', 19, NULL, false, false),
  ('Amigo', 'IV. Desenvolvendo amizade', 4, 55, '1', '1', 'd', 'Relate as quatro situações onde você praticou a Regra Áurea, com data e descrição do que aconteceu.', 'Relatório', 20, NULL, false, false),
  ('Amigo', 'IV. Desenvolvendo amizade', 4, 56, '2', '2', NULL, 'Saber cantar o Hino Nacional de seu país e conhecer sua história. Saber o nome do autor da letra e da música do hino.', 'Requisito', 21, NULL, false, true),
  ('Amigo', 'IV. Desenvolvendo amizade', 4, 57, '2', '2', 'a', 'Autor da letra do Hino Nacional.', 'Questão', 21, NULL, false, false),
  ('Amigo', 'IV. Desenvolvendo amizade', 4, 58, '2', '2', 'b', 'Autor da música do Hino Nacional.', 'Questão', 21, NULL, false, false),
  ('Amigo', 'IV. Desenvolvendo amizade', 4, 59, '2', '2', 'c', 'Faça um relato rápido da história do Hino Nacional.', 'Questão', 21, NULL, false, false),
  ('Amigo', 'IV. Desenvolvendo amizade', 4, 60, '2', '2', 'd', 'Anote as palavras do hino que você não conhecia e seu significado.', 'Atividade', 22, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 61, '1', '1', NULL, 'Completar uma das seguintes especialidades: Natação principiante I; Cultura física; Nós e amarras; Segurança básica na água.', 'Requisito', 23, NULL, false, true),
  ('Amigo', 'V. Saúde e aptidão física', 5, 62, '1', '1', 'Natação principiante I', 'Supervisionado por um especialista, completar os 11 itens da especialidade de Natação principiante I.', 'Especialidade', 23, 'Natação principiante I', false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 63, '1', '1', 'Natação 1', 'Ter a especialidade de Segurança básica na água.', 'Subitem de especialidade', 23, 'Segurança básica na água', false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 64, '1', '1', 'Natação 2', 'Com a água no nível do peito, buscar um objeto no fundo, sem ajuda e com os olhos abertos.', 'Subitem de especialidade', 23, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 65, '1', '1', 'Natação 3', 'Saltar da borda lateral, na parte mais profunda da piscina.', 'Subitem de especialidade', 23, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 66, '1', '1', 'Natação 4', 'Dando um impulso, deslizar de barriga para baixo à distância de dois corpos.', 'Subitem de especialidade', 23, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 67, '1', '1', 'Natação 5', 'Nado crawl – 20 metros.', 'Subitem de especialidade', 23, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 68, '1', '1', 'Natação 6', 'Nado de costas – 20 metros.', 'Subitem de especialidade', 23, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 69, '1', '1', 'Natação 7', 'Mudar de direção no nado livre de frente.', 'Subitem de especialidade', 23, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 70, '1', '1', 'Natação 8', 'Mudar de direção no nado de costas.', 'Subitem de especialidade', 23, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 71, '1', '1', 'Natação 9', 'Permanecer boiando por 1 minuto.', 'Subitem de especialidade', 23, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 72, '1', '1', 'Natação 10', 'Deslocar-se na água por 20 metros usando camiseta.', 'Subitem de especialidade', 23, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 73, '1', '1', 'Natação 11', 'Realizar perna de crawl e costas com prancha por 10 minutos.', 'Subitem de especialidade', 23, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 74, '1', '1', 'Cultura física', 'Completar os requisitos da especialidade de Cultura física.', 'Especialidade', 23, 'Cultura física', false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 75, '1', '1', 'Cultura física 1', 'Fazer um relatório citando, pelo menos, 10 benefícios de se manter um bom condicionamento físico.', 'Subitem de especialidade', 23, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 76, '1', '1', 'Cultura física 2', 'Fazer um relatório sobre como exercícios físicos, alimentação adequada e estabilidade emocional ajudam no equilíbrio do corpo, com exemplos negativos e positivos.', 'Subitem de especialidade', 23, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 77, '1', '1', 'Cultura física 3', 'Definir exercícios isométricos, isotônicos, isocinéticos, anaeróbios e aeróbios, citando exemplos.', 'Subitem de especialidade', 23, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 78, '1', '1', 'Cultura física 4', 'Explicar a importância de alongamento, aquecimento, exercícios aeróbios, relaxamento e exercícios localizados, citando exemplos.', 'Subitem de especialidade', 23, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 79, '1', '1', 'Cultura física 5', 'Demonstrar como verificar a frequência cardíaca em repouso e após atividade física.', 'Subitem de especialidade', 23, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 80, '1', '1', 'Cultura física 6', 'Saber calcular a frequência cardíaca máxima, sua importância, faixa de melhor aproveitamento em exercícios aeróbios e aparelho de controle.', 'Subitem de especialidade', 23, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 81, '1', '1', 'Cultura física 7', 'Fazer um programa de exercícios regulares, pelo menos 4 vezes por semana por 4 meses, registrando os dados pedidos.', 'Subitem de especialidade', 24, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 82, '1', '1', 'Nós e amarras', 'Completar os 12 requisitos da especialidade de Nós e amarras.', 'Especialidade', 24, 'Nós e amarras', false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 83, '1', '1', 'Nós e amarras 1', 'Definir termos relacionados a cordas e nós.', 'Subitem de especialidade', 24, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 84, '1', '1', 'Nós e amarras 2', 'Conhecer os cuidados para conservação de cordas.', 'Subitem de especialidade', 24, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 85, '1', '1', 'Nós e amarras 3', 'Descrever diferenças entre corda estática e dinâmica e listar usos.', 'Subitem de especialidade', 24, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 86, '1', '1', 'Nós e amarras 4', 'Identificar tipos de cordas e relatar pontos positivos e negativos: poliéster, sisal, nylon e polipropileno.', 'Subitem de especialidade', 24, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 87, '1', '1', 'Nós e amarras 5', 'Vantagens e desvantagens da corda sintética.', 'Subitem de especialidade', 24, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 88, '1', '1', 'Nós e amarras 6', 'Segundo a Bíblia, qual tipo de corda estática é mais resistente? Citar livro, capítulo e versículo.', 'Subitem de especialidade', 24, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 89, '1', '1', 'Nós e amarras 7', 'Fazer em uma corda os nós/costuras solicitados.', 'Subitem de especialidade', 24, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 90, '1', '1', 'Nós e amarras 8', 'Fazer duas cordas com pelo menos 2 metros cada, uma de três fios e outra com trançado triplo.', 'Subitem de especialidade', 24, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 91, '1', '1', 'Nós e amarras 9', 'Descrever pelo menos 3 plantas que fornecem material para corda.', 'Subitem de especialidade', 24, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 92, '1', '1', 'Nós e amarras 10', 'Fazer de memória pelo menos 20 nós, dizer nome, uso e limitações, e fazer relatório.', 'Subitem de especialidade', 24, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 93, '1', '1', 'Nós e amarras 11', 'Fazer corretamente cinco amarras: quadrada, diagonal, paralela/redonda, contínua simples e contínua dupla.', 'Subitem de especialidade', 25, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 94, '1', '1', 'Nós e amarras 12', 'Fazer um quadro com pelo menos 25 nós.', 'Subitem de especialidade', 25, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 95, '1', '1', 'Segurança básica na água', 'Completar os 11 requisitos da especialidade de Segurança básica na água.', 'Especialidade', 25, 'Segurança básica na água', false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 96, '1', '1', 'Segurança água 1', 'Demonstrar como entrar e sair da água de forma segura.', 'Subitem de especialidade', 25, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 97, '1', '1', 'Segurança água 2', 'Enquanto segura a respiração, submergir completamente o rosto na água por cinco segundos.', 'Subitem de especialidade', 25, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 98, '1', '1', 'Segurança água 3', 'Respirar pela boca e, alternadamente, com o rosto submerso, soltar o ar pela boca e pelo nariz, no mínimo sete vezes.', 'Subitem de especialidade', 25, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 99, '1', '1', 'Segurança água 4', 'Abrir os olhos embaixo d’água e recuperar objetos submersos.', 'Subitem de especialidade', 25, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 100, '1', '1', 'Segurança água 5', 'Boiar de frente por cinco segundos.', 'Subitem de especialidade', 25, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 101, '1', '1', 'Segurança água 6', 'Boiar de frente por um percurso de dois corpos.', 'Subitem de especialidade', 25, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 102, '1', '1', 'Segurança água 7', 'Voltar flutuando por 15 segundos.', 'Subitem de especialidade', 25, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 103, '1', '1', 'Segurança água 8', 'Segurando a borda da piscina, bater os pés alternadamente por vinte segundos.', 'Subitem de especialidade', 25, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 104, '1', '1', 'Segurança água 9', 'Usando braços e pernas, nadar por um percurso de cinco corpos.', 'Subitem de especialidade', 25, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 105, '1', '1', 'Segurança água 10', 'Aprender a colocar colete salva-vidas e flutuar por trinta segundos.', 'Subitem de especialidade', 25, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 106, '1', '1', 'Segurança água 11', 'Demonstrar segurança para: pedir ajuda em emergência; livrar-se de uma cãibra; aprender pelo menos dez regras de segurança próximo à água.', 'Subitem de especialidade', 25, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 107, '2', '2', NULL, 'Utilizando a experiência de Daniel:', 'Requisito', 25, NULL, false, true),
  ('Amigo', 'V. Saúde e aptidão física', 5, 108, '2', '2', 'a', 'Explicar os princípios de temperança que ele defendeu ou participar em apresentação/encenação sobre Daniel 1.', 'Requisito', 25, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 109, '2', '2', 'b', 'Memorizar e explicar Daniel 1:8.', 'Requisito', 25, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 110, '2', '2', 'c', 'Escrever seu compromisso pessoal de seguir um estilo de vida saudável.', 'Requisito', 25, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 111, '2', '2', 'a.1', 'Você participou de alguma apresentação ou encenação sobre Daniel? Registrar sim/não, data, local e descrever a encenação.', 'Relatório', 26, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 112, '2', '2', 'b.1', 'Complete o versículo Daniel 1:8.', 'Atividade', 26, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 113, '2', '2', 'c.1', 'Meu compromisso de estilo de vida baseado em Daniel 1:8.', 'Atividade', 27, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 114, '3', '3', NULL, 'Aprender os princípios de uma dieta saudável e ajudar a preparar um quadro com os grupos básicos de alimentos.', 'Requisito', 27, NULL, false, true),
  ('Amigo', 'V. Saúde e aptidão física', 5, 115, '3', '3', 'a', 'Organize figuras ou desenhos conforme os grupos: carboidratos, vitaminas e minerais, proteínas e gorduras; coloque ao menos três alimentos em cada grupo.', 'Atividade', 27, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 116, '3', '3', 'b', 'Dos alimentos apresentados, circule os que Deus aconselhou que usássemos. Dica: Gênesis 1:29.', 'Atividade', 29, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 117, '3', '3', 'c', 'Consultando a pirâmide alimentar, organize um cardápio saudável para três dias, de preferência sem carne.', 'Atividade', 29, NULL, false, false),
  ('Amigo', 'V. Saúde e aptidão física', 5, 118, '3', '3', 'd', 'Preencha café da manhã, almoço e jantar para o 1º, 2º e 3º dia.', 'Atividade', 31, NULL, false, false),
  ('Amigo', 'VI. Organização e liderança', 6, 119, '1', '1', NULL, 'Através da observação, acompanhar todo o processo de planejamento até a execução de uma caminhada de 5 km.', 'Requisito', 32, NULL, false, true),
  ('Amigo', 'VI. Organização e liderança', 6, 120, '1', '1', 'a', 'Anote os itens que você precisa levar em uma caminhada.', 'Atividade', 32, NULL, false, false),
  ('Amigo', 'VI. Organização e liderança', 6, 121, '1', '1', 'b', 'Faça um breve relatório da caminhada realizada: data, local, duração e relato.', 'Relatório', 32, NULL, false, false),
  ('Amigo', 'VI. Organização e liderança', 6, 122, '1', '1', 'c', 'Marque as coisas que viu durante a caminhada e ligue-as às passagens bíblicas correspondentes.', 'Atividade', 33, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 123, '1', '1', NULL, 'Completar uma das seguintes especialidades: Felinos; Cães; Mamíferos; Sementes; Aves de estimação.', 'Requisito', 33, NULL, false, true),
  ('Amigo', 'VII. Estudo da natureza', 7, 124, '1', '1', 'Felinos', 'Completar os 12 requisitos da especialidade de Felinos.', 'Especialidade', 33, 'Felinos', false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 125, '1', '1', 'Felinos 1', 'Nome científico da família do gato e características comuns.', 'Subitem de especialidade', 33, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 126, '1', '1', 'Felinos 2', 'Semelhança da estrutura da pata em todos os felinos.', 'Subitem de especialidade', 33, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 127, '1', '1', 'Felinos 3', 'Semelhança dos olhos de todos os felinos.', 'Subitem de especialidade', 33, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 128, '1', '1', 'Felinos 4', 'Principal alimento dos gatos e adaptação dos dentes.', 'Subitem de especialidade', 33, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 129, '1', '1', 'Felinos 5', 'Função dos bigodes.', 'Subitem de especialidade', 33, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 130, '1', '1', 'Felinos 6', 'Como os ouvidos são protegidos.', 'Subitem de especialidade', 33, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 131, '1', '1', 'Felinos 7', 'Identificar 4 raças de gatos domésticos e descrever o temperamento.', 'Subitem de especialidade', 33, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 132, '1', '1', 'Felinos 8', 'Benefícios dos gatos domésticos para o homem.', 'Subitem de especialidade', 33, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 133, '1', '1', 'Felinos 9', 'Identificar 7 espécies de felinos selvagens e dizer onde vivem.', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 134, '1', '1', 'Felinos 10', 'Responder perguntas sobre maior felino do mundo, maior da América do Sul, mais veloz e “rei dos animais”.', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 135, '1', '1', 'Felinos 11', 'Contar a história de Androcles e o Leão.', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 136, '1', '1', 'Felinos 12', 'Contar 4 histórias bíblicas com felinos.', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 137, '1', '1', 'Cães', 'Completar os 13 requisitos da especialidade de Cães.', 'Especialidade', 34, 'Cães', false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 138, '1', '1', 'Cães 1', 'Dar o nome científico do cão doméstico.', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 139, '1', '1', 'Cães 2', 'Citar 5 características peculiares da família Canidae.', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 140, '1', '1', 'Cães 3', 'Identificar 5 membros selvagens da família dos cães.', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 141, '1', '1', 'Cães 4', 'Identificar 15 raças de cães.', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 142, '1', '1', 'Cães 5', 'Mencionar 5 contribuições da família dos cães ao homem.', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 143, '1', '1', 'Cães 6', 'Explicar a importância de grupos de cães e citar raças equivalentes: guia, farejadores, pastores, companheiros para crianças, guardas, auxiliares da polícia/bombeiros.', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 144, '1', '1', 'Cães 7', 'Dar o nome da menor e da maior raça.', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 145, '1', '1', 'Cães 8', 'Identificar 5 cães “toy”.', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 146, '1', '1', 'Cães 9', 'Qual cão tem a língua inteiramente azul ou preta?', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 147, '1', '1', 'Cães 10', 'Qual o cão mais rápido?', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 148, '1', '1', 'Cães 11', 'Escrever ou contar uma história sobre um cão.', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 149, '1', '1', 'Cães 12', 'Cuidados para que cães tenham vida saudável.', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 150, '1', '1', 'Cães 13', 'Ajudar a cuidar de um cão por pelo menos 1 mês.', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 151, '1', '1', 'Mamíferos', 'Completar os requisitos da especialidade de Mamíferos.', 'Especialidade', 34, 'Mamíferos', false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 152, '1', '1', 'Mamíferos 1', 'Em que dia da criação foram criados os mamíferos?', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 153, '1', '1', 'Mamíferos 2', 'Relacionar 4 características de um mamífero.', 'Subitem de especialidade', 34, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 154, '1', '1', 'Mamíferos 3', 'Apresentar características e espécies de 12 ordens de mamíferos.', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 155, '1', '1', 'Mamíferos 4', 'Relacionar quatro mamíferos úteis e explicar sua utilidade.', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 156, '1', '1', 'Mamíferos 5', 'Relacionar quatro coisas prejudiciais feitas por mamíferos.', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 157, '1', '1', 'Mamíferos 6', 'Relacionar quatro mamíferos completamente aquáticos e indicar sua distribuição.', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 158, '1', '1', 'Mamíferos 7', 'Qual é o maior mamífero do mundo? Onde vive, como se alimenta e o que come?', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 159, '1', '1', 'Mamíferos 8', 'Relacionar oito espécies de mamíferos silvestres observados pessoalmente.', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 160, '1', '1', 'Mamíferos 9', 'Escrever ou contar história sobre mamíferos silvestres observados.', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 161, '1', '1', 'Sementes', 'Completar os 10 requisitos da especialidade de Sementes.', 'Especialidade', 35, 'Sementes', false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 162, '1', '1', 'Sementes 1', 'Qual o principal objetivo de uma semente?', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 163, '1', '1', 'Sementes 2', 'Que alimentos foram dados primeiro ao homem no Éden?', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 164, '1', '1', 'Sementes 3', 'Identificar tegumento, cotilédone e embrião e saber seus propósitos.', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 165, '1', '1', 'Sementes 4', 'Conhecer 4 métodos de dispersão e 3 exemplos por método.', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 166, '1', '1', 'Sementes 5', 'Conhecer 10 sementes usadas como alimento.', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 167, '1', '1', 'Sementes 6', 'Conhecer 5 sementes fonte de óleo.', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 168, '1', '1', 'Sementes 7', 'Conhecer 5 sementes usadas como condimentos.', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 169, '1', '1', 'Sementes 8', 'Qual fator não pode faltar para uma planta germinar?', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 170, '1', '1', 'Sementes 9', 'Fazer coleção de 30 tipos de sementes, 20 encontradas por você, com identificação.', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 171, '1', '1', 'Sementes 10', 'Plantar feijão, milho e soja e fazer relatório diário da germinação.', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 172, '1', '1', 'Aves de estimação', 'Completar os requisitos da especialidade de Aves de estimação.', 'Especialidade', 35, 'Aves de estimação', false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 173, '1', '1', 'Aves 1', 'Conhecer as leis sobre captura, criação e exportação de pássaros em gaiolas e certificar-se da legalidade.', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 174, '1', '1', 'Aves 2', 'Cuidar de um pássaro ou casal por pelo menos 6 meses.', 'Subitem de especialidade', 35, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 175, '1', '1', 'Aves 3', 'Completar registro de cuidados por 1 mês ou cuidar do pássaro de outra pessoa por 1 semana.', 'Subitem de especialidade', 36, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 176, '1', '1', 'Aves 4', 'Canários: variedades, história, sementes usadas na alimentação e cuidados gerais.', 'Subitem de especialidade', 36, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 177, '1', '1', 'Aves 5', 'Periquitos: origem e descrição de hábitos.', 'Subitem de especialidade', 36, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 178, '1', '1', 'Aves 6', 'Pesquisar a ave de estimação mais comum na região, suas características e cuidados.', 'Subitem de especialidade', 36, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 179, '1', '1', 'Aves 7', 'Encontrar na Bíblia pelo menos 3 versos sobre aves de estimação e pesquisar hábitos, características e origens.', 'Subitem de especialidade', 36, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 180, '2', '2', NULL, 'Aprender e demonstrar uma maneira para purificar a água e escrever um parágrafo destacando o significado de Jesus como a água da vida.', 'Requisito', 36, NULL, false, true),
  ('Amigo', 'VII. Estudo da natureza', 7, 181, '2', '2', 'a', 'Descreva uma maneira de se purificar a água.', 'Atividade', 36, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 182, '2', '2', 'b', 'Localize na Bíblia um versículo que mostre Jesus como fonte de água e explique-o.', 'Atividade', 36, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 183, '2', '2', 'c', 'Escreva sobre o significado de Jesus como a água viva.', 'Atividade', 37, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 184, '3', '3', NULL, 'Aprender e montar uma barraca em local apropriado.', 'Requisito', 37, NULL, false, true),
  ('Amigo', 'VII. Estudo da natureza', 7, 185, '3', '3', 'a', 'Mencione três tipos diferentes de barracas.', 'Questão', 37, NULL, false, false),
  ('Amigo', 'VII. Estudo da natureza', 7, 186, '3', '3', 'b', 'Como deve ser escolhido o local para montar uma barraca?', 'Questão', 37, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 187, '1', '1', NULL, 'Demonstrar como cuidar corretamente de uma corda. Fazer e explicar o uso prático dos nós: simples, cego, direito, cirurgião, lais de guia, lais de guia duplo, escota, catau, pescador, fateixa, volta do fiel, nó de gancho, volta da ribeira e ordinário.', 'Requisito', 38, NULL, false, true),
  ('Amigo', 'VIII. Arte de acampar', 8, 188, '1', '1', 'a', 'Escreva sobre como cuidar corretamente de uma corda.', 'Atividade', 38, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 189, '1', '1', 'b', 'Faça e explique o uso prático de cada nó listado.', 'Atividade', 38, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 190, '2', '2', NULL, 'Completar a especialidade de Acampamento I.', 'Requisito', 41, 'Acampamento I', false, true),
  ('Amigo', 'VIII. Arte de acampar', 8, 191, '2', '2', 'Acampamento I 1', 'Entender e praticar a boa educação no campo e preservação da natureza.', 'Subitem de especialidade', 41, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 192, '2', '2', 'Acampamento I 2', 'Saber oito coisas que devem ser feitas quando se está perdido.', 'Subitem de especialidade', 41, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 193, '2', '2', 'Acampamento I 3', 'Familiarizar-se com equipamentos para dormir adequados a climas e épocas.', 'Subitem de especialidade', 41, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 194, '2', '2', 'Acampamento I 4', 'Relacionar objetos pessoais necessários a um acampamento de fim de semana.', 'Subitem de especialidade', 41, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 195, '2', '2', 'Acampamento I 5', 'Planejar e participar de acampamento de fim de semana, com no mínimo 2 pernoites.', 'Subitem de especialidade', 41, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 196, '2', '2', 'Acampamento I 6', 'Saber montar barraca e observar prevenção contra incêndios.', 'Subitem de especialidade', 41, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 197, '2', '2', 'Acampamento I 7', 'Conhecer princípios de higiene em acampamento.', 'Subitem de especialidade', 41, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 198, '2', '2', 'Acampamento I 8', 'Usar corretamente canivete e machadinha e conhecer 10 regras de segurança.', 'Subitem de especialidade', 41, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 199, '2', '2', 'Acampamento I 9', 'Fogueiras: escolher local, segurança, fósforos, fazer com um fósforo e proteger lenha.', 'Subitem de especialidade', 41, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 200, '2', '2', 'Acampamento I 10', 'Fazer e comer pão no espeto.', 'Subitem de especialidade', 41, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 201, '2', '2', 'Acampamento I 11', 'Descrever como levar e manter utensílios de cozinha limpos.', 'Subitem de especialidade', 41, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 202, '2', '2', 'Acampamento I 12', 'Descrever roupa apropriada para dormir e manter-se aquecido.', 'Subitem de especialidade', 41, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 203, '2', '2', 'Acampamento I 13', 'Retirar lição espiritual prática da natureza durante o acampamento.', 'Subitem de especialidade', 41, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 204, '2', '2', 'Acampamento I 14', 'Explicar e praticar o lema: não levar nada além de fotos, não deixar nada além de pegadas, não matar nada além do tempo.', 'Subitem de especialidade', 41, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 205, '3', '3', NULL, 'Apresentar dez regras para uma caminhada e explicar o que fazer quando estiver perdido.', 'Requisito', 42, NULL, false, true),
  ('Amigo', 'VIII. Arte de acampar', 8, 206, '3', '3', 'a', 'Registrar as regras 1 a 10 para uma caminhada.', 'Atividade', 42, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 207, '3', '3', 'b', 'Registrar o que fazer quando estiver perdido.', 'Atividade', 44, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 208, '4', '4', NULL, 'Aprender os sinais para seguir uma pista. Preparar e seguir uma pista de no mínimo dez sinais, que também possa ser seguida por outros.', 'Requisito', 45, NULL, false, true),
  ('Amigo', 'VIII. Arte de acampar', 8, 209, '4', '4', 'a', 'Escreva o que significa cada um dos sinais apresentados.', 'Atividade', 45, NULL, false, false),
  ('Amigo', 'VIII. Arte de acampar', 8, 210, '4', '4', 'b', 'Minha trilha: relato, local e data.', 'Relatório', 45, NULL, false, false),
  ('Amigo', 'IX. Estilo de vida', 9, 211, '1', '1', NULL, 'Completar uma especialidade na área de Artes e habilidades manuais.', 'Requisito', 46, NULL, false, true),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 212, '1', '1', NULL, 'Memorizar, cantar ou tocar o Hino dos Desbravadores e conhecer a história do hino.', 'Requisito', 46, NULL, true, true),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 213, '1', '1', 'a', 'Registrar o significado de cada trecho do Hino dos Desbravadores.', 'Atividade', 46, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 214, '2', '2', NULL, 'Em consulta com seu líder, escolher um personagem do Antigo Testamento e conversar com o grupo sobre o amor e cuidado de Deus e o livramento demonstrado na vida do personagem.', 'Requisito', 47, NULL, true, true),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 215, '2', '2', 'a', 'Situação vivida pelo personagem.', 'Questão', 47, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 216, '2', '2', 'b', 'Como Deus demonstrou Seu cuidado nessa situação?', 'Questão', 47, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 217, '2', '2', 'c', 'Situação mais perigosa vivida pelo personagem.', 'Questão', 48, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 218, '2', '2', 'd', 'Como Deus livrou esse personagem do perigo?', 'Questão', 48, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 219, '3', '3', NULL, 'Levar pelo menos dois amigos não adventistas à Escola Sabatina ou ao Clube de Desbravadores.', 'Requisito', 48, NULL, true, true),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 220, '3', '3', 'a', 'Registrar nome do amigo, qual atividade conheceu e data da visita.', 'Relatório', 48, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 221, '4', '4', NULL, 'Conhecer os princípios de higiene, boas maneiras à mesa e comportamento diante de pessoas de diferentes idades. Demonstrar e explicar como podem ser úteis nas reuniões e acampamentos do Clube.', 'Requisito', 48, NULL, true, true),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 222, '4', '4', 'a', 'Liste 5 hábitos de higiene que devemos praticar diariamente.', 'Atividade', 48, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 223, '4', '4', 'b', 'Preencha as frases usando apenas as palavras certas do banco de palavras.', 'Atividade', 49, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 224, '4', '4', 'c', 'Explique por que as boas maneiras são importantes.', 'Questão', 49, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 225, '5', '5', NULL, 'Completar a especialidade de Arte de acampar.', 'Requisito', 50, 'Arte de acampar', true, true),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 226, '5', '5', 'Arte de acampar 1', 'Explicar como e por que tempo, estação e fontes de água devem ser considerados ao escolher local.', 'Subitem de especialidade', 50, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 227, '5', '5', 'Arte de acampar 2', 'Preparar listas de roupas para clima quente e frio.', 'Subitem de especialidade', 50, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 228, '5', '5', 'Arte de acampar 3', 'Conhecer e praticar regras de segurança de acampamento.', 'Subitem de especialidade', 50, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 229, '5', '5', 'Arte de acampar 4', 'Demonstrar habilidade e segurança no uso do canivete.', 'Subitem de especialidade', 50, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 230, '5', '5', 'Arte de acampar 5', 'Preparar acampamento para a unidade, listando objetos pessoais e do grupo.', 'Subitem de especialidade', 50, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 231, '5', '5', 'Arte de acampar 6', 'Preparar cardápio balanceado para desjejum, almoço e jantar.', 'Subitem de especialidade', 50, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 232, '5', '5', 'Arte de acampar 7', 'No acampamento: preparar chão da barraca, montar barraca, preparar área de fogueira, proteger de animais/insetos/clima e preservar a natureza.', 'Subitem de especialidade', 50, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 233, '5', '5', 'Arte de acampar 8', 'Saber oito coisas a fazer quando perdido.', 'Subitem de especialidade', 50, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 234, '5', '5', 'Arte de acampar 9', 'Acampar por três dias e duas noites e participar de pelo menos duas refeições.', 'Subitem de especialidade', 50, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 235, '5', '5', 'Arte de acampar 10', 'Explicar o significado e a razão do Código de Acampamento dos Desbravadores.', 'Subitem de especialidade', 50, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 236, '6', '6', NULL, 'Conhecer e identificar dez flores silvestres e dez insetos de sua região.', 'Requisito', 51, NULL, true, true),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 237, '6', '6', 'a', 'Conhecer técnicas de secagem de plantas: ao ar livre e prensagem.', 'Conteúdo', 51, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 238, '6', '6', 'b', 'Tire fotos, recorte revistas, desenhe ou cole 10 flores silvestres de sua região.', 'Atividade', 52, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 239, '6', '6', 'c', 'Tire fotos, recorte revistas ou desenhe 10 insetos de sua região.', 'Atividade', 54, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 240, '7', '7', NULL, 'Começar uma fogueira usando materiais naturais e mantê-la acesa.', 'Requisito', 56, NULL, true, true),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 241, '7', '7', 'a', 'Faça uma lista de seis materiais encontrados na natureza que poderiam ser usados para iniciar uma fogueira.', 'Atividade', 56, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 242, '8', '8', NULL, 'Usar corretamente uma faca, facão ou machadinha e conhecer dez regras para usá-los com segurança.', 'Requisito', 56, NULL, true, true),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 243, '8', '8', 'a', 'Marque C nas ilustrações corretas e E nas erradas.', 'Atividade', 56, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 244, '8', '8', 'b', 'Liste dez regras de segurança no uso da faca, facão ou machadinha.', 'Atividade', 57, NULL, true, false),
  ('Amigo', 'Classe avançada — Amigo da Natureza', 10, 245, '9', '9', NULL, 'Escolher e completar uma especialidade em uma das áreas: atividades missionárias ou atividades agrícolas.', 'Requisito', 57, NULL, true, true),
  ('Amigo', 'Administrativo', 11, 246, 'Ficha de autorização', 'Ficha de autorização', NULL, 'Ficha de autorização para participação em especialidades, camporis, acampamentos, desfiles, cursos, olimpíadas, feiras, certificado, congresso, convenção, acantonamentos, excursões e investiduras.', 'Formulário', 58, NULL, false, false),
  ('Companheiro', 'I. Gerais', 1, 1, '1', '1', NULL, 'Ter no mínimo 11 anos de idade.', 'Requisito', 4, NULL, false, true),
  ('Companheiro', 'I. Gerais', 1, 2, '2', '2', NULL, 'Ser membro ativo do Clube de Desbravadores.', 'Requisito', 4, NULL, false, true),
  ('Companheiro', 'I. Gerais', 1, 3, '2.1', '2', NULL, 'Ao final do ano, fazer um relatório das atividades realizadas no Clube.', 'Requisito', 4, NULL, false, false),
  ('Companheiro', 'I. Gerais', 1, 4, '2.2', '2', NULL, 'Colar fotos dos momentos mais marcantes.', 'Requisito', 4, NULL, false, false),
  ('Companheiro', 'I. Gerais', 1, 5, '3', '3', NULL, 'Ilustrar de forma criativa o significado do Voto do Desbravador.', 'Requisito', 5, NULL, false, true),
  ('Companheiro', 'I. Gerais', 1, 6, '4', '4', NULL, 'Ler o livro do Curso de Leitura do ano e escrever um parágrafo sobre o que mais chamou atenção ou considerou importante.', 'Requisito', 6, NULL, false, true),
  ('Companheiro', 'I. Gerais', 1, 7, '4', '4', 'a', 'Título do livro', 'Campo', 6, NULL, false, false),
  ('Companheiro', 'I. Gerais', 1, 8, '4', '4', 'b', 'Autor(es)', 'Campo', 6, NULL, false, false),
  ('Companheiro', 'I. Gerais', 1, 9, '4', '4', 'c', 'Editora', 'Campo', 6, NULL, false, false),
  ('Companheiro', 'I. Gerais', 1, 10, '4', '4', 'd', 'Personagem principal', 'Campo', 6, NULL, false, false),
  ('Companheiro', 'I. Gerais', 1, 11, '5', '5', NULL, 'Ler o livro Caminho a Cristo.', 'Requisito', 6, NULL, false, true),
  ('Companheiro', 'I. Gerais', 1, 12, '5.1', '5', NULL, 'Registrar a data de início e a data de término da leitura.', 'Requisito', 6, NULL, false, false),
  ('Companheiro', 'I. Gerais', 1, 13, '5.2', '5', NULL, 'Fazer um breve relato dos pontos que mais chamaram a atenção.', 'Requisito', 6, NULL, false, false),
  ('Companheiro', 'I. Gerais', 1, 14, '6', '6', NULL, 'Participar ativamente da Classe Bíblica do Clube.', 'Requisito', 7, NULL, false, true),
  ('Companheiro', 'I. Gerais', 1, 15, '6.1', '6', NULL, 'Registrar datas de início e término e o estudo bíblico utilizado.', 'Requisito', 7, NULL, false, false),
  ('Companheiro', 'I. Gerais', 1, 16, '6.2', '6', NULL, 'Escrever um parágrafo sobre o assunto estudado que achou mais interessante e explicar por quê.', 'Requisito', 7, NULL, false, false),
  ('Companheiro', 'II. Descoberta espiritual', 2, 17, '1', '1', 'a', 'Memorizar e demonstrar conhecimento dos Dez Mandamentos: a Lei de Deus dada a Moisés.', 'Requisito', 7, NULL, false, false),
  ('Companheiro', 'II. Descoberta espiritual', 2, 18, '1', '1', 'b', 'Memorizar os 27 livros do Novo Testamento e demonstrar habilidade para encontrar qualquer um deles.', 'Requisito', 7, NULL, false, false),
  ('Companheiro', 'II. Descoberta espiritual', 2, 19, '1.1', '1', NULL, 'Desembaralhar as letras e escrever os Dez Mandamentos; conferir em Êxodo 20:3-17.', 'Requisito', 8, NULL, false, false),
  ('Companheiro', 'II. Descoberta espiritual', 2, 20, '1.2', '1', NULL, 'Encontrar os 27 livros do Novo Testamento no caça-palavras e escrevê-los nos grupos: Evangelhos, Histórico, Cartas e Epístolas e Profético.', 'Requisito', 9, NULL, false, false),
  ('Companheiro', 'II. Descoberta espiritual', 2, 21, '2', '2', NULL, 'Ler e explicar Isaías 41:9-10, Hebreus 13:5, Provérbios 22:6, 1 João 1:9 e Salmo 8.', 'Requisito', 10, NULL, false, true),
  ('Companheiro', 'II. Descoberta espiritual', 2, 22, '2.1', '2', NULL, 'Ilustrar o significado dos versos por meio de fotos, desenhos ou colagens.', 'Requisito', 10, NULL, false, false),
  ('Companheiro', 'II. Descoberta espiritual', 2, 23, '3', '3', NULL, 'Completar a leitura bíblica indicada na página.', 'Requisito', 11, NULL, false, true),
  ('Companheiro', 'II. Descoberta espiritual', 2, 24, '4', '4', NULL, 'Em consulta com o conselheiro, escolher um tema: parábola de Jesus; milagre de Jesus; Sermão da Montanha; ou sermão sobre a Segunda Vinda de Cristo.', 'Requisito', 11, NULL, false, true),
  ('Companheiro', 'II. Descoberta espiritual', 2, 25, '4.1', '4', NULL, 'Escolher uma forma de demonstrar conhecimento: troca de ideias, atividade em grupo ou redação.', 'Requisito', 11, NULL, false, false),
  ('Companheiro', 'II. Descoberta espiritual', 2, 26, '4.2', '4', NULL, 'Escrever o que aprendeu sobre o tema escolhido.', 'Requisito', 12, NULL, false, false),
  ('Companheiro', 'III. Servindo a outros', 3, 27, '1', '1', NULL, 'Planejar e dedicar pelo menos duas horas servindo a comunidade e demonstrando companheirismo a alguém, de maneira prática.', 'Requisito', 12, NULL, false, true),
  ('Companheiro', 'III. Servindo a outros', 3, 28, '1.1', '1', NULL, 'Escolher a atividade: visita a hospital, orfanato, creche, asilo, distribuição de alimentos ou ajuda a pessoa carente.', 'Requisito', 12, NULL, false, false),
  ('Companheiro', 'III. Servindo a outros', 3, 29, '1.2', '1', NULL, 'Planejar a atividade e descrever exatamente como o requisito será cumprido.', 'Requisito', 13, NULL, false, false),
  ('Companheiro', 'III. Servindo a outros', 3, 30, '2', '2', NULL, 'Participar de um projeto que beneficie a comunidade ou a igreja.', 'Requisito', 13, NULL, false, true),
  ('Companheiro', 'III. Servindo a outros', 3, 31, '2.1', '2', NULL, 'Escolher e escrever sobre o projeto realizado.', 'Requisito', 13, NULL, false, false),
  ('Companheiro', 'IV. Desenvolvendo amizade', 4, 32, '1', '1', NULL, 'Conversar com o conselheiro ou unidade sobre como respeitar pessoas de diferentes culturas, etnia e sexo.', 'Requisito', 14, NULL, false, true),
  ('Companheiro', 'IV. Desenvolvendo amizade', 4, 33, '1.1', '1', NULL, 'Ler Deuteronômio 10:17-19 e preencher a cruzadinha com as palavras em destaque.', 'Requisito', 14, NULL, false, false),
  ('Companheiro', 'IV. Desenvolvendo amizade', 4, 34, '1.2', '1', NULL, 'Pesquisar na Bíblia três trechos que demonstrem o cuidado de Deus com pessoas de culturas e etnias diferentes.', 'Requisito', 15, NULL, false, false),
  ('Companheiro', 'IV. Desenvolvendo amizade', 4, 35, '1.3', '1', NULL, 'Explicar, com suas próprias palavras, Tiago 2:8-9.', 'Requisito', 15, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 36, '1', '1', NULL, 'Memorizar e explicar 1 Coríntios 9:24-27.', 'Requisito', 16, NULL, false, true),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 37, '1', '1', 'Verso 24', 'Explicar o significado do verso.', 'Reflexão', 16, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 38, '1', '1', 'Verso 25', 'Explicar o significado do verso.', 'Reflexão', 16, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 39, '1', '1', 'Verso 26', 'Explicar o significado do verso.', 'Reflexão', 16, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 40, '1', '1', 'Verso 27', 'Explicar o significado do verso.', 'Reflexão', 16, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 41, '2', '2', NULL, 'Conversar com o líder sobre aptidão física e exercícios regulares relacionados a uma vida saudável.', 'Requisito', 17, NULL, false, true),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 42, '2.1', '2', NULL, 'Completar a frase cifrada sobre os benefícios do exercício físico.', 'Requisito', 17, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 43, '2.2', '2', NULL, 'Usando um texto bíblico, demonstrar como o exercício físico é comparado com a vida espiritual.', 'Requisito', 17, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 44, '2.3', '2', NULL, 'Explicar por que é importante fazer alongamento antes de qualquer exercício.', 'Requisito', 18, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 45, '2.4', '2', NULL, 'Escrever compromisso pessoal para a prática de exercícios físicos diários e registrar os exercícios de cada dia da semana.', 'Requisito', 18, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 46, '3', '3', NULL, 'Aprender sobre os prejuízos que o cigarro causa à saúde e escrever compromisso de não fazer uso do fumo.', 'Requisito', 18, NULL, false, true),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 47, '3.1', '3', NULL, 'Escrever cinco doenças que podem surgir por causa do cigarro.', 'Requisito', 18, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 48, '3.2', '3', NULL, 'Escrever dez substâncias tóxicas que compõem o cigarro.', 'Requisito', 18, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 49, '4', '4', NULL, 'Completar uma das especialidades: Natação principiante II ou Acampamento II.', 'Requisito', 20, NULL, false, true),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 50, '4 - Acampamento II', '4 - Acampamento II', '1', 'Ter, no mínimo, 11 anos.', 'Especialidade', 20, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 51, '4 - Acampamento II', '4 - Acampamento II', '2', 'Desenvolver uma filosofia pessoal de comportamento em acampamentos, abordando cortesia e preservação da natureza.', 'Especialidade', 20, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 52, '4 - Acampamento II', '4 - Acampamento II', '3', 'Conhecer fatores para escolher bom local: vento, água, vida silvestre, madeira, condições do tempo e boa vontade.', 'Especialidade', 20, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 53, '4 - Acampamento II', '4 - Acampamento II', '4', 'Demonstrar habilidade para proteger a natureza e a fonte de água, com higiene pessoal e limpeza ao cozinhar.', 'Especialidade', 20, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 54, '4 - Acampamento II', '4 - Acampamento II', '5', 'Participar de acampamento de fim de semana com, no mínimo, duas pernoites.', 'Especialidade', 20, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 55, '4 - Acampamento II', '4 - Acampamento II', '6', 'Tomar parte em um culto durante o acampamento.', 'Especialidade', 20, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 56, '4 - Acampamento II', '4 - Acampamento II', '7', 'Saber acender com segurança um fogareiro e um lampião.', 'Especialidade', 21, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 57, '4 - Acampamento II', '4 - Acampamento II', '8', 'Saber as normas de segurança no uso do machado ou facão e cortar lenha apropriadamente.', 'Especialidade', 21, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 58, '4 - Acampamento II', '4 - Acampamento II', '9', 'Construir e conhecer o uso do fogo do conselho ou fogo indígena para cozinhar; rever normas de segurança.', 'Especialidade', 21, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 59, '4 - Acampamento II', '4 - Acampamento II', '10', 'Explicar duas formas de manter alimentos frescos sem equipamentos elétricos.', 'Especialidade', 21, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 60, '4 - Acampamento II', '4 - Acampamento II', '11', 'Executar duas maneiras diferentes de levantar objetos pesados em acampamento.', 'Especialidade', 21, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 61, '4 - Acampamento II', '4 - Acampamento II', '12', 'Preparar refeições cozinhando, fritando e assando alimentos.', 'Especialidade', 21, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 62, '4 - Acampamento II', '4 - Acampamento II', '13', 'Escolher local para barracas, montar corretamente, explicar precauções para barraca molhada e limpar, secar e guardar.', 'Especialidade', 21, NULL, false, false),
  ('Companheiro', 'V. Saúde e aptidão física', 5, 63, '4 - Acampamento II', '4 - Acampamento II', '14', 'Demonstrar cuidados com saco de dormir ou colchonete: enrolar, manter seco e limpar.', 'Especialidade', 21, NULL, false, false),
  ('Companheiro', 'VI. Organização e liderança', 6, 64, '1', '1', NULL, 'Dirigir ou colaborar em uma meditação criativa para a Unidade ou Clube.', 'Requisito', 21, NULL, false, true),
  ('Companheiro', 'VI. Organização e liderança', 6, 65, '1.1', '1', NULL, 'Participar de encenação de uma história bíblica em tempos modernos e escrever o roteiro da peça.', 'Requisito', 21, NULL, false, false),
  ('Companheiro', 'VI. Organização e liderança', 6, 66, '2', '2', NULL, 'Ajudar no planejamento de uma excursão ou acampamento com a Unidade ou Clube, envolvendo pelo menos um pernoite.', 'Requisito', 22, NULL, false, true),
  ('Companheiro', 'VI. Organização e liderança', 6, 67, '2', '2', '1', 'Escolha do local', 'Planejamento', 22, NULL, false, false),
  ('Companheiro', 'VI. Organização e liderança', 6, 68, '2', '2', '2', 'Orçamento e logística', 'Planejamento', 22, NULL, false, false),
  ('Companheiro', 'VI. Organização e liderança', 6, 69, '2', '2', '3', 'Cardápio e nutrição', 'Planejamento', 22, NULL, false, false),
  ('Companheiro', 'VI. Organização e liderança', 6, 70, '2', '2', '4', 'Segurança e primeiros socorros', 'Planejamento', 23, NULL, false, false),
  ('Companheiro', 'VI. Organização e liderança', 6, 71, '2', '2', '5', 'Programação e atividades', 'Planejamento', 23, NULL, false, false),
  ('Companheiro', 'VI. Organização e liderança', 6, 72, '2', '2', '6', 'Equipamentos e infraestrutura', 'Planejamento', 23, NULL, false, false),
  ('Companheiro', 'VI. Organização e liderança', 6, 73, '2.1', '2', NULL, 'Escrever o cronograma do acampamento, local escolhido, data de realização e o que faria diferente na próxima vez.', 'Requisito', 23, NULL, false, false),
  ('Companheiro', 'VII. Estudo da natureza', 7, 74, '1', '1', NULL, 'Participar de jogos na natureza ou caminhada ecológica pelo período de uma hora.', 'Requisito', 24, NULL, false, true),
  ('Companheiro', 'VII. Estudo da natureza', 7, 75, '1.1', '1', NULL, 'Fazer relatório sobre a atividade da qual participou.', 'Requisito', 24, NULL, false, false),
  ('Companheiro', 'VII. Estudo da natureza', 7, 76, '2', '2', NULL, 'Completar uma especialidade: Anfíbios, Aves, Aves domésticas, Pecuária, Répteis, Moluscos, Árvores ou Arbustos.', 'Requisito', 25, NULL, false, true),
  ('Companheiro', 'VII. Estudo da natureza', 7, 77, '3', '3', NULL, 'Recapitular o estudo da Criação e fazer um diário por sete dias, registrando observações do que foi criado em cada dia.', 'Requisito', 29, NULL, false, true),
  ('Companheiro', 'VII. Estudo da natureza', 7, 78, '3', '3', '1º dia', 'Registrar o que Deus criou/fez: Luz e separação das trevas, e explicar a importância para a vida hoje.', 'Diário', 30, NULL, false, false),
  ('Companheiro', 'VII. Estudo da natureza', 7, 79, '3', '3', '2º dia', 'Registrar o que Deus criou/fez: Firmamento e separação das águas, e explicar a importância para a vida hoje.', 'Diário', 31, NULL, false, false),
  ('Companheiro', 'VII. Estudo da natureza', 7, 80, '3', '3', '3º dia', 'Registrar o que Deus criou/fez: Terra seca, mares e vegetação, e explicar a importância para a vida hoje.', 'Diário', 32, NULL, false, false),
  ('Companheiro', 'VII. Estudo da natureza', 7, 81, '3', '3', '4º dia', 'Registrar o que Deus criou/fez: Sol, lua e estrelas, e explicar a importância para a vida hoje.', 'Diário', 33, NULL, false, false),
  ('Companheiro', 'VII. Estudo da natureza', 7, 82, '3', '3', '5º dia', 'Registrar o que Deus criou/fez: Animais aquáticos e aves, e explicar a importância para a vida hoje.', 'Diário', 34, NULL, false, false),
  ('Companheiro', 'VII. Estudo da natureza', 7, 83, '3', '3', '6º dia', 'Registrar o que Deus criou/fez: Animais terrestres e ser humano, e explicar a importância para a vida hoje.', 'Diário', 35, NULL, false, false),
  ('Companheiro', 'VII. Estudo da natureza', 7, 84, '3', '3', '7º dia', 'Registrar o que Deus criou/fez: Descanso, bênção e santificação do sábado, e explicar a importância para a vida hoje.', 'Diário', 36, NULL, false, false),
  ('Companheiro', 'VII. Estudo da natureza', 7, 85, '3.8', '3', NULL, 'Citar três versos bíblicos que confirmem o sábado como dia especial e refletir sobre como ele pode melhorar a vida.', 'Requisito', 36, NULL, false, false),
  ('Companheiro', 'VIII. Arte de acampar', 8, 86, '1', '1', NULL, 'Descobrir os pontos cardeais sem bússola e desenhar a Rosa dos Ventos.', 'Requisito', 37, NULL, false, true),
  ('Companheiro', 'VIII. Arte de acampar', 8, 87, '1.1', '1', NULL, 'Identificar norte ao meio-dia e os pontos colaterais correspondentes às 9h e 15h.', 'Requisito', 37, NULL, false, false),
  ('Companheiro', 'VIII. Arte de acampar', 8, 88, '2', '2', NULL, 'Participar de acampamento de final de semana e fazer relatório destacando o que mais impressionou positivamente.', 'Requisito', 38, NULL, false, true),
  ('Companheiro', 'VIII. Arte de acampar', 8, 89, '2.1', '2', NULL, 'Marcar verdadeiro ou falso nas frases sobre escolha e montagem do acampamento.', 'Requisito', 38, NULL, false, false),
  ('Companheiro', 'VIII. Arte de acampar', 8, 90, '3', '3', NULL, 'Aprender ou recapitular os nós: oito, volta do salteador, duplo, caminhoneiro, direito, volta do fiel, escota, lais de guia e simples.', 'Requisito', 39, NULL, false, true),
  ('Companheiro', 'VIII. Arte de acampar', 8, 91, '3', '3', 'Oito', 'Registrar o uso prático do nó.', 'Nó', 39, NULL, false, false),
  ('Companheiro', 'VIII. Arte de acampar', 8, 92, '3', '3', 'Volta do salteador', 'Registrar o uso prático do nó.', 'Nó', 39, NULL, false, false),
  ('Companheiro', 'VIII. Arte de acampar', 8, 93, '3', '3', 'Nó duplo', 'Registrar o uso prático do nó.', 'Nó', 39, NULL, false, false),
  ('Companheiro', 'VIII. Arte de acampar', 8, 94, '3', '3', 'Caminhoneiro', 'Registrar o uso prático do nó.', 'Nó', 39, NULL, false, false),
  ('Companheiro', 'VIII. Arte de acampar', 8, 95, '3', '3', 'Nó direito', 'Registrar o uso prático do nó.', 'Nó', 40, NULL, false, false),
  ('Companheiro', 'VIII. Arte de acampar', 8, 96, '3', '3', 'Volta do fiel', 'Registrar o uso prático do nó.', 'Nó', 40, NULL, false, false),
  ('Companheiro', 'VIII. Arte de acampar', 8, 97, '3', '3', 'Escota', 'Registrar o uso prático do nó.', 'Nó', 40, NULL, false, false),
  ('Companheiro', 'VIII. Arte de acampar', 8, 98, '3', '3', 'Lais de guia', 'Registrar o uso prático do nó.', 'Nó', 40, NULL, false, false),
  ('Companheiro', 'VIII. Arte de acampar', 8, 99, '3', '3', 'Nó simples', 'Registrar o uso prático do nó.', 'Nó', 40, NULL, false, false),
  ('Companheiro', 'IX. Estilo de vida', 9, 100, '1', '1', NULL, 'Completar uma especialidade não realizada anteriormente na seção de Artes e habilidades manuais.', 'Requisito', 41, NULL, false, true),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 101, '1', '1', NULL, 'Aprender e demonstrar a composição, significado e uso correto da Bandeira Nacional.', 'Requisito', 41, NULL, true, true),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 102, '1.1', '1', NULL, 'Colar ou desenhar uma bandeira do Brasil, identificando as constelações representadas.', 'Requisito', 41, NULL, true, false),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 103, '1.2', '1', NULL, 'Explicar o significado das cores verde, amarelo, azul e branco.', 'Requisito', 42, NULL, true, false),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 104, '1.3', '1', NULL, 'Marcar as frases que demonstram o uso correto da Bandeira Nacional.', 'Requisito', 42, NULL, true, false),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 105, '2', '2', NULL, 'Ler a primeira visão de Ellen White e discutir como Deus usa os profetas para apresentar Sua mensagem à igreja.', 'Requisito', 43, NULL, true, true),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 106, '2.1', '2', NULL, 'Responder ao questionário sobre a primeira visão.', 'Requisito', 45, NULL, true, false),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 107, '2.2', '2', NULL, 'Encontrar três versos bíblicos sobre o uso dos profetas no passado e um sobre o futuro.', 'Requisito', 46, NULL, true, false),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 108, '2.3', '2', NULL, 'Ler 1 João 4:1-6, ler um relato biográfico sobre Ellen White e escrever como sua vida demonstrou que ela foi profetisa verdadeira.', 'Requisito', 46, NULL, true, false),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 109, '3', '3', NULL, 'Participar de atividade missionária ou comunitária, envolvendo também um amigo.', 'Requisito', 47, NULL, true, true),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 110, '3.1', '3', NULL, 'Registrar nome e idade do amigo, atividade, data e breve relatório.', 'Requisito', 47, NULL, true, false),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 111, '4', '4', NULL, 'Conversar sobre respeito aos pais ou responsáveis e fazer uma lista mostrando como cuidam de você.', 'Requisito', 48, NULL, true, true),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 112, '4.1', '4', NULL, 'Encontrar as palavras destacadas de Êxodo 20:12 no caça-palavras.', 'Requisito', 48, NULL, true, false),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 113, '4.2', '4', NULL, 'Listar dez coisas que os pais providenciam e cinco atitudes novas para demonstrar respeito e amor.', 'Requisito', 48, NULL, true, false),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 114, '5', '5', NULL, 'Participar de uma caminhada de 6 km e preparar relatório de uma página.', 'Requisito', 49, NULL, true, true),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 115, '5.1', '5', NULL, 'Registrar local, data, ponto de vista mais bonita e momento mais difícil.', 'Requisito', 49, NULL, true, false),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 116, '6', '6', NULL, 'Escolher: curso para deixar de fumar; dois filmes sobre saúde; cartaz sobre drogas; apoio a exposição/passeata; ou pesquisa sobre saúde.', 'Requisito', 50, NULL, true, true),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 117, '7', '7', NULL, 'Identificar e descrever doze aves nativas e doze árvores nativas.', 'Requisito', 52, NULL, true, true),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 118, '7.1', '7', NULL, 'Colar figuras ou fotos e registrar nome e descrição de cada espécie.', 'Requisito', 52, NULL, true, false),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 119, '8', '8', NULL, 'Participar de uma cerimônia: investidura, admissão em lenço ou Dia Mundial do Desbravador; sugerir ideias criativas.', 'Requisito', 54, NULL, true, true),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 120, '8.1', '8', NULL, 'Registrar cerimônia escolhida, data, local, pontos a melhorar e uma ideia criativa.', 'Requisito', 54, NULL, true, false),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 121, '9', '9', NULL, 'Preparar uma refeição em fogueira durante acampamento do Clube ou Unidade.', 'Requisito', 55, NULL, true, true),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 122, '9.1', '9', NULL, 'Listar alimentos que podem ser preparados sem utensílios e preparar pelo menos cinco deles.', 'Requisito', 55, NULL, true, false),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 123, '9.2', '9', NULL, 'Descrever o cardápio da refeição preparada.', 'Requisito', 55, NULL, true, false),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 124, '10', '10', NULL, 'Preparar um quadro com quinze nós diferentes.', 'Requisito', 56, NULL, true, true),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 125, '11', '11', NULL, 'Completar a especialidade de Excursionismo pedestre com mochila.', 'Requisito', 56, 'Excursionismo pedestre com mochila', true, true),
  ('Companheiro', 'Classe avançada – Excursionismo com mochila', 11, 126, '11', '11', '1', 'Explicar o lema dos excursionistas: da natureza nada se tira além de fotos; não deixar nada além de pegadas; não matar nada além do tempo.', 'Especialidade', 56, NULL, true, false),
  ('Companheiro', 'Classe avançada – Excursionismo com mochila', 11, 127, '11', '11', '2', 'Descrever vestuário, calçado e equipamentos para clima chuvoso, quente e frio.', 'Especialidade', 56, NULL, true, false),
  ('Companheiro', 'Classe avançada – Excursionismo com mochila', 11, 128, '11', '11', '3', 'Descrever critérios para escolher mochila e alternativa de emergência.', 'Especialidade', 57, NULL, true, false),
  ('Companheiro', 'Classe avançada – Excursionismo com mochila', 11, 129, '11', '11', '4', 'Relacionar objetos essenciais para excursionismo.', 'Especialidade', 57, NULL, true, false),
  ('Companheiro', 'Classe avançada – Excursionismo com mochila', 11, 130, '11', '11', '5', 'Relacionar cinco modelos de sacos de dormir e o clima adequado.', 'Especialidade', 57, NULL, true, false),
  ('Companheiro', 'Classe avançada – Excursionismo com mochila', 11, 131, '11', '11', '6', 'Demonstrar como arrumar uma mochila.', 'Especialidade', 57, NULL, true, false),
  ('Companheiro', 'Classe avançada – Excursionismo com mochila', 11, 132, '11', '11', '7', 'Planejar alimentação, cardápio para dois dias, embalagem e lanche para caminhada.', 'Especialidade', 57, NULL, true, false),
  ('Companheiro', 'Classe avançada – Excursionismo com mochila', 11, 133, '11', '11', '8', 'Conhecer prevenção, sintomas e primeiros socorros para queimadura solar, bolhas, hipotermia, insolação, exaustão, picadas de cobra, cólicas, desidratação e câimbra.', 'Especialidade', 57, NULL, true, false),
  ('Companheiro', 'Classe avançada – Excursionismo com mochila', 11, 134, '11', '11', '9', 'Ter kit de primeiros socorros e saber usar cada item.', 'Especialidade', 57, NULL, true, false),
  ('Companheiro', 'Classe avançada – Excursionismo com mochila', 11, 135, '11', '11', '10', 'Calcular o peso máximo a carregar de acordo com o peso corporal.', 'Especialidade', 57, NULL, true, false),
  ('Companheiro', 'Classe avançada – Excursionismo com mochila', 11, 136, '11', '11', '11', 'Conhecer três métodos sem bússola para encontrar pontos cardeais e demonstrar dois.', 'Especialidade', 57, NULL, true, false),
  ('Companheiro', 'Classe avançada – Excursionismo com mochila', 11, 137, '11', '11', '12', 'Demonstrar como colocar e tirar mochila sozinho e com ajuda.', 'Especialidade', 57, NULL, true, false),
  ('Companheiro', 'Classe avançada – Excursionismo com mochila', 11, 138, '11', '11', '13', 'Participar de excursão de fim de semana com caminhada de pelo menos 8 km e cozinhar as refeições durante a excursão.', 'Especialidade', 57, NULL, true, false),
  ('Companheiro', 'Classe avançada – Companheiro de excursionista', 10, 139, '12', '12', NULL, 'Completar uma especialidade não realizada anteriormente: habilidades domésticas, ciência e saúde, atividades missionárias ou atividades agrícolas.', 'Requisito', 57, NULL, true, true);
