-- Seed do plano de 365 dias do Ano Biblico (gerado por scripts/gerar_seed_ano_biblico.py a partir do PDF fornecido pelo usuario).
-- Nao editar a mao: rode o script novamente e substitua este arquivo.

INSERT INTO public.ano_biblico_catalogo
  (mes, dia, ano_bissexto, ordem_no_ano, livro_abrev, livro_nome, referencia, passagens)
VALUES
  (1, 1, FALSE, 1, 'Gn', 'Gênesis', 'Gn1', '[{"livro_abrev": "Gn", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 2, FALSE, 2, 'Gn', 'Gênesis', 'Gn2', '[{"livro_abrev": "Gn", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 3, FALSE, 3, 'Gn', 'Gênesis', 'Gn3', '[{"livro_abrev": "Gn", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 4, FALSE, 4, 'Gn', 'Gênesis', 'Gn4:1-16', '[{"livro_abrev": "Gn", "capitulo": 4, "verso_ini": 1, "verso_fim": 16}]'::jsonb),
  (1, 5, FALSE, 5, 'Gn', 'Gênesis', 'Gn6', '[{"livro_abrev": "Gn", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 6, FALSE, 6, 'Gn', 'Gênesis', 'Gn7', '[{"livro_abrev": "Gn", "capitulo": 7, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 7, FALSE, 7, 'Gn', 'Gênesis', 'Gn8', '[{"livro_abrev": "Gn", "capitulo": 8, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 8, FALSE, 8, 'Gn', 'Gênesis', 'Gn9:1-19', '[{"livro_abrev": "Gn", "capitulo": 9, "verso_ini": 1, "verso_fim": 19}]'::jsonb),
  (1, 9, FALSE, 9, 'Gn', 'Gênesis', 'Gn11:1-19,12:1-13', '[{"livro_abrev": "Gn", "capitulo": 11, "verso_ini": 1, "verso_fim": 19}, {"livro_abrev": "Gn", "capitulo": 12, "verso_ini": 1, "verso_fim": 13}]'::jsonb),
  (1, 10, FALSE, 10, 'Gn', 'Gênesis', 'Gn14', '[{"livro_abrev": "Gn", "capitulo": 14, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 11, FALSE, 11, 'Gn', 'Gênesis', 'Gn15', '[{"livro_abrev": "Gn", "capitulo": 15, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 12, FALSE, 12, 'Gn', 'Gênesis', 'Gn17:1-22', '[{"livro_abrev": "Gn", "capitulo": 17, "verso_ini": 1, "verso_fim": 22}]'::jsonb),
  (1, 13, FALSE, 13, 'Gn', 'Gênesis', 'Gn18', '[{"livro_abrev": "Gn", "capitulo": 18, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 14, FALSE, 14, 'Gn', 'Gênesis', 'Gn19:1-29', '[{"livro_abrev": "Gn", "capitulo": 19, "verso_ini": 1, "verso_fim": 29}]'::jsonb),
  (1, 15, FALSE, 15, 'Gn', 'Gênesis', 'Gn21:1-21', '[{"livro_abrev": "Gn", "capitulo": 21, "verso_ini": 1, "verso_fim": 21}]'::jsonb),
  (1, 16, FALSE, 16, 'Gn', 'Gênesis', 'Gn22:1-19', '[{"livro_abrev": "Gn", "capitulo": 22, "verso_ini": 1, "verso_fim": 19}]'::jsonb),
  (1, 17, FALSE, 17, 'Gn', 'Gênesis', 'Gn23', '[{"livro_abrev": "Gn", "capitulo": 23, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 18, FALSE, 18, 'Gn', 'Gênesis', 'Gn24', '[{"livro_abrev": "Gn", "capitulo": 24, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 19, FALSE, 19, 'Gn', 'Gênesis', 'Gn27', '[{"livro_abrev": "Gn", "capitulo": 27, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 20, FALSE, 20, 'Gn', 'Gênesis', 'Gn28', '[{"livro_abrev": "Gn", "capitulo": 28, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 21, FALSE, 21, 'Gn', 'Gênesis', 'Gn29:1-30', '[{"livro_abrev": "Gn", "capitulo": 29, "verso_ini": 1, "verso_fim": 30}]'::jsonb),
  (1, 22, FALSE, 22, 'Gn', 'Gênesis', 'Gn31:1-3,17-18', '[{"livro_abrev": "Gn", "capitulo": 31, "verso_ini": 1, "verso_fim": 3}, {"livro_abrev": "Gn", "capitulo": 31, "verso_ini": 17, "verso_fim": 18}]'::jsonb),
  (1, 23, FALSE, 23, 'Gn', 'Gênesis', 'Gn32', '[{"livro_abrev": "Gn", "capitulo": 32, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 24, FALSE, 24, 'Gn', 'Gênesis', 'Gn33', '[{"livro_abrev": "Gn", "capitulo": 33, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 25, FALSE, 25, 'Gn', 'Gênesis', 'Gn35:1-20', '[{"livro_abrev": "Gn", "capitulo": 35, "verso_ini": 1, "verso_fim": 20}]'::jsonb),
  (1, 26, FALSE, 26, 'Gn', 'Gênesis', 'Gn37', '[{"livro_abrev": "Gn", "capitulo": 37, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 27, FALSE, 27, 'Gn', 'Gênesis', 'Gn39', '[{"livro_abrev": "Gn", "capitulo": 39, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 28, FALSE, 28, 'Gn', 'Gênesis', 'Gn40', '[{"livro_abrev": "Gn", "capitulo": 40, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 29, FALSE, 29, 'Gn', 'Gênesis', 'Gn41', '[{"livro_abrev": "Gn", "capitulo": 41, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 30, FALSE, 30, 'Gn', 'Gênesis', 'Gn42', '[{"livro_abrev": "Gn", "capitulo": 42, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (1, 31, FALSE, 31, 'Gn', 'Gênesis', 'Gn43', '[{"livro_abrev": "Gn", "capitulo": 43, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 1, FALSE, 32, 'Gn', 'Gênesis', 'Gn44', '[{"livro_abrev": "Gn", "capitulo": 44, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 2, FALSE, 33, 'Gn', 'Gênesis', 'Gn45', '[{"livro_abrev": "Gn", "capitulo": 45, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 3, FALSE, 34, 'Gn', 'Gênesis', 'Gn46:1-7,28-34', '[{"livro_abrev": "Gn", "capitulo": 46, "verso_ini": 1, "verso_fim": 7}, {"livro_abrev": "Gn", "capitulo": 46, "verso_ini": 28, "verso_fim": 34}]'::jsonb),
  (2, 4, FALSE, 35, 'Gn', 'Gênesis', 'Gn47', '[{"livro_abrev": "Gn", "capitulo": 47, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 5, FALSE, 36, 'Gn', 'Gênesis', 'Gn48', '[{"livro_abrev": "Gn", "capitulo": 48, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 6, FALSE, 37, 'Gn', 'Gênesis', 'Gn49', '[{"livro_abrev": "Gn", "capitulo": 49, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 7, FALSE, 38, 'Gn', 'Gênesis', 'Gn50', '[{"livro_abrev": "Gn", "capitulo": 50, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 8, FALSE, 39, 'Ex', 'Êxodo', 'Ex1', '[{"livro_abrev": "Ex", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 9, FALSE, 40, 'Ex', 'Êxodo', 'Ex2', '[{"livro_abrev": "Ex", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 10, FALSE, 41, 'Ex', 'Êxodo', 'Ex3', '[{"livro_abrev": "Ex", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 11, FALSE, 42, 'Ex', 'Êxodo', 'Ex4:1-17,27-31', '[{"livro_abrev": "Ex", "capitulo": 4, "verso_ini": 1, "verso_fim": 17}, {"livro_abrev": "Ex", "capitulo": 4, "verso_ini": 27, "verso_fim": 31}]'::jsonb),
  (2, 12, FALSE, 43, 'Ex', 'Êxodo', 'Ex5', '[{"livro_abrev": "Ex", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 13, FALSE, 44, 'Ex', 'Êxodo', 'Ex7', '[{"livro_abrev": "Ex", "capitulo": 7, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 14, FALSE, 45, 'Ex', 'Êxodo', 'Ex8', '[{"livro_abrev": "Ex", "capitulo": 8, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 15, FALSE, 46, 'Ex', 'Êxodo', 'Ex9', '[{"livro_abrev": "Ex", "capitulo": 9, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 16, FALSE, 47, 'Ex', 'Êxodo', 'Ex10', '[{"livro_abrev": "Ex", "capitulo": 10, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 17, FALSE, 48, 'Ex', 'Êxodo', 'Ex11', '[{"livro_abrev": "Ex", "capitulo": 11, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 18, FALSE, 49, 'Ex', 'Êxodo', 'Ex12', '[{"livro_abrev": "Ex", "capitulo": 12, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 19, FALSE, 50, 'Ex', 'Êxodo', 'Ex13:17-22,14', '[{"livro_abrev": "Ex", "capitulo": 13, "verso_ini": 17, "verso_fim": 22}, {"livro_abrev": "Ex", "capitulo": 14, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 20, FALSE, 51, 'Ex', 'Êxodo', 'Ex15:22-27', '[{"livro_abrev": "Ex", "capitulo": 15, "verso_ini": 22, "verso_fim": 27}]'::jsonb),
  (2, 21, FALSE, 52, 'Ex', 'Êxodo', 'Ex16', '[{"livro_abrev": "Ex", "capitulo": 16, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 22, FALSE, 53, 'Ex', 'Êxodo', 'Ex17', '[{"livro_abrev": "Ex", "capitulo": 17, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 23, FALSE, 54, 'Ex', 'Êxodo', 'Ex18', '[{"livro_abrev": "Ex", "capitulo": 18, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 24, FALSE, 55, 'Ex', 'Êxodo', 'Ex19', '[{"livro_abrev": "Ex", "capitulo": 19, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 25, FALSE, 56, 'Ex', 'Êxodo', 'Ex20', '[{"livro_abrev": "Ex", "capitulo": 20, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 26, FALSE, 57, 'Ex', 'Êxodo', 'Ex24', '[{"livro_abrev": "Ex", "capitulo": 24, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 27, FALSE, 58, 'Ex', 'Êxodo', 'Ex32', '[{"livro_abrev": "Ex", "capitulo": 32, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 28, FALSE, 59, 'Ex', 'Êxodo', 'Ex33', '[{"livro_abrev": "Ex", "capitulo": 33, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (2, 28, TRUE, 59, 'Ex', 'Êxodo', 'Ex33:1-11', '[{"livro_abrev": "Ex", "capitulo": 33, "verso_ini": 1, "verso_fim": 11}]'::jsonb),
  (2, 29, TRUE, 60, 'Ex', 'Êxodo', 'Ex33:12-23', '[{"livro_abrev": "Ex", "capitulo": 33, "verso_ini": 12, "verso_fim": 23}]'::jsonb),
  (3, 1, FALSE, 60, 'Ex', 'Êxodo', 'Ex34:1-14,21-25', '[{"livro_abrev": "Ex", "capitulo": 34, "verso_ini": 1, "verso_fim": 14}, {"livro_abrev": "Ex", "capitulo": 34, "verso_ini": 21, "verso_fim": 25}]'::jsonb),
  (3, 2, FALSE, 61, 'Ex', 'Êxodo', 'Ex35:1-29,40', '[{"livro_abrev": "Ex", "capitulo": 35, "verso_ini": 1, "verso_fim": 29}, {"livro_abrev": "Ex", "capitulo": 40, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 3, FALSE, 62, 'Lv', 'Levítico', 'Lv11', '[{"livro_abrev": "Lv", "capitulo": 11, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 4, FALSE, 63, 'Nm', 'Números', 'Nm9:15-23,11', '[{"livro_abrev": "Nm", "capitulo": 9, "verso_ini": 15, "verso_fim": 23}, {"livro_abrev": "Nm", "capitulo": 11, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 5, FALSE, 64, 'Nm', 'Números', 'Nm13', '[{"livro_abrev": "Nm", "capitulo": 13, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 6, FALSE, 65, 'Nm', 'Números', 'Nm14', '[{"livro_abrev": "Nm", "capitulo": 14, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 7, FALSE, 66, 'Nm', 'Números', 'Nm16', '[{"livro_abrev": "Nm", "capitulo": 16, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 8, FALSE, 67, 'Nm', 'Números', 'Nm17,20', '[{"livro_abrev": "Nm", "capitulo": 17, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Nm", "capitulo": 20, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 9, FALSE, 68, 'Nm', 'Números', 'Nm21', '[{"livro_abrev": "Nm", "capitulo": 21, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 10, FALSE, 69, 'Nm', 'Números', 'Nm22', '[{"livro_abrev": "Nm", "capitulo": 22, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 11, FALSE, 70, 'Nm', 'Números', 'Nm23', '[{"livro_abrev": "Nm", "capitulo": 23, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 12, FALSE, 71, 'Nm', 'Números', 'Nm24', '[{"livro_abrev": "Nm", "capitulo": 24, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 13, FALSE, 72, 'Nm', 'Números', 'Nm35', '[{"livro_abrev": "Nm", "capitulo": 35, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 14, FALSE, 73, 'Dt', 'Deuteronômio', 'Dt1:1-17', '[{"livro_abrev": "Dt", "capitulo": 1, "verso_ini": 1, "verso_fim": 17}]'::jsonb),
  (3, 15, FALSE, 74, 'Dt', 'Deuteronômio', 'Dt5', '[{"livro_abrev": "Dt", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 16, FALSE, 75, 'Dt', 'Deuteronômio', 'Dt32', '[{"livro_abrev": "Dt", "capitulo": 32, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 17, FALSE, 76, 'Dt', 'Deuteronômio', 'Dt33,34', '[{"livro_abrev": "Dt", "capitulo": 33, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Dt", "capitulo": 34, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 18, FALSE, 77, 'Js', 'Josué', 'Js1', '[{"livro_abrev": "Js", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 19, FALSE, 78, 'Js', 'Josué', 'Js2', '[{"livro_abrev": "Js", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 20, FALSE, 79, 'Js', 'Josué', 'Js3', '[{"livro_abrev": "Js", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 21, FALSE, 80, 'Js', 'Josué', 'Js4', '[{"livro_abrev": "Js", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 22, FALSE, 81, 'Js', 'Josué', 'Js5:10-15,6', '[{"livro_abrev": "Js", "capitulo": 5, "verso_ini": 10, "verso_fim": 15}, {"livro_abrev": "Js", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 23, FALSE, 82, 'Js', 'Josué', 'Js7', '[{"livro_abrev": "Js", "capitulo": 7, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 24, FALSE, 83, 'Js', 'Josué', 'Js8', '[{"livro_abrev": "Js", "capitulo": 8, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 25, FALSE, 84, 'Js', 'Josué', 'Js10:1-27', '[{"livro_abrev": "Js", "capitulo": 10, "verso_ini": 1, "verso_fim": 27}]'::jsonb),
  (3, 26, FALSE, 85, 'Js', 'Josué', 'Js24', '[{"livro_abrev": "Js", "capitulo": 24, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 27, FALSE, 86, 'Jz', 'Juízes', 'Jz6', '[{"livro_abrev": "Jz", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 28, FALSE, 87, 'Jz', 'Juízes', 'Jz7', '[{"livro_abrev": "Jz", "capitulo": 7, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 29, FALSE, 88, 'Jz', 'Juízes', 'Jz13,14', '[{"livro_abrev": "Jz", "capitulo": 13, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Jz", "capitulo": 14, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 30, FALSE, 89, 'Jz', 'Juízes', 'Jz15,16', '[{"livro_abrev": "Jz", "capitulo": 15, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Jz", "capitulo": 16, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (3, 31, FALSE, 90, 'Rt', 'Rute', 'Rt1,2', '[{"livro_abrev": "Rt", "capitulo": 1, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Rt", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 1, FALSE, 91, 'Rt', 'Rute', 'Rt3,4', '[{"livro_abrev": "Rt", "capitulo": 3, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Rt", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 2, FALSE, 92, '1Sm', '1 Samuel', '1Sm1', '[{"livro_abrev": "1Sm", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 3, FALSE, 93, '1Sm', '1 Samuel', '1Sm2', '[{"livro_abrev": "1Sm", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 4, FALSE, 94, '1Sm', '1 Samuel', '1Sm3', '[{"livro_abrev": "1Sm", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 5, FALSE, 95, '1Sm', '1 Samuel', '1Sm4', '[{"livro_abrev": "1Sm", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 6, FALSE, 96, '1Sm', '1 Samuel', '1Sm5,6', '[{"livro_abrev": "1Sm", "capitulo": 5, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "1Sm", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 7, FALSE, 97, '1Sm', '1 Samuel', '1Sm7', '[{"livro_abrev": "1Sm", "capitulo": 7, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 8, FALSE, 98, '1Sm', '1 Samuel', '1Sm8', '[{"livro_abrev": "1Sm", "capitulo": 8, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 9, FALSE, 99, '1Sm', '1 Samuel', '1Sm9', '[{"livro_abrev": "1Sm", "capitulo": 9, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 10, FALSE, 100, '1Sm', '1 Samuel', '1Sm10', '[{"livro_abrev": "1Sm", "capitulo": 10, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 11, FALSE, 101, '1Sm', '1 Samuel', '1Sm11:12-15', '[{"livro_abrev": "1Sm", "capitulo": 11, "verso_ini": 12, "verso_fim": 15}]'::jsonb),
  (4, 12, FALSE, 102, '1Sm', '1 Samuel', '1Sm12', '[{"livro_abrev": "1Sm", "capitulo": 12, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 13, FALSE, 103, '1Sm', '1 Samuel', '1Sm13', '[{"livro_abrev": "1Sm", "capitulo": 13, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 14, FALSE, 104, '1Sm', '1 Samuel', '1Sm14', '[{"livro_abrev": "1Sm", "capitulo": 14, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 15, FALSE, 105, '1Sm', '1 Samuel', '1Sm15', '[{"livro_abrev": "1Sm", "capitulo": 15, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 16, FALSE, 106, '1Sm', '1 Samuel', '1Sm16', '[{"livro_abrev": "1Sm", "capitulo": 16, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 17, FALSE, 107, '1Sm', '1 Samuel', '1Sm17', '[{"livro_abrev": "1Sm", "capitulo": 17, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 18, FALSE, 108, '1Sm', '1 Samuel', '1Sm18:1-19', '[{"livro_abrev": "1Sm", "capitulo": 18, "verso_ini": 1, "verso_fim": 19}]'::jsonb),
  (4, 19, FALSE, 109, '1Sm', '1 Samuel', '1Sm20', '[{"livro_abrev": "1Sm", "capitulo": 20, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 20, FALSE, 110, '1Sm', '1 Samuel', '1Sm24', '[{"livro_abrev": "1Sm", "capitulo": 24, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 21, FALSE, 111, '1Sm', '1 Samuel', '1Sm25', '[{"livro_abrev": "1Sm", "capitulo": 25, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 22, FALSE, 112, '1Sm', '1 Samuel', '1Sm26', '[{"livro_abrev": "1Sm", "capitulo": 26, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 23, FALSE, 113, '1Sm', '1 Samuel', '1Sm31', '[{"livro_abrev": "1Sm", "capitulo": 31, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 24, FALSE, 114, '2Sm', '2 Samuel', '2Sm1', '[{"livro_abrev": "2Sm", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 25, FALSE, 115, '2Sm', '2 Samuel', '2Sm5', '[{"livro_abrev": "2Sm", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 26, FALSE, 116, '2Sm', '2 Samuel', '2Sm7', '[{"livro_abrev": "2Sm", "capitulo": 7, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 27, FALSE, 117, '2Sm', '2 Samuel', '2Sm15', '[{"livro_abrev": "2Sm", "capitulo": 15, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 28, FALSE, 118, '2Sm', '2 Samuel', '2Sm17', '[{"livro_abrev": "2Sm", "capitulo": 17, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 29, FALSE, 119, '2Sm', '2 Samuel', '2Sm18', '[{"livro_abrev": "2Sm", "capitulo": 18, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (4, 30, FALSE, 120, '1Rs', '1 Reis', '1Rs1:28-53', '[{"livro_abrev": "1Rs", "capitulo": 1, "verso_ini": 28, "verso_fim": 53}]'::jsonb),
  (5, 1, FALSE, 121, '1Rs', '1 Reis', '1Rs3', '[{"livro_abrev": "1Rs", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 2, FALSE, 122, '1Rs', '1 Reis', '1Rs4:20-34', '[{"livro_abrev": "1Rs", "capitulo": 4, "verso_ini": 20, "verso_fim": 34}]'::jsonb),
  (5, 3, FALSE, 123, '1Rs', '1 Reis', '1Rs5', '[{"livro_abrev": "1Rs", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 4, FALSE, 124, '1Rs', '1 Reis', '1Rs6', '[{"livro_abrev": "1Rs", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 5, FALSE, 125, '1Rs', '1 Reis', '1Rs7', '[{"livro_abrev": "1Rs", "capitulo": 7, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 6, FALSE, 126, '1Rs', '1 Reis', '1Rs8', '[{"livro_abrev": "1Rs", "capitulo": 8, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 7, FALSE, 127, '1Rs', '1 Reis', '1Rs10', '[{"livro_abrev": "1Rs", "capitulo": 10, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 8, FALSE, 128, '1Rs', '1 Reis', '1Rs11:6-43', '[{"livro_abrev": "1Rs", "capitulo": 11, "verso_ini": 6, "verso_fim": 43}]'::jsonb),
  (5, 9, FALSE, 129, '1Rs', '1 Reis', '1Rs12', '[{"livro_abrev": "1Rs", "capitulo": 12, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 10, FALSE, 130, '1Rs', '1 Reis', '1Rs17', '[{"livro_abrev": "1Rs", "capitulo": 17, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 11, FALSE, 131, '1Rs', '1 Reis', '1Rs18', '[{"livro_abrev": "1Rs", "capitulo": 18, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 12, FALSE, 132, '1Rs', '1 Reis', '1Rs19', '[{"livro_abrev": "1Rs", "capitulo": 19, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 13, FALSE, 133, '1Rs', '1 Reis', '1Rs21', '[{"livro_abrev": "1Rs", "capitulo": 21, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 14, FALSE, 134, '2Rs', '2 Reis', '2Rs1', '[{"livro_abrev": "2Rs", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 15, FALSE, 135, '2Rs', '2 Reis', '2Rs2', '[{"livro_abrev": "2Rs", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 16, FALSE, 136, '2Rs', '2 Reis', '2Rs4', '[{"livro_abrev": "2Rs", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 17, FALSE, 137, '2Rs', '2 Reis', '2Rs5', '[{"livro_abrev": "2Rs", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 18, FALSE, 138, '2Rs', '2 Reis', '2Rs6:1-7', '[{"livro_abrev": "2Rs", "capitulo": 6, "verso_ini": 1, "verso_fim": 7}]'::jsonb),
  (5, 19, FALSE, 139, '2Rs', '2 Reis', '2Rs18', '[{"livro_abrev": "2Rs", "capitulo": 18, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 20, FALSE, 140, '2Rs', '2 Reis', '2Rs19', '[{"livro_abrev": "2Rs", "capitulo": 19, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 21, FALSE, 141, '2Rs', '2 Reis', '2Rs20', '[{"livro_abrev": "2Rs", "capitulo": 20, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 22, FALSE, 142, '2Rs', '2 Reis', '2Rs22', '[{"livro_abrev": "2Rs", "capitulo": 22, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 23, FALSE, 143, '2Rs', '2 Reis', '2Rs23:36-37', '[{"livro_abrev": "2Rs", "capitulo": 23, "verso_ini": 36, "verso_fim": 37}]'::jsonb),
  (5, 24, FALSE, 144, '2Rs', '2 Reis', '2Rs24', '[{"livro_abrev": "2Rs", "capitulo": 24, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 25, FALSE, 145, '2Rs', '2 Reis', '2Rs25:1-22', '[{"livro_abrev": "2Rs", "capitulo": 25, "verso_ini": 1, "verso_fim": 22}]'::jsonb),
  (5, 26, FALSE, 146, '2Cr', '2 Crônicas', '2Cr36', '[{"livro_abrev": "2Cr", "capitulo": 36, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 27, FALSE, 147, 'Ed', 'Esdras', 'Ed1', '[{"livro_abrev": "Ed", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 28, FALSE, 148, 'Ed', 'Esdras', 'Ed3,4', '[{"livro_abrev": "Ed", "capitulo": 3, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Ed", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 29, FALSE, 149, 'Ed', 'Esdras', 'Ed5,6', '[{"livro_abrev": "Ed", "capitulo": 5, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Ed", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 30, FALSE, 150, 'Ed', 'Esdras', 'Ed7', '[{"livro_abrev": "Ed", "capitulo": 7, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (5, 31, FALSE, 151, 'Ne', 'Neemias', 'Ne1,2', '[{"livro_abrev": "Ne", "capitulo": 1, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Ne", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 1, FALSE, 152, 'Ne', 'Neemias', 'Ne4', '[{"livro_abrev": "Ne", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 2, FALSE, 153, 'Ne', 'Neemias', 'Ne5', '[{"livro_abrev": "Ne", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 3, FALSE, 154, 'Ne', 'Neemias', 'Ne6', '[{"livro_abrev": "Ne", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 4, FALSE, 155, 'Ne', 'Neemias', 'Ne8', '[{"livro_abrev": "Ne", "capitulo": 8, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 5, FALSE, 156, 'Et', 'Ester', 'Et1', '[{"livro_abrev": "Et", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 6, FALSE, 157, 'Et', 'Ester', 'Et2', '[{"livro_abrev": "Et", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 7, FALSE, 158, 'Et', 'Ester', 'Et3', '[{"livro_abrev": "Et", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 8, FALSE, 159, 'Et', 'Ester', 'Et4', '[{"livro_abrev": "Et", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 9, FALSE, 160, 'Et', 'Ester', 'Et5', '[{"livro_abrev": "Et", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 10, FALSE, 161, 'Et', 'Ester', 'Et6', '[{"livro_abrev": "Et", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 11, FALSE, 162, 'Et', 'Ester', 'Et7', '[{"livro_abrev": "Et", "capitulo": 7, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 12, FALSE, 163, 'Et', 'Ester', 'Et8', '[{"livro_abrev": "Et", "capitulo": 8, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 13, FALSE, 164, 'Et', 'Ester', 'Et9', '[{"livro_abrev": "Et", "capitulo": 9, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 14, FALSE, 165, 'Jó', 'Jó', 'Jó1', '[{"livro_abrev": "Jó", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 15, FALSE, 166, 'Jó', 'Jó', 'Jó2', '[{"livro_abrev": "Jó", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 16, FALSE, 167, 'Jó', 'Jó', 'Jó42', '[{"livro_abrev": "Jó", "capitulo": 42, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 17, FALSE, 168, 'Sl', 'Salmos', 'Sl1,15,19', '[{"livro_abrev": "Sl", "capitulo": 1, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Sl", "capitulo": 15, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Sl", "capitulo": 19, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 18, FALSE, 169, 'Sl', 'Salmos', 'Sl23,24,27', '[{"livro_abrev": "Sl", "capitulo": 23, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Sl", "capitulo": 24, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Sl", "capitulo": 27, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 19, FALSE, 170, 'Sl', 'Salmos', 'Sl37', '[{"livro_abrev": "Sl", "capitulo": 37, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 20, FALSE, 171, 'Sl', 'Salmos', 'Sl39,42,46', '[{"livro_abrev": "Sl", "capitulo": 39, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Sl", "capitulo": 42, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Sl", "capitulo": 46, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 21, FALSE, 172, 'Sl', 'Salmos', 'Sl67,73,84', '[{"livro_abrev": "Sl", "capitulo": 67, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Sl", "capitulo": 73, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Sl", "capitulo": 84, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 22, FALSE, 173, 'Sl', 'Salmos', 'Sl90,91,92', '[{"livro_abrev": "Sl", "capitulo": 90, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Sl", "capitulo": 91, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Sl", "capitulo": 92, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 23, FALSE, 174, 'Sl', 'Salmos', 'Sl97,98,103', '[{"livro_abrev": "Sl", "capitulo": 97, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Sl", "capitulo": 98, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Sl", "capitulo": 103, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 24, FALSE, 175, 'Sl', 'Salmos', 'Sl117,119:1-80', '[{"livro_abrev": "Sl", "capitulo": 117, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Sl", "capitulo": 119, "verso_ini": 1, "verso_fim": 80}]'::jsonb),
  (6, 25, FALSE, 176, 'Sl', 'Salmos', 'Sl119:81-176', '[{"livro_abrev": "Sl", "capitulo": 119, "verso_ini": 81, "verso_fim": 176}]'::jsonb),
  (6, 26, FALSE, 177, 'Sl', 'Salmos', 'Sl121,125,148', '[{"livro_abrev": "Sl", "capitulo": 121, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Sl", "capitulo": 125, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Sl", "capitulo": 148, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 27, FALSE, 178, 'Pv', 'Provérbios', 'Pv1', '[{"livro_abrev": "Pv", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 28, FALSE, 179, 'Pv', 'Provérbios', 'Pv3', '[{"livro_abrev": "Pv", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 29, FALSE, 180, 'Pv', 'Provérbios', 'Pv4', '[{"livro_abrev": "Pv", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (6, 30, FALSE, 181, 'Pv', 'Provérbios', 'Pv10', '[{"livro_abrev": "Pv", "capitulo": 10, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 1, FALSE, 182, 'Pv', 'Provérbios', 'Pv15', '[{"livro_abrev": "Pv", "capitulo": 15, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 2, FALSE, 183, 'Pv', 'Provérbios', 'Pv25', '[{"livro_abrev": "Pv", "capitulo": 25, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 3, FALSE, 184, 'Pv', 'Provérbios', 'Pv31:10-31', '[{"livro_abrev": "Pv", "capitulo": 31, "verso_ini": 10, "verso_fim": 31}]'::jsonb),
  (7, 4, FALSE, 185, 'Ec', 'Eclesiastes', 'Ec5', '[{"livro_abrev": "Ec", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 5, FALSE, 186, 'Ec', 'Eclesiastes', 'Ec7', '[{"livro_abrev": "Ec", "capitulo": 7, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 6, FALSE, 187, 'Ec', 'Eclesiastes', 'Ec11,12', '[{"livro_abrev": "Ec", "capitulo": 11, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Ec", "capitulo": 12, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 7, FALSE, 188, 'Is', 'Isaías', 'Is5', '[{"livro_abrev": "Is", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 8, FALSE, 189, 'Is', 'Isaías', 'Is11', '[{"livro_abrev": "Is", "capitulo": 11, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 9, FALSE, 190, 'Is', 'Isaías', 'Is26', '[{"livro_abrev": "Is", "capitulo": 26, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 10, FALSE, 191, 'Is', 'Isaías', 'Is35', '[{"livro_abrev": "Is", "capitulo": 35, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 11, FALSE, 192, 'Is', 'Isaías', 'Is40', '[{"livro_abrev": "Is", "capitulo": 40, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 12, FALSE, 193, 'Is', 'Isaías', 'Is42,43', '[{"livro_abrev": "Is", "capitulo": 42, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Is", "capitulo": 43, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 13, FALSE, 194, 'Is', 'Isaías', 'Is53', '[{"livro_abrev": "Is", "capitulo": 53, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 14, FALSE, 195, 'Is', 'Isaías', 'Is54', '[{"livro_abrev": "Is", "capitulo": 54, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 15, FALSE, 196, 'Is', 'Isaías', 'Is60,61', '[{"livro_abrev": "Is", "capitulo": 60, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Is", "capitulo": 61, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 16, FALSE, 197, 'Jr', 'Jeremias', 'Jr9:23-26,10', '[{"livro_abrev": "Jr", "capitulo": 9, "verso_ini": 23, "verso_fim": 26}, {"livro_abrev": "Jr", "capitulo": 10, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 17, FALSE, 198, 'Jr', 'Jeremias', 'Jr26', '[{"livro_abrev": "Jr", "capitulo": 26, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 18, FALSE, 199, 'Jr', 'Jeremias', 'Jr52', '[{"livro_abrev": "Jr", "capitulo": 52, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 19, FALSE, 200, 'Dn', 'Daniel', 'Dn1', '[{"livro_abrev": "Dn", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 20, FALSE, 201, 'Dn', 'Daniel', 'Dn2', '[{"livro_abrev": "Dn", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 21, FALSE, 202, 'Dn', 'Daniel', 'Dn3', '[{"livro_abrev": "Dn", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 22, FALSE, 203, 'Dn', 'Daniel', 'Dn4', '[{"livro_abrev": "Dn", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 23, FALSE, 204, 'Dn', 'Daniel', 'Dn5', '[{"livro_abrev": "Dn", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 24, FALSE, 205, 'Dn', 'Daniel', 'Dn6', '[{"livro_abrev": "Dn", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 25, FALSE, 206, 'Dn', 'Daniel', 'Dn7', '[{"livro_abrev": "Dn", "capitulo": 7, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 26, FALSE, 207, 'Dn', 'Daniel', 'Dn8', '[{"livro_abrev": "Dn", "capitulo": 8, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 27, FALSE, 208, 'Dn', 'Daniel', 'Dn9', '[{"livro_abrev": "Dn", "capitulo": 9, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 28, FALSE, 209, 'Dn', 'Daniel', 'Dn10', '[{"livro_abrev": "Dn", "capitulo": 10, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 29, FALSE, 210, 'Dn', 'Daniel', 'Dn11', '[{"livro_abrev": "Dn", "capitulo": 11, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 30, FALSE, 211, 'Dn', 'Daniel', 'Dn12', '[{"livro_abrev": "Dn", "capitulo": 12, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (7, 31, FALSE, 212, 'Jl', 'Joel', 'Jl2,Am8', '[{"livro_abrev": "Jl", "capitulo": 2, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Am", "capitulo": 8, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 1, FALSE, 213, 'Jn', 'Jonas', 'Jn1,2', '[{"livro_abrev": "Jn", "capitulo": 1, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Jn", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 2, FALSE, 214, 'Jn', 'Jonas', 'Jn3,4', '[{"livro_abrev": "Jn", "capitulo": 3, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Jn", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 3, FALSE, 215, 'Mq', 'Miquéias', 'Mq4', '[{"livro_abrev": "Mq", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 4, FALSE, 216, 'Ag', 'Ageu', 'Ag2', '[{"livro_abrev": "Ag", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 5, FALSE, 217, 'Zc', 'Zacarias', 'Zc4', '[{"livro_abrev": "Zc", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 6, FALSE, 218, 'Ml', 'Malaquias', 'Ml3,4', '[{"livro_abrev": "Ml", "capitulo": 3, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Ml", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 7, FALSE, 219, 'Mt', 'Mateus', 'Mt1', '[{"livro_abrev": "Mt", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 8, FALSE, 220, 'Mt', 'Mateus', 'Mt2', '[{"livro_abrev": "Mt", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 9, FALSE, 221, 'Mt', 'Mateus', 'Mt3', '[{"livro_abrev": "Mt", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 10, FALSE, 222, 'Mt', 'Mateus', 'Mt4', '[{"livro_abrev": "Mt", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 11, FALSE, 223, 'Mt', 'Mateus', 'Mt5', '[{"livro_abrev": "Mt", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 12, FALSE, 224, 'Mt', 'Mateus', 'Mt6', '[{"livro_abrev": "Mt", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 13, FALSE, 225, 'Mt', 'Mateus', 'Mt7', '[{"livro_abrev": "Mt", "capitulo": 7, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 14, FALSE, 226, 'Mt', 'Mateus', 'Mt8', '[{"livro_abrev": "Mt", "capitulo": 8, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 15, FALSE, 227, 'Mt', 'Mateus', 'Mt9', '[{"livro_abrev": "Mt", "capitulo": 9, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 16, FALSE, 228, 'Mt', 'Mateus', 'Mt10', '[{"livro_abrev": "Mt", "capitulo": 10, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 17, FALSE, 229, 'Mt', 'Mateus', 'Mt11', '[{"livro_abrev": "Mt", "capitulo": 11, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 18, FALSE, 230, 'Mt', 'Mateus', 'Mt12', '[{"livro_abrev": "Mt", "capitulo": 12, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 19, FALSE, 231, 'Mt', 'Mateus', 'Mt13', '[{"livro_abrev": "Mt", "capitulo": 13, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 20, FALSE, 232, 'Mt', 'Mateus', 'Mt14', '[{"livro_abrev": "Mt", "capitulo": 14, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 21, FALSE, 233, 'Mt', 'Mateus', 'Mt15', '[{"livro_abrev": "Mt", "capitulo": 15, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 22, FALSE, 234, 'Mt', 'Mateus', 'Mt16', '[{"livro_abrev": "Mt", "capitulo": 16, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 23, FALSE, 235, 'Mt', 'Mateus', 'Mt17', '[{"livro_abrev": "Mt", "capitulo": 17, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 24, FALSE, 236, 'Mt', 'Mateus', 'Mt18', '[{"livro_abrev": "Mt", "capitulo": 18, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 25, FALSE, 237, 'Mt', 'Mateus', 'Mt19', '[{"livro_abrev": "Mt", "capitulo": 19, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 26, FALSE, 238, 'Mt', 'Mateus', 'Mt20', '[{"livro_abrev": "Mt", "capitulo": 20, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 27, FALSE, 239, 'Mt', 'Mateus', 'Mt21', '[{"livro_abrev": "Mt", "capitulo": 21, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 28, FALSE, 240, 'Mt', 'Mateus', 'Mt22', '[{"livro_abrev": "Mt", "capitulo": 22, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 29, FALSE, 241, 'Mt', 'Mateus', 'Mt23', '[{"livro_abrev": "Mt", "capitulo": 23, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 30, FALSE, 242, 'Mt', 'Mateus', 'Mt24', '[{"livro_abrev": "Mt", "capitulo": 24, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (8, 31, FALSE, 243, 'Mt', 'Mateus', 'Mt25', '[{"livro_abrev": "Mt", "capitulo": 25, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 1, FALSE, 244, 'Mt', 'Mateus', 'Mt26', '[{"livro_abrev": "Mt", "capitulo": 26, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 2, FALSE, 245, 'Mt', 'Mateus', 'Mt27', '[{"livro_abrev": "Mt", "capitulo": 27, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 3, FALSE, 246, 'Mt', 'Mateus', 'Mt28', '[{"livro_abrev": "Mt", "capitulo": 28, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 4, FALSE, 247, 'Mc', 'Marcos', 'Mc1', '[{"livro_abrev": "Mc", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 5, FALSE, 248, 'Mc', 'Marcos', 'Mc2', '[{"livro_abrev": "Mc", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 6, FALSE, 249, 'Mc', 'Marcos', 'Mc3', '[{"livro_abrev": "Mc", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 7, FALSE, 250, 'Mc', 'Marcos', 'Mc4', '[{"livro_abrev": "Mc", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 8, FALSE, 251, 'Mc', 'Marcos', 'Mc5', '[{"livro_abrev": "Mc", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 9, FALSE, 252, 'Mc', 'Marcos', 'Mc6', '[{"livro_abrev": "Mc", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 10, FALSE, 253, 'Mc', 'Marcos', 'Mc7', '[{"livro_abrev": "Mc", "capitulo": 7, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 11, FALSE, 254, 'Mc', 'Marcos', 'Mc8', '[{"livro_abrev": "Mc", "capitulo": 8, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 12, FALSE, 255, 'Mc', 'Marcos', 'Mc9', '[{"livro_abrev": "Mc", "capitulo": 9, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 13, FALSE, 256, 'Mc', 'Marcos', 'Mc10', '[{"livro_abrev": "Mc", "capitulo": 10, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 14, FALSE, 257, 'Mc', 'Marcos', 'Mc11', '[{"livro_abrev": "Mc", "capitulo": 11, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 15, FALSE, 258, 'Mc', 'Marcos', 'Mc12', '[{"livro_abrev": "Mc", "capitulo": 12, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 16, FALSE, 259, 'Mc', 'Marcos', 'Mc13', '[{"livro_abrev": "Mc", "capitulo": 13, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 17, FALSE, 260, 'Mc', 'Marcos', 'Mc14', '[{"livro_abrev": "Mc", "capitulo": 14, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 18, FALSE, 261, 'Mc', 'Marcos', 'Mc15', '[{"livro_abrev": "Mc", "capitulo": 15, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 19, FALSE, 262, 'Mc', 'Marcos', 'Mc16', '[{"livro_abrev": "Mc", "capitulo": 16, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 20, FALSE, 263, 'Lc', 'Lucas', 'Lc1', '[{"livro_abrev": "Lc", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 21, FALSE, 264, 'Lc', 'Lucas', 'Lc2', '[{"livro_abrev": "Lc", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 22, FALSE, 265, 'Lc', 'Lucas', 'Lc3', '[{"livro_abrev": "Lc", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 23, FALSE, 266, 'Lc', 'Lucas', 'Lc4', '[{"livro_abrev": "Lc", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 24, FALSE, 267, 'Lc', 'Lucas', 'Lc5', '[{"livro_abrev": "Lc", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 25, FALSE, 268, 'Lc', 'Lucas', 'Lc6', '[{"livro_abrev": "Lc", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 26, FALSE, 269, 'Lc', 'Lucas', 'Lc7', '[{"livro_abrev": "Lc", "capitulo": 7, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 27, FALSE, 270, 'Lc', 'Lucas', 'Lc8', '[{"livro_abrev": "Lc", "capitulo": 8, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 28, FALSE, 271, 'Lc', 'Lucas', 'Lc9', '[{"livro_abrev": "Lc", "capitulo": 9, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 29, FALSE, 272, 'Lc', 'Lucas', 'Lc10', '[{"livro_abrev": "Lc", "capitulo": 10, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (9, 30, FALSE, 273, 'Lc', 'Lucas', 'Lc11', '[{"livro_abrev": "Lc", "capitulo": 11, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 1, FALSE, 274, 'Lc', 'Lucas', 'Lc12', '[{"livro_abrev": "Lc", "capitulo": 12, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 2, FALSE, 275, 'Lc', 'Lucas', 'Lc13', '[{"livro_abrev": "Lc", "capitulo": 13, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 3, FALSE, 276, 'Lc', 'Lucas', 'Lc14', '[{"livro_abrev": "Lc", "capitulo": 14, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 4, FALSE, 277, 'Lc', 'Lucas', 'Lc15', '[{"livro_abrev": "Lc", "capitulo": 15, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 5, FALSE, 278, 'Lc', 'Lucas', 'Lc16', '[{"livro_abrev": "Lc", "capitulo": 16, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 6, FALSE, 279, 'Lc', 'Lucas', 'Lc17', '[{"livro_abrev": "Lc", "capitulo": 17, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 7, FALSE, 280, 'Lc', 'Lucas', 'Lc18', '[{"livro_abrev": "Lc", "capitulo": 18, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 8, FALSE, 281, 'Lc', 'Lucas', 'Lc19', '[{"livro_abrev": "Lc", "capitulo": 19, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 9, FALSE, 282, 'Lc', 'Lucas', 'Lc20', '[{"livro_abrev": "Lc", "capitulo": 20, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 10, FALSE, 283, 'Lc', 'Lucas', 'Lc21', '[{"livro_abrev": "Lc", "capitulo": 21, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 11, FALSE, 284, 'Lc', 'Lucas', 'Lc22', '[{"livro_abrev": "Lc", "capitulo": 22, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 12, FALSE, 285, 'Lc', 'Lucas', 'Lc23', '[{"livro_abrev": "Lc", "capitulo": 23, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 13, FALSE, 286, 'Lc', 'Lucas', 'Lc24', '[{"livro_abrev": "Lc", "capitulo": 24, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 14, FALSE, 287, 'Jo', 'João', 'Jo1', '[{"livro_abrev": "Jo", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 15, FALSE, 288, 'Jo', 'João', 'Jo2', '[{"livro_abrev": "Jo", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 16, FALSE, 289, 'Jo', 'João', 'Jo3', '[{"livro_abrev": "Jo", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 17, FALSE, 290, 'Jo', 'João', 'Jo4', '[{"livro_abrev": "Jo", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 18, FALSE, 291, 'Jo', 'João', 'Jo5', '[{"livro_abrev": "Jo", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 19, FALSE, 292, 'Jo', 'João', 'Jo6', '[{"livro_abrev": "Jo", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 20, FALSE, 293, 'Jo', 'João', 'Jo7', '[{"livro_abrev": "Jo", "capitulo": 7, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 21, FALSE, 294, 'Jo', 'João', 'Jo8', '[{"livro_abrev": "Jo", "capitulo": 8, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 22, FALSE, 295, 'Jo', 'João', 'Jo9', '[{"livro_abrev": "Jo", "capitulo": 9, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 23, FALSE, 296, 'Jo', 'João', 'Jo10', '[{"livro_abrev": "Jo", "capitulo": 10, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 24, FALSE, 297, 'Jo', 'João', 'Jo11', '[{"livro_abrev": "Jo", "capitulo": 11, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 25, FALSE, 298, 'Jo', 'João', 'Jo12', '[{"livro_abrev": "Jo", "capitulo": 12, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 26, FALSE, 299, 'Jo', 'João', 'Jo13', '[{"livro_abrev": "Jo", "capitulo": 13, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 27, FALSE, 300, 'Jo', 'João', 'Jo14', '[{"livro_abrev": "Jo", "capitulo": 14, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 28, FALSE, 301, 'Jo', 'João', 'Jo15', '[{"livro_abrev": "Jo", "capitulo": 15, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 29, FALSE, 302, 'Jo', 'João', 'Jo16', '[{"livro_abrev": "Jo", "capitulo": 16, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 30, FALSE, 303, 'Jo', 'João', 'Jo17', '[{"livro_abrev": "Jo", "capitulo": 17, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (10, 31, FALSE, 304, 'Jo', 'João', 'Jo18', '[{"livro_abrev": "Jo", "capitulo": 18, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 1, FALSE, 305, 'Jo', 'João', 'Jo19', '[{"livro_abrev": "Jo", "capitulo": 19, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 2, FALSE, 306, 'Jo', 'João', 'Jo20', '[{"livro_abrev": "Jo", "capitulo": 20, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 3, FALSE, 307, 'Jo', 'João', 'Jo21', '[{"livro_abrev": "Jo", "capitulo": 21, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 4, FALSE, 308, 'At', 'Atos', 'At1', '[{"livro_abrev": "At", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 5, FALSE, 309, 'At', 'Atos', 'At2', '[{"livro_abrev": "At", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 6, FALSE, 310, 'At', 'Atos', 'At3', '[{"livro_abrev": "At", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 7, FALSE, 311, 'At', 'Atos', 'At4', '[{"livro_abrev": "At", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 8, FALSE, 312, 'At', 'Atos', 'At5', '[{"livro_abrev": "At", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 9, FALSE, 313, 'At', 'Atos', 'At6', '[{"livro_abrev": "At", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 10, FALSE, 314, 'At', 'Atos', 'At7', '[{"livro_abrev": "At", "capitulo": 7, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 11, FALSE, 315, 'At', 'Atos', 'At8', '[{"livro_abrev": "At", "capitulo": 8, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 12, FALSE, 316, 'At', 'Atos', 'At9', '[{"livro_abrev": "At", "capitulo": 9, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 13, FALSE, 317, 'At', 'Atos', 'At10', '[{"livro_abrev": "At", "capitulo": 10, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 14, FALSE, 318, 'At', 'Atos', 'At11', '[{"livro_abrev": "At", "capitulo": 11, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 15, FALSE, 319, 'At', 'Atos', 'At12', '[{"livro_abrev": "At", "capitulo": 12, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 16, FALSE, 320, 'At', 'Atos', 'At13', '[{"livro_abrev": "At", "capitulo": 13, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 17, FALSE, 321, 'At', 'Atos', 'At14', '[{"livro_abrev": "At", "capitulo": 14, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 18, FALSE, 322, 'At', 'Atos', 'At15', '[{"livro_abrev": "At", "capitulo": 15, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 19, FALSE, 323, 'At', 'Atos', 'At16', '[{"livro_abrev": "At", "capitulo": 16, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 20, FALSE, 324, 'At', 'Atos', 'At17', '[{"livro_abrev": "At", "capitulo": 17, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 21, FALSE, 325, 'At', 'Atos', 'At18', '[{"livro_abrev": "At", "capitulo": 18, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 22, FALSE, 326, 'At', 'Atos', 'At19', '[{"livro_abrev": "At", "capitulo": 19, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 23, FALSE, 327, 'At', 'Atos', 'At20', '[{"livro_abrev": "At", "capitulo": 20, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 24, FALSE, 328, 'At', 'Atos', 'At21', '[{"livro_abrev": "At", "capitulo": 21, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 25, FALSE, 329, 'At', 'Atos', 'At22', '[{"livro_abrev": "At", "capitulo": 22, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 26, FALSE, 330, 'At', 'Atos', 'At23', '[{"livro_abrev": "At", "capitulo": 23, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 27, FALSE, 331, 'At', 'Atos', 'At24', '[{"livro_abrev": "At", "capitulo": 24, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 28, FALSE, 332, 'At', 'Atos', 'At25', '[{"livro_abrev": "At", "capitulo": 25, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 29, FALSE, 333, 'At', 'Atos', 'At26', '[{"livro_abrev": "At", "capitulo": 26, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (11, 30, FALSE, 334, 'At', 'Atos', 'At27', '[{"livro_abrev": "At", "capitulo": 27, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 1, FALSE, 335, 'At', 'Atos', 'At28', '[{"livro_abrev": "At", "capitulo": 28, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 2, FALSE, 336, 'Rm', 'Romanos', 'Rm1', '[{"livro_abrev": "Rm", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 3, FALSE, 337, 'Rm', 'Romanos', 'Rm3', '[{"livro_abrev": "Rm", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 4, FALSE, 338, 'Rm', 'Romanos', 'Rm5', '[{"livro_abrev": "Rm", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 5, FALSE, 339, 'Rm', 'Romanos', 'Rm6', '[{"livro_abrev": "Rm", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 6, FALSE, 340, 'Rm', 'Romanos', 'Rm8', '[{"livro_abrev": "Rm", "capitulo": 8, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 7, FALSE, 341, 'Rm', 'Romanos', 'Rm12', '[{"livro_abrev": "Rm", "capitulo": 12, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 8, FALSE, 342, '1Co', '1 Coríntios', '1Co1', '[{"livro_abrev": "1Co", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 9, FALSE, 343, '1Co', '1 Coríntios', '1Co2', '[{"livro_abrev": "1Co", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 10, FALSE, 344, '1Co', '1 Coríntios', '1Co3', '[{"livro_abrev": "1Co", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 11, FALSE, 345, '1Co', '1 Coríntios', '1Co6', '[{"livro_abrev": "1Co", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 12, FALSE, 346, '1Co', '1 Coríntios', '1Co8', '[{"livro_abrev": "1Co", "capitulo": 8, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 13, FALSE, 347, '1Co', '1 Coríntios', '1Co10', '[{"livro_abrev": "1Co", "capitulo": 10, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 14, FALSE, 348, '1Co', '1 Coríntios', '1Co11', '[{"livro_abrev": "1Co", "capitulo": 11, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 15, FALSE, 349, '1Co', '1 Coríntios', '1Co12', '[{"livro_abrev": "1Co", "capitulo": 12, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 16, FALSE, 350, '1Co', '1 Coríntios', '1Co13', '[{"livro_abrev": "1Co", "capitulo": 13, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 17, FALSE, 351, '1Co', '1 Coríntios', '1Co15', '[{"livro_abrev": "1Co", "capitulo": 15, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 18, FALSE, 352, '2Co', '2 Coríntios', '2Co4', '[{"livro_abrev": "2Co", "capitulo": 4, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 19, FALSE, 353, '2Co', '2 Coríntios', '2Co5', '[{"livro_abrev": "2Co", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 20, FALSE, 354, 'Gl', 'Gálatas', 'Gl5', '[{"livro_abrev": "Gl", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 21, FALSE, 355, 'Ef', 'Efésios', 'Ef2', '[{"livro_abrev": "Ef", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 22, FALSE, 356, 'Ef', 'Efésios', 'Ef6', '[{"livro_abrev": "Ef", "capitulo": 6, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 23, FALSE, 357, 'Fp', 'Filipenses', 'Fp2', '[{"livro_abrev": "Fp", "capitulo": 2, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 24, FALSE, 358, 'Cl', 'Colossenses', 'Cl1', '[{"livro_abrev": "Cl", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 25, FALSE, 359, 'Cl', 'Colossenses', 'Cl3', '[{"livro_abrev": "Cl", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 26, FALSE, 360, '1Ts', '1 Tessalonicenses', '1Ts5', '[{"livro_abrev": "1Ts", "capitulo": 5, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 27, FALSE, 361, '2Tm', '2 Timóteo', '2Tm3', '[{"livro_abrev": "2Tm", "capitulo": 3, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 28, FALSE, 362, 'Hb', 'Hebreus', 'Hb11', '[{"livro_abrev": "Hb", "capitulo": 11, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 29, FALSE, 363, 'Tg', 'Tiago', 'Tg1', '[{"livro_abrev": "Tg", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 30, FALSE, 364, '1Pe', '1 Pedro', '1Pe1', '[{"livro_abrev": "1Pe", "capitulo": 1, "verso_ini": null, "verso_fim": null}]'::jsonb),
  (12, 31, FALSE, 365, 'Ap', 'Apocalipse', 'Ap21,22', '[{"livro_abrev": "Ap", "capitulo": 21, "verso_ini": null, "verso_fim": null}, {"livro_abrev": "Ap", "capitulo": 22, "verso_ini": null, "verso_fim": null}]'::jsonb)
ON CONFLICT (mes, dia, ano_bissexto) DO UPDATE SET
  ordem_no_ano = EXCLUDED.ordem_no_ano,
  livro_abrev = EXCLUDED.livro_abrev,
  livro_nome = EXCLUDED.livro_nome,
  referencia = EXCLUDED.referencia,
  passagens = EXCLUDED.passagens,
  updated_at = now();
