-- Listas oficiais dos mestrados (Manual de Especialidades DSA, edicao 2025, paginas 363 a 369).
-- Ensinos Biblicos: 14 das 27 especialidades da secao (pagina 90). Os 4 mestrados de area
-- (ADRA, Artes, Agricolas, Habilidades Domesticas) ja estao ativos e conferem com o manual.
-- Tudo ou nada: se algum nome nao casar com o catalogo, o script para sem alterar nada.
-- Ao ativar, os membros que ja cumprem a regra vao direto para a fila da diretoria.
CREATE OR REPLACE FUNCTION pg_temp.aplicar_lista(p_codigo text, p_qtd integer, p_nomes text[]) RETURNS void
LANGUAGE plpgsql AS $f$
DECLARE
  m public.mestrados%ROWTYPE;
  v_prog integer := (SELECT id FROM public.programas WHERE nome ILIKE '%desbravador%' ORDER BY id LIMIT 1);
  v_falta text;
  v_erro text;
  v_snap jsonb;
BEGIN
  SELECT * INTO m FROM public.mestrados WHERE codigo = p_codigo FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Mestrado % nao existe.', p_codigo; END IF;

  SELECT string_agg(n, '; ') INTO v_falta
  FROM unnest(p_nomes) n
  WHERE NOT EXISTS (
    SELECT 1 FROM public.especialidades_modelo em
    WHERE em.ativo = TRUE AND em.programa_id = v_prog AND public.mestrado_norm(em.nome) = public.mestrado_norm(n));
  IF v_falta IS NOT NULL THEN RAISE EXCEPTION '% - nao encontrei no catalogo: %', p_codigo, v_falta; END IF;

  DELETE FROM public.mestrado_especialidades WHERE mestrado_id = m.id;
  INSERT INTO public.mestrado_especialidades (mestrado_id, especialidade_id, obrigatoria)
  SELECT m.id, em.id, FALSE
  FROM public.especialidades_modelo em
  WHERE em.ativo = TRUE AND em.programa_id = v_prog
    AND public.mestrado_norm(em.nome) IN (SELECT public.mestrado_norm(n) FROM unnest(p_nomes) n)
  ON CONFLICT DO NOTHING;

  UPDATE public.mestrados SET
    quantidade_exigida = p_qtd, fonte = 'Manual de Especialidades DSA', edicao = '2025',
    observacoes = CASE WHEN p_codigo = 'ME-016' THEN '14 especialidades de Ensinos Biblicos' ELSE '7 da lista do manual' END || ' (Manual 2025, pag. 363 a 369).',
    situacao = 'rascunho', atualizado_em = now()
  WHERE id = m.id;

  v_erro := public.mestrado_validar(m.id);
  IF v_erro IS NOT NULL THEN RAISE EXCEPTION '% - nao foi possivel ativar: %', p_codigo, v_erro; END IF;

  UPDATE public.mestrados SET situacao = 'ativo' WHERE id = m.id;
  SELECT * INTO m FROM public.mestrados WHERE id = m.id;
  v_snap := jsonb_build_object('codigo', m.codigo, 'nome', m.nome, 'quantidade_exigida', m.quantidade_exigida, 'areas', m.areas,
    'fonte', m.fonte, 'edicao', m.edicao, 'observacoes', m.observacoes, 'situacao', m.situacao,
    'especialidades', (SELECT COALESCE(jsonb_agg(jsonb_build_object('id', me.especialidade_id, 'obrigatoria', me.obrigatoria, 'grupo_requisito', me.grupo_requisito)), '[]'::jsonb)
                        FROM public.mestrado_especialidades me WHERE me.mestrado_id = m.id));
  INSERT INTO public.mestrado_versoes (mestrado_id, versao, snapshot)
  VALUES (m.id, m.versao, v_snap)
  ON CONFLICT (mestrado_id, versao) DO UPDATE SET snapshot = EXCLUDED.snapshot, criado_em = now();
  PERFORM public.mestrado_reavaliar_todos(m.id);
END
$f$;

DO $$
BEGIN
  PERFORM pg_temp.aplicar_lista('ME-004', 7, ARRAY[
      'Adoração cristã',
      'Apocalipse',
      'Arqueologia bíblica',
      'Arte da pregação cristã',
      'Arte da pregação cristã - avançado',
      'Arte de contar histórias cristãs',
      'Arte em fantoches',
      'Arte em fantoches - avançado',
      'Asseio e cortesia cristã',
      'Aventuras com Cristo',
      'Aventuras com Cristo - avançado',
      'Braile',
      'Cidadania cristã',
      'Colportagem',
      'Criacionismo',
      'Criacionismo - avançado',
      'Crítico de mídia',
      'Dramatização cristã',
      'Escatologia',
      'Espírito de Profecia',
      'Etnologia missionária',
      'Evangelismo pessoal',
      'Evangelismo web',
      'Evangelismo web - avançado',
      'Historiador eclesiástico',
      'Intercessor',
      'Interpretação bíblica',
      'Investigador Bíblico I',
      'Liderança juvenil',
      'Língua de sinais',
      'Língua de sinais - avançado',
      'Lives - Transmissão de Cultos Online',
      'Livro de Daniel',
      'Marcação bíblica',
      'Marcação bíblica - avançado',
      'Mensageira de Deus',
      'Mordomia',
      'Pacificador',
      'Pacificador - avançado',
      'Parábolas de Jesus',
      'Pioneiros adventistas',
      'Pregador evangelista',
      'Pregador evangelista - avançado',
      'Relacionamentos saudáveis',
      'Santuário',
      'Sonoplastia',
      'Sonoplastia - avançado',
      'Temperança',
      'Testemunho juvenil',
      'Vida familiar']);
  PERFORM pg_temp.aplicar_lista('ME-005', 7, ARRAY[
      'Administração',
      'Alvenaria',
      'Barbearia',
      'Biblioteconomia',
      'Cães - cuidado e treinamento',
      'Carpintaria',
      'Colocação de papel de parede',
      'Conserto de sapatos',
      'Contabilidade',
      'Corte e costura',
      'Corte e costura - avançado',
      'Cuidados e manutenção de violões',
      'Desenvolvimento de software',
      'Eletricidade',
      'Eletrônica',
      'Encadernação',
      'Evangelismo',
      'Fotografia',
      'Hidráulica',
      'Informática programável',
      'Intérprete de língua de sinais',
      'Jornalismo',
      'Logística',
      'Magistério',
      'Manutenção de bicicletas',
      'Marcenaria',
      'Marketing',
      'Marketing - avançado',
      'Mecânica automotiva',
      'Mecânica de pequenos motores',
      'Modelagem têxtil',
      'Montagem e manutenção de computadores',
      'Noções de direito',
      'Noções de economia',
      'Ofício de alfaiate',
      'Operação e manutenção de impressoras',
      'Pintura de paredes exteriores',
      'Pintura de paredes interiores',
      'Produção de vídeo',
      'Radioamadorismo',
      'Restauro e conservação documental',
      'Secretariado',
      'Segurança contra incêndios',
      'Silvicultura',
      'Soldagem',
      'Taquigrafia',
      'Tipografia',
      'Vendas',
      'Web Design - básico',
      'Web Design - avançado']);
  PERFORM pg_temp.aplicar_lista('ME-006', 7, ARRAY[
      'Computação I - básico',
      'Computação II - médio',
      'Computação III - regular',
      'Computação IV - avançado',
      'Computação V - especialista',
      'Desenvolvimento de software',
      'Eletrônica',
      'Experimentos científicos',
      'Física',
      'Habilidades em matemática I',
      'Habilidades em matemática II',
      'Informática programável',
      'Internet',
      'Internet - avançado',
      'Metodologia de estudo',
      'Ótica',
      'Química',
      'Segurança nas redes sociais',
      'Web Design - básico',
      'Web Design - avançado']);
  PERFORM pg_temp.aplicar_lista('ME-007', 7, ARRAY[
      'Caiaque',
      'Canoagem',
      'Esqui aquático',
      'Mergulho autônomo',
      'Mergulho livre',
      'Natação principiante I',
      'Natação principiante II',
      'Natação intermediário I',
      'Natação intermediário II',
      'Natação - avançado',
      'Navegação',
      'Rafting',
      'Remo',
      'Saltos ornamentais',
      'Salvamento de afogados',
      'Salvamento de afogados - avançado',
      'Segurança básica na água',
      'Vela']);
  PERFORM pg_temp.aplicar_lista('ME-008', 7, ARRAY[
      'Arco e flecha',
      'Atletismo',
      'Basquete',
      'Ciclismo',
      'Ciclismo - avançado',
      'Cultura física',
      'Equitação',
      'Escalada',
      'Escalada - avançado',
      'Esportes adaptados',
      'Esqui aquático',
      'Exploração de cavernas',
      'Exploração de cavernas - avançado',
      'Futebol',
      'Futsal',
      'Ginástica acrobática',
      'Handebol',
      'Mountain biking',
      'Rapel',
      'Rapel - avançado',
      'Rapel - instrutor',
      'Softbol',
      'Tênis de mesa',
      'Triathlon',
      'Vôlei']);
  PERFORM pg_temp.aplicar_lista('ME-009', 7, ARRAY[
      'Acampamento consciente',
      'Acampamento em baixas temperaturas',
      'Acampamento I',
      'Acampamento II',
      'Acampamento III',
      'Acampamento IV',
      'Acampamento seguro',
      'Acampamento seguro - avançado',
      'Arte de acampar',
      'Artes mateiras',
      'Comida mateira',
      'Construções rústicas de grande porte',
      'Cozinha com forno holandês',
      'Escalada em árvores',
      'Excursionismo pedestre',
      'Excursionismo pedestre - avançado',
      'Excursionismo pedestre com mochila',
      'Excursionismo pedestre com mochila - avançado',
      'Excursionismo pedestre na neve',
      'Fogueiras e cozinha ao ar livre',
      'Liderança campestre',
      'Liderança campestre - avançado',
      'Liderança na selva',
      'Liderança na selva - avançado',
      'Mapa e bússola',
      'Nós e amarras',
      'Nós e amarras - avançado',
      'Orientação com GPS',
      'Pioneirias',
      'Pioneirias - avançado',
      'Pioneirismo',
      'Plantas silvestres comestíveis',
      'Trilha de sinais',
      'Vida silvestre']);
  PERFORM pg_temp.aplicar_lista('ME-010', 7, ARRAY[
      'Aquarismo',
      'Boliche',
      'Bolinha de gude',
      'Carrinho de rolimã',
      'Colecionador',
      'Cubo mágico',
      'Evolução em ordem unida',
      'Fanfarra',
      'Filatelia',
      'Futebol de botão',
      'Geocaching',
      'Geocaching - avançado',
      'Nós e amarras',
      'Nós e amarras - avançado',
      'Numismática',
      'Numismática - avançado',
      'Ordem unida',
      'Ordem unida - avançado',
      'Ordem unida - instrutor',
      'Patins',
      'Pião',
      'Pipas',
      'Segurança básica na água',
      'Skate',
      'Slackline',
      'Troca de pins',
      'Viagem e turismo',
      'Viagem e turismo - avançado']);
  PERFORM pg_temp.aplicar_lista('ME-011', 7, ARRAY[
      'Alerta vermelho',
      'Anatomia humana básica',
      'Bactérias',
      'Bioquímica',
      'Biossegurança',
      'Citologia',
      'Coração e circulação',
      'Digestão',
      'Enfermagem básica',
      'Hereditariedade',
      'Higiene oral',
      'Higiene oral - avançado',
      'Inteligência emocional',
      'Microscopia',
      'Nutrição',
      'Nutrição - avançado',
      'Ossos, músculos e articulações',
      'Plantas medicinais',
      'Prevenção de doenças tropicais',
      'Primeiros socorros - básico',
      'Primeiros socorros - intermediário',
      'Primeiros socorros - avançado',
      'Protozoários',
      'Reanimação cardiopulmonar',
      'Remédios da natureza',
      'Resgate básico',
      'Sangue e defesas do corpo',
      'Saúde e cura',
      'Saúde mental',
      'Sexualidade humana',
      'Sistema nervoso',
      'Sistema respiratório',
      'Vacinas',
      'Vírus',
      'Zoonoses']);
  PERFORM pg_temp.aplicar_lista('ME-012', 7, ARRAY[
      'Abelhas e vespas',
      'Anfíbios',
      'Anfíbios - avançado',
      'Animais migratórios',
      'Animais nocivos',
      'Animais noturnos',
      'Animais peçonhentos',
      'Aranhas',
      'Araras, papagaios e periquitos',
      'Aves',
      'Aves - avançado',
      'Aves de estimação',
      'Aves de rapina',
      'Aves domésticas',
      'Cães',
      'Camelos',
      'Cetáceos',
      'Cigarras',
      'Crustáceos',
      'Equinodermos',
      'Fauna marinha',
      'Felinos',
      'Felinos - avançado',
      'Formigas',
      'Insetos',
      'Insetos - avançado',
      'Mamíferos',
      'Mamíferos - avançado',
      'Mamíferos marinhos',
      'Mariposas e borboletas',
      'Marsupiais',
      'Mimetismo e camuflagem',
      'Moluscos',
      'Moluscos - avançado',
      'Morcegos',
      'Morcegos - avançado',
      'Odonata',
      'Peixes',
      'Peixes ornamentais',
      'Pequenos mamíferos de estimação',
      'Poríferos e cnidários',
      'Primatas',
      'Quelônios',
      'Rastreio de animais',
      'Rastreio de animais - avançado',
      'Rebanhos domésticos',
      'Répteis',
      'Répteis - avançado',
      'Tubarões',
      'Vermes',
      'Vermes - avançado',
      'Zoonoses']);
  PERFORM pg_temp.aplicar_lista('ME-013', 7, ARRAY[
      'Animais ameaçados de extinção',
      'Araras, papagaios e periquitos',
      'Compostagem doméstica',
      'Conservação ambiental',
      'Ecologia',
      'Ecologia - avançado',
      'Energias renováveis',
      'Estuário',
      'Preservação de recursos hídricos',
      'Quedas d''água',
      'Quelônios',
      'Reciclagem e sustentabilidade',
      'Reciclagem e sustentabilidade - avançado']);
  PERFORM pg_temp.aplicar_lista('ME-014', 7, ARRAY[
      'Algas',
      'Arbustos',
      'Arbustos - avançado',
      'Árvores',
      'Árvores - avançado',
      'Briófitas',
      'Bromélias',
      'Cactos',
      'Cactos - avançado',
      'Ervas',
      'Eucaliptos',
      'Fisiologia vegetal',
      'Flores',
      'Flores - avançado',
      'Gramíneas',
      'Líquens',
      'Orquídeas',
      'Orquídeas - avançado',
      'Palmeiras',
      'Plantas carnívoras',
      'Plantas caseiras',
      'Samambaias',
      'Sementes',
      'Sementes - avançado']);
  PERFORM pg_temp.aplicar_lista('ME-016', 14, ARRAY[
      'Escrituras sagradas',
      'Trindade',
      'Deus Pai',
      'Deus Filho',
      'Deus Espírito Santo',
      'Criação do mundo',
      'Natureza da humanidade',
      'Grande conflito',
      'Experiência da salvação',
      'Crescimento em Cristo',
      'Igreja',
      'Remanescente e sua missão',
      'Unidade no corpo de Cristo',
      'Batismo',
      'Ceia do Senhor',
      'Dons e ministérios espirituais',
      'Dom de profecia',
      'Lei de Deus',
      'Sábado',
      'Mordomia',
      'Conduta cristã',
      'Matrimônio e família',
      'Ministério de Cristo no santuário celestial',
      'Segunda vinda de Cristo',
      'Morte e ressurreição',
      'Milênio e Fim do Pecado',
      'Nova Terra']);
END $$;
