-- Requisitos das especialidades conforme o Manual de Especialidades 2025 (transcricao compilada em Word).
-- Substitui os requisitos de cada especialidade (a linha de cada requisito/subitem na ordem do manual) e
-- atualiza a quantidade de requisitos. Ortografia e acentos revisados. Parte 5 de 5.
-- Tudo ou nada: se alguma especialidade nao for encontrada pelo codigo, nada e alterado.
CREATE OR REPLACE FUNCTION pg_temp.set_req(p_codigo text, p_nivel text, p_linhas text[]) RETURNS void
LANGUAGE plpgsql AS $f$
DECLARE
  v_prog integer := (SELECT id FROM public.programas WHERE nome ILIKE '%desbravador%' ORDER BY id LIMIT 1);
  em public.especialidades_modelo%ROWTYPE;
BEGIN
  SELECT * INTO em FROM public.especialidades_modelo WHERE programa_id = v_prog AND codigo = p_codigo;
  IF NOT FOUND THEN RAISE EXCEPTION 'Especialidade % nao encontrada.', p_codigo; END IF;

  DELETE FROM public.mda_requisitos_modelo
   WHERE programa_id = v_prog AND item_tipo = 'Especialidade'
     AND (especialidade_id = em.id OR (especialidade_id IS NULL AND item_url IS NOT NULL AND item_url = em.item_url));

  INSERT INTO public.mda_requisitos_modelo (programa_id, item_tipo, item_nome, item_codigo, item_url, especialidade_id, secao, ordem, texto)
  SELECT v_prog, 'Especialidade', em.nome, em.codigo, COALESCE(em.item_url, 'manual-2025/' || em.codigo), em.id, NULL, t.ord::integer, t.txt
    FROM unnest(p_linhas) WITH ORDINALITY AS t(txt, ord);

  UPDATE public.especialidades_modelo
     SET quantidade_requisitos = array_length(p_linhas, 1),
         nivel = COALESCE(p_nivel, nivel),
         updated_at = now()
   WHERE id = em.id;
END
$f$;

DO $$
BEGIN
  PERFORM pg_temp.set_req('AR-121', NULL, ARRAY[
    '1. Explicar a origem do pin trading (troca de pins) e como essa prática começou no Clube de Desbravadores.',
    '2. Definir os seguintes termos:',
    'a) Botton;',
    'b) Pino;',
    'c) Etiqueta;',
    'd) Lanyard;',
    'e) Pin.',
    '3. Identificar dois tipos comuns de fechos para pins e demonstrar ou descrever como colocá-los e retirá-los com segurança.',
    '4. Saber onde é possível conseguir pins para trocar, incluindo pins gratuitos ou baratos. Conseguir, pelo menos, três pins para trocar.',
    '5. Discutir, pelo menos, cinco diferentes métodos de exibir seus pins para trocar. Escolher um método que você gostou e organizar seus pins para trocar.',
    '6. Nomear três lugares ou eventos onde o pin trading é uma atividade popular.',
    '7. Explicar os seguintes princípios da etiqueta do pin trading:',
    'a) Diversão;',
    'b) Justiça;',
    'c) Amizade.',
    '8. Trocar pins com, pelo menos, cinco pessoas que você não conheça em um lugar ou evento, usando os princípios de etiqueta diversão, justiça e amizade. Compartilhar com sua unidade, classe ou conselheiro/líder uma história interessante ou sobre alguém que você conheceu enquanto trocava pins.']);
  PERFORM pg_temp.set_req('AR-019', '2', ARRAY[
    'Nota: necessário o acompanhamento de um instrutor qualificado.',
    '1. Conhecer e explicar as regras de navegação para veleiros.',
    '2. Saber como as condições meteorológicas e as condições marítimas afetam o desempenho do barco à vela e a segurança da embarcação.',
    '3. Que medidas de segurança devem ser tomadas ao velejar?',
    '4. Fazer o seguinte:',
    'a) Afastar o barco à vela do ancoradouro ou praia;',
    'b) Saber como ajustar as velas de acordo com as seguintes situações:',
    '• Contra o vento;',
    '• Toda-vela;',
    '• Curva aberta;',
    '• Curva fechada;',
    '• A favor do vento.',
    'c) Mudar de rumo usando as velas;',
    'd) Aproximar-se da doca, praia ou ancoradouro, parar o barco e preparar o barco para ser guardado.',
    '5. Saber fazer os seguintes nós e como utilizá-los ao velejar:',
    'a) Nó direito;',
    'b) Lais de guia;',
    'c) Volta do fiel;',
    'd) Figura em oito;',
    'e) Laçada dupla.',
    '6. Relacionar as maneiras para cuidar e preservar seu equipamento de navegação durante o ano.',
    '7. Conhecer, pelo menos, 20 termos utilizados na navegação e seus significados.',
    '8. Ser capaz de identificar, pelo menos, 15 partes de um veleiro.',
    '9. Explicar:',
    'a) Como deve ser feito o resgate de uma pessoa que tenha caído na água?',
    'b) O que fazer quando um veleiro vira?']);
  PERFORM pg_temp.set_req('AR-086', '1', ARRAY[
    '1. Listar todos os tipos de transporte que você possa pensar que as pessoas usam ao redor do mundo. Diminuir esta lista anterior para os cinco meios de transporte mais comuns. Listar os prós e os contras de cada um dos cinco.',
    '2. Liste alguns dos prós e contras dos seguintes tipos de hospedagem:',
    'a) Hotel;',
    'b) Albergue da Juventude;',
    'c) Amigos/família;',
    'd) Trailer/acampamentos;',
    'e) Resorts.',
    '3. Quais documentos são necessários para os seguintes tipos de viagens? Em quais casos é necessária uma autorização dos pais?',
    'a) Viagens intermunicipais;',
    'b) Viagens interestaduais;',
    'c) Viagens internacionais (para países que pertencem e não pertencem ao mesmo bloco econômico).',
    '4. Cumprir um dos seguintes:',
    'a) Assistir a um programa diário de viagem, ou uma reportagem ou vídeo promocional, que mostra paisagens de viagens e geografia de uma única localização;',
    'b) Pesquisar, através de atlas, livros ou internet, uma cidade ou região que você gostaria de visitar.',
    'Depois, sobre a alternativa escolhida, descobrir o seguinte:',
    '• População;',
    '• Clima;',
    '• Vegetação/geografia;',
    '• Comidas típicas;',
    '• Cultura.',
    '5. O que é necessário para viajar ao exterior? Discuta em grupo como um turista deve comportar-se quando estiver em outro país.',
    '6. Quais são as regras sobre o que se pode levar na mala despachada e na bagagem de mão? Por que é importante respeitar as leis a respeito de levar elementos de origem animal e vegetal de um país a outro?',
    '7. Criar um plano simples de viagem para 7 dias de férias familiares, ou para duas viagens de 4 dias cada. Como parte de seu planejamento, incluir os seguintes locais para visita:',
    'a) Detalhes sobre um lugar histórico;',
    'b) Detalhes sobre dois parques naturais;',
    'c) Detalhes sobre uma área de recreação.',
    'Observação: O primeiro e o último dia devem ser dias de viagem.',
    '8. Listar algumas maneiras diferentes que as pessoas usavam para viajar no tempo bíblico.']);
  PERFORM pg_temp.set_req('AR-087', NULL, ARRAY[
    '1. Ter a especialidade de Viagem e turismo.',
    '2. Que considerações de segurança você deve pensar quando viaja?',
    '3. Quais recomendações ou requerimentos de saúde são recomendados e/ou exigidos pelo departamento de saúde de seu país para viagens internacionais?',
    '4. Criar um orçamento para férias familiares, incluindo projeções de valores para o grupo e para você:',
    'a) Passagens de ida e volta;',
    'b) Despesas com transportes;',
    'c) Despesas com hospedagem;',
    'd) Despesas com alimentação;',
    'e) Custo orçado para visitar locais planejados;',
    'f) Gastos com lembrancinhas;',
    'g) Incluir 10% para despesas diversas.']);
  PERFORM pg_temp.set_req('AR-024', '2', ARRAY[
    '1. Participar de, pelo menos, dois acampamentos, com no mínimo dois pernoites cada, durante os quais possa praticar as habilidades necessárias para esta especialidade.',
    '2. Mencionar oito coisas que devem ser feitas quando se está perdido numa floresta/mata. Conhecer três métodos de identificar os pontos cardeais sem o uso de uma bússola.',
    '3. Explicar como encontrar água na floresta/mata e demonstrar três maneiras de purificar água para beber.',
    '4. Explicar os primeiros socorros que devem ser prestados nas seguintes situações:',
    'a) Hipotermia;',
    'b) Mordida de cobra peçonhenta;',
    'c) Insolação;',
    'd) Exaustão;',
    'e) Ferimentos;',
    'f) Náuseas;',
    'g) Desidratação.',
    '5. Demonstrar, na prática, pelo menos dois dos itens abaixo:',
    'a) Avaliar a altura de uma árvore;',
    'b) Avaliar a largura de um riacho;',
    'c) Avaliar a profundidade de um rio.',
    '6. Demonstrar duas formas de sinalizar pedidos de socorro.',
    '7. Usando uma bússola, seguir um percurso (previamente montado pelo instrutor) com no mínimo três azimutes de mais de 300 metros, com margem de erro de, no máximo, 5% da distância do percurso (por exemplo: para um percurso de 300 metros, margem de erro de 15 metros).',
    '8. Identificar, preparar e comer três variedades de plantas silvestres.',
    '9. Explicar como preparar-se e providenciar abrigo nas seguintes condições:',
    'a) Muita neve;',
    'b) Área rochosa;',
    'c) Pântano;',
    'd) Floresta.',
    '10. Ter um estojo pessoal de sobrevivência com pelo menos 10 itens e saber usar cada um deles.']);
  PERFORM pg_temp.set_req('AR-108', '1', ARRAY[
    '1. Conhecer o regulamento atualizado da FIVB (Federação Internacional de Vôlei) e relacionar as oito regras principais do vôlei.',
    '2. O que significa a expressão fair play?',
    '3. Definir os seguintes termos:',
    'a) Ace;',
    'b) Antena;',
    'c) Aquecimento;',
    'd) Barreira;',
    'e) Bloqueio;',
    'f) Bola de graça;',
    'g) Bola dentro;',
    'h) Bola fora;',
    'i) Bola presa;',
    'j) Dois toques;',
    'k) Golpe de ataque;',
    'l) Jornada nas estrelas;',
    'm) Levantador;',
    'n) Líbero;',
    'o) Manchete;',
    'p) Match point;',
    'q) Peixinho;',
    'r) Quatro toques;',
    's) Rally;',
    't) Rede;',
    'u) Rodízio;',
    'v) Saque;',
    'w) Saque viagem;',
    'x) Set;',
    'y) Set point;',
    'z) Tempo técnico;',
    'aa) Toque apoiado.',
    '4. Demonstrar e compreender as diferentes habilidades exigidas em cada posição do vôlei.',
    '5. Demonstrar habilidade razoável nas seguintes áreas:',
    'a) Empunhadura;',
    'b) Saque;',
    'c) Passe;',
    'd) Levantamento;',
    'e) Ataque;',
    'f) Bloqueio.',
    '6. Passar pelo menos quatro horas ajudando uma pessoa menos habilidosa ou mais jovem a melhorar suas habilidades no vôlei.',
    '7. Jogar ao menos cinco partidas de vôlei com a família ou amigos. Mostrar fair play durante seus treinos e jogos.',
    '8. Desenhar, em escala, uma quadra de vôlei com seus limites adequadamente definidos. Informar as dimensões da rede de vôlei e respectiva altura de instalação.']);
  PERFORM pg_temp.set_req('AR-109', NULL, ARRAY[
    'Nota: Necessário o acompanhamento de um instrutor qualificado.',
    '1. Qual a diferença entre skate e waveboarding?',
    '2. Explicar por que o waveboarding é considerado a junção de três esportes radicais. Que esportes são esses?',
    '3. Explicar sobre os seguintes equipamentos de segurança:',
    'a) Capacete;',
    'b) Joelheira;',
    'c) Caneleira;',
    'd) Luvas.',
    '4. Desmontar e remontar corretamente seu waveboard, identificando e nomeando cada parte.',
    '5. Relacionar os tipos de rodas que existem, explicando a diferença entre elas e onde cada uso é mais indicado.',
    '6. Fazer, pelo menos, 15 das seguintes manobras, sendo que 5 delas deverão ser em rampa:',
    'a) Ollie;',
    'b) Wheelie (manual) por 10 metros;',
    'c) Nose Wheelie (nose manual) por 10 metros;',
    'd) C Turn;',
    'e) 180 graus;',
    'f) 180º varial corpo;',
    'g) 360 Spin;',
    'h) Grab Rail;',
    'i) Leap Board;',
    'j) Vire downhill;',
    'k) Kickflip;',
    'l) Impossible Duplo;',
    'm) No Comply Kickflip;',
    'n) Kickflip Fakie;',
    'o) Kickflip Switch;',
    'p) Fakie Bigspin;',
    'q) Nollie Kickflip;',
    'r) Nollie Helpflip;',
    's) Nollie Frontside 180 bigspin;',
    't) Varial Kickflip;',
    'u) Helpflip Varial;',
    'v) Backside Kickflip 180;',
    'w) Frontside Helpflip 180;',
    'x) Frontside Kickflip 180;',
    'y) 360 e Kickflip;',
    'z) Frontside duplo.']);
  PERFORM pg_temp.set_req('CS-009', '1', ARRAY[
    '1. Explicar o que deve ser feito para evitar ferimentos e/ou morte em cinco das situações a seguir:',
    'a) Incêndio em sua casa, na casa de um vizinho ou em um prédio público;',
    'b) Se estiver perdido, de carro, num lugar ermo ou deserto;',
    'c) Acidente automobilístico;',
    'd) Terremoto;',
    'e) Enchente;',
    'f) Ciclone;',
    'g) Furacão;',
    'h) Tempestade;',
    'i) Acidente nuclear;',
    'j) Desmoronamento;',
    'k) Se barco ou canoa virar enquanto se navega.',
    '2. Ao telefonar pedindo ajuda numa emergência, que informações essenciais devem ser dadas e quem deve desligar o telefone por último? Quais são os principais números de emergência em seu país?',
    '3. Demonstrar que medidas de primeiros socorros você deveria tomar numa emergência nas seguintes circunstâncias:',
    'a) A roupa de alguém pega fogo;',
    'b) Alguém está engasgado;',
    'c) Alguém engoliu veneno.',
    '4. Fazer o seguinte:',
    'a) Desenhar uma rota de escape para sua família em caso de incêndio em sua casa, para o caso de as saídas normais estarem bloqueadas;',
    'b) Fazer com a sua família ou unidade um treinamento para o caso de incêndio;',
    'c) Discutir com o seu instrutor os procedimentos para retirar pessoas da igreja e/ou escola em caso de incêndio. (Obs.: deve-se analisar alternativas para prevenir o pânico).',
    '5. O que você e seus pais devem fazer para prevenir o sequestro de crianças em sua família? O que você deveria fazer se fosse sequestrado?']);
  PERFORM pg_temp.set_req('CS-036', '2', ARRAY[
    '1. O que é anatomia humana?',
    '2. Como se iniciou o estudo da anatomia humana? Quais são as técnicas usadas atualmente para o estudo de anatomia?',
    '3. O que é, como é e qual é a importância da posição anatômica? Ilustrar.',
    '4. Quais os componentes básicos e as principais funções de cada um dos sistemas abaixo? Apresentar imagens que ilustrem cada um deles.',
    'a) Sistema circulatório;',
    'b) Sistema respiratório;',
    'c) Sistema digestório;',
    'd) Sistema esquelético.',
    '5. O que são variações anatômicas?',
    '6. Fazer um glossário com os seguintes termos anatômicos:',
    'a) Superficial e profundo;',
    'b) Medial e lateral;',
    'c) Posterior e anterior;',
    'd) Caudal e cranial;',
    'e) Distal e proximal;',
    'f) Médio;',
    'g) Dorso;',
    'h) Abdome;',
    'i) Flexão e extensão;',
    'j) Abdução e adução;',
    'k) Oposição;',
    'l) Rotação;',
    'm) Circundução.',
    '7. O que a Bíblia fala sobre o cuidado com o corpo? 1 Coríntios 6:19-20.']);
  PERFORM pg_temp.set_req('CS-021', NULL, ARRAY[
    '1. Definir os seguintes termos:',
    'a) Carboidrato;',
    'b) Lipídio;',
    'c) Ácido graxo;',
    'd) Proteína;',
    'e) Peptídeo;',
    'f) Enzima;',
    'g) Aminoácido;',
    'h) Ácido nucleico;',
    'i) Hidrofílico e hidrofóbico;',
    'j) Triglicerídeo.',
    '2. Qual a importância da água para o organismo? Quais as principais características físicas e químicas da molécula da água?',
    '3. O que significa metabolismo?',
    '4. Bioquimicamente, por que sentimos fome?',
    '5. Explicar como ocorre a via da glicólise. Qual a sua importância para o metabolismo?',
    '6. Quais células humanas são dependentes apenas da glicólise para obter energia?',
    '7. Qual molécula une a via da glicólise e o ciclo do ácido cítrico (ciclo de Krebs)?',
    '8. Qual a importância do ciclo do ácido cítrico (ciclo de Krebs)?',
    '9. Quais as funções dos lipídeos?',
    '10. Por que os lipídios são insolúveis em água?',
    '11. Por que os lipídeos, e não a glicose, são utilizados para o armazenamento de energia?',
    '12. O que é a beta-oxidação? Por que essa via recebe esse nome?',
    '13. O que são aminoácidos essenciais e não essenciais?',
    '14. O que são os corpos cetônicos, onde são produzidos e quais as consequências do excesso de sua produção?',
    '15. Que compostos são formados pela união dos aminoácidos? Quais as principais funções desses compostos?',
    '16. Qual a importância dos ácidos nucleicos? Como é sua estrutura e quais são seus componentes?',
    '17. A partir de uma imagem (desenho) de uma molécula de DNA, identificar seus quatro nucleotídeos e dizer como se dão as ligações entre eles.']);
  PERFORM pg_temp.set_req('CS-035', NULL, ARRAY[
    '1. Definir os seguintes termos:',
    'a) Aerossóis;',
    'b) Agente de risco;',
    'c) Biossegurança;',
    'd) Material biológico;',
    'e) Acidente químico ou biológico;',
    'f) Incidente químico ou biológico;',
    'g) Patogênico.',
    '2. O que são EPIs (Equipamentos de Proteção Individual)? Para que eles servem? Quais são os EPIs que os profissionais de saúde costumam usar?',
    '3. Diferenciar surto, epidemia, pandemia e endemia.',
    '4. Em meio a uma epidemia/pandemia, quais os principais cuidados que devem ser tomados?',
    '5. Qual a diferença entre isolamento e quarentena?',
    '6. Escolher duas doenças da lista abaixo e responder: quando aconteceu? quantos foram infectados? qual era a maneira de contágio? quais eram os sintomas? encontraram cura? quais foram os cuidados de biossegurança?',
    'a) Peste negra;',
    'b) Varíola;',
    'c) Gripe espanhola;',
    'd) Tifo;',
    'e) Gripe suína.',
    '7. Escolher uma das doenças abaixo e responder: quais são os sintomas? como é a forma de contágio? existe cura atualmente? onde e quando já houve surto/epidemia/pandemia? Existe prevenção dessa doença?',
    'a) Cólera;',
    'b) Tuberculose;',
    'c) Febre amarela;',
    'd) Sarampo;',
    'e) Malária;',
    'f) AIDS;',
    'g) Covid-19.',
    '8. Como as vacinas funcionam? Qual a importância de se estar com as vacinas em dia?',
    '9. Sobre a lavagem das mãos:',
    'a) Apresentar ao seu instrutor, pessoalmente, por vídeo ou por imagens, como deve ser feita a lavagem correta das mãos. Explicar por que é importante seguir cada passo;',
    'b) Por qual motivo não é recomendável usar toalhas que serão usadas várias vezes por várias pessoas, e sim toalhas de papel?',
    '10. Por que o adequado é usar álcool 70% e não outros tipos de álcool? Qual a forma correta de utilizá-lo?',
    '11. Que atitudes devem ser tomadas ao tossir e espirrar para evitar contaminar outras pessoas?',
    '12. De acordo com Mateus 24 e Apocalipse 6, o que a Bíblia fala sobre as doenças no fim dos tempos?',
    '13. De acordo com 1 Coríntios 15 e Apocalipse 21 e 22, o que acontecerá com os doentes e com as doenças quando formos para o céu?']);
  PERFORM pg_temp.set_req('CS-037', NULL, ARRAY[
    '1. Por que a verdadeira ciência não se opõe à Bíblia?',
    '2. Explicar sobre a relação dos cientistas abaixo com sua fé em Deus:',
    'a) Nicolau Copérnico;',
    'b) Johannes Kepler;',
    'c) Galileu Galilei;',
    'd) Isaac Newton;',
    'e) Robert Boyle;',
    'f) Michael Faraday;',
    'g) Gregor Mendel;',
    'h) Lord Kelvin (William Thompson);',
    'i) Max Planck;',
    'j) Albert Einstein;',
    'k) Louis Pasteur.',
    '3. Citar uma frase referente a Deus de cada cientista apresentado abaixo:',
    'a) Arthur Eddington;',
    'b) Allan Sandage;',
    'c) Charles Townes;',
    'd) Werner Von Braun;',
    'e) Max Planck;',
    'f) Antoine Henri Becquerel;',
    'g) Andrews Millikan;',
    'h) Erwin Schrödinger;',
    'i) Edward Mitchell;',
    'j) Louis Pasteur;',
    'k) Isaac Newton;',
    'l) Albert Einstein.']);
  PERFORM pg_temp.set_req('CS-020', NULL, ARRAY[
    '1. Quais são as estruturas que formam o sistema circulatório? Ilustrar e descrever as principais funções de cada uma.',
    '2. Descrever os tipos de vasos que compõem o sistema circulatório, ilustrando cada um deles.',
    '3. Saber localizar os seguintes pontos de pulso: carotídeo, braquial e radial. Saber aferir a frequência de pulso de uma pessoa, usando um dos pontos acima.',
    '4. Registrar seu pulso em repouso, em seguida fazer exercícios (correr, nadar, subir escadas, etc.) por 10 minutos. Aferir novamente o seu pulso imediatamente e cinco minutos após o exercício. O exercício afetou os batimentos do seu coração? Por que isso ocorre?',
    '5. Usar um estetoscópio para auscultar os batimentos cardíacos de uma criança menor de cinco anos de idade e de um adulto. Ambas as aferições devem durar exatos 60 segundos. Anotar os resultados e explicar o porquê da diferença na quantidade de batimentos cardíacos de uma criança em relação a um adulto.',
    '6. Quais são as quatro câmaras do coração? Quais são as suas quatro principais valvas?',
    '7. Qual é a diferença entre pequena circulação e grande circulação?',
    '8. Qual o nome dos vasos que irrigam o próprio coração? Qual o nome da principal artéria do corpo?',
    '9. Listar, pelo menos, cinco coisas que ajudam a manter o sistema cardiovascular saudável.',
    '10. O que é colesterol e como ele está relacionado à aterosclerose? Como a aterosclerose afeta o sistema cardiovascular?',
    '11. O que é um eletrocardiograma e para que serve?',
    '12. Explicar o que é o aparelho marcapasso cardíaco e dizer qual a sua função.',
    '13. O que é o sistema linfático? Quais as suas funções?',
    '14. Descrever as principais estruturas do sistema linfático.']);
  PERFORM pg_temp.set_req('CS-015', '2', ARRAY[
    '1. O que é digestão e onde ela se inicia?',
    '2. Onde é formada a saliva? Quais são as três principais funções dela?',
    '3. Qual é o papel do dente na digestão?',
    '4. Ser capaz de identificar, através de figuras, os seguintes órgãos que participam do processo digestivo, descrevendo cada um: boca, esôfago, estômago, fígado, pâncreas, intestino delgado, intestino grosso e ânus.',
    '5. Qual é a diferença entre bolo alimentar e quimo?',
    '6. O que é a bile? Onde é formada? Qual é a sua função e onde é liberada?',
    '7. O que são as microvilosidades intestinais? Por que elas fazem o alimento ser absorvido com maior velocidade?',
    '8. O que são fibras alimentares? Qual a importância delas para o processo digestivo? O que acontece se os alimentos permanecerem por mais tempo dentro do trato gastrointestinal?',
    '9. Demonstrar a digestão do amido em açúcar, utilizando o teste do iodo.',
    '10. Onde ocorre a digestão/absorção dos seguintes elementos: carboidratos, proteínas, lipídios, vitaminas, minerais e água?']);
  PERFORM pg_temp.set_req('CS-006', '2', ARRAY[
    '1. Quem é Florence Nightingale e qual a sua contribuição para a enfermagem?',
    '2. Entrevistar um enfermeiro ou um técnico/auxiliar de enfermagem e fazer as seguintes perguntas:',
    'a) Por que escolheu esta profissão?',
    'b) Que faculdade/curso é preciso fazer para trabalhar em sua profissão?',
    'c) Além da conclusão da faculdade/curso, que outros requisitos são necessários para exercer a sua profissão?',
    'd) Qual é o aspecto que você mais gosta em seu trabalho? O que menos gosta?',
    'e) Que dias da semana, e quantas horas diárias, você tem que trabalhar?',
    'f) Citar algumas instituições em sua cidade ou Estado que oferecem cursos na sua área.',
    '3. Quais são os sinais vitais? Quais são os valores de normalidade de cada sinal vital (para um adulto)?',
    '4. Praticar aferir o pulso, a respiração e a temperatura de um amigo do seu Clube.',
    '5. O que é febre? Conhecer os sinais e sintomas da febre. É necessário usar medicamentos sempre que se tem febre? Por quê?',
    '6. O que é uma doença contagiosa? Quais são as vias de transmissão? Que precauções devem ser seguidas para evitar a transmissão dessas doenças? Relacionar medidas de segurança a serem observadas ao cuidar de alguém que esteja com uma doença contagiosa.',
    '7. Saber quando e como lavar as mãos quando estiver cuidando de alguém doente.',
    '8. Qual a importância da mudança de decúbito para uma pessoa que está acamada? Como ela é feita e com que frequência deve ser feita?',
    '9. Demonstrar como se aplica uma compressa quente/fria. Quando é indicado usar compressas quentes? Quando é indicado usar compressas frias?']);
  PERFORM pg_temp.set_req('CS-038', '2', ARRAY[
    '1. Para que servem os experimentos científicos?',
    '2. Explicar a primeira lei de Newton utilizando um ovo de galinha não cozido.',
    '3. Com uma muda de feijão, uma caixa e luz solar, explicar sobre a fotossíntese.',
    '4. Explicar a oxidação de frutos utilizando uma banana. O que pode ser usado para impedir essa oxidação?',
    '5. Usando um copo transparente, água, açúcar e óleo de cozinha, explicar sobre misturas homogêneas e heterogêneas.',
    '6. Usando um pente de plástico, flanela de lã e papel picado, explicar sobre eletricidade estática.',
    '7. Mostrar que o ar é constituído de matéria, utilizando uma seringa descartável.',
    '8. Usando um barbante e duas laranjas, explicar sobre energia cinética.',
    '9. Explicar sobre a alteração de pressão fazendo o experimento do submarino de garrafa, usando uma garrafa PET transparente, tampa de caneta, tubo de caneta, água e massa de modelar.',
    '10. Explicar sobre óptica fazendo o experimento da câmara escura, usando uma lata ou caixa, prego e vela.',
    '11. Com um copo de vidro transparente e um canudo, explicar sobre a refração.',
    '12. Explicar sobre a força eletromagnética da Terra, usando uma agulha, ímã, cortiça, água e copo.',
    '13. Descobrir na Bíblia uma história sobre alguém fazendo um experimento. O que foi a única coisa que fez esse experimento dar certo?']);
  PERFORM pg_temp.set_req('CS-013', NULL, ARRAY[
    '1. O que é física?',
    '2. Qual é o objetivo principal da física?',
    '3. Quais são as principais áreas de estudo da física?',
    '4. Explicar a diferença entre a física clássica e a física moderna.',
    '5. Quais são as três leis de Newton?',
    '6. Aprender como calcular a velocidade média. Calcular a velocidade média de cada desbravador em um percurso e classificá-los do mais rápido ao mais lento.',
    '7. Demonstrar a experiência de Galileu — queda de um corpo — derrubando duas garrafas de plástico (uma cheia de água e a outra pela metade) ao mesmo tempo, de uma altura de 2 metros. Registrar os resultados e retirar uma aplicação espiritual da experiência.',
    '8. Demonstrar a vantagem mecânica da alavanca, retirando um prego grande, pregado bem fundo numa madeira, usando apenas um martelo. Puxar um segundo prego usando um martelo e um pequeno bloco de madeira, localizado perto do prego, sob a cabeça do martelo. Anotar a diferença de força exigida para puxar o prego com as diferentes posições do martelo no bloco (fulcro) e tirar uma aplicação espiritual desta experiência.',
    '9. O que é temperatura? Como ela está relacionada com a energia térmica de um objeto?',
    '10. Explicar o que é dilatação térmica e dar um exemplo prático de um objeto que sofre dilatação quando aquecido.',
    '11. Qual é a principal diferença entre campo elétrico e campo magnético?',
    '12. Qual é a diferença fundamental entre resistores e capacitores em um circuito elétrico?',
    '13. O que é a Teoria da Relatividade de Albert Einstein e qual foi a sua contribuição para a física moderna?',
    '14. O que é o efeito fotoelétrico e qual sua importância na física moderna?']);
  PERFORM pg_temp.set_req('CS-031', '1', ARRAY[
    '1. O que é o sistema decimal e por que ele é importante na matemática?',
    '2. Identificar e classificar os algarismos do sistema decimal (0 a 9) e explicar a importância da posição de cada um.',
    '3. Explicar e exemplificar o algoritmo para as quatro operações básicas: adição, subtração, multiplicação e divisão.',
    '4. Elaborar quatro situações práticas onde você usaria as quatro operações básicas para resolver problemas do dia a dia.',
    '5. Pesquisar e apresentar a origem histórica dos símbolos matemáticos para raiz quadrada, divisão, adição e subtração em forma de desenhos ou escrita.',
    '6. Demonstrar, por meio de exemplos práticos, a resolução de três problemas de potenciação e três exemplos de expressões numéricas utilizando parênteses, colchetes e chaves.',
    '7. Apresentar e resolver três situações práticas envolvendo frações nas operações de adição, subtração, multiplicação e divisão, utilizando o cálculo do mínimo múltiplo comum (MMC) para adição e subtração.',
    '8. Apresentar e demonstrar a resolução de três problemas que envolvam cálculos de porcentagem, como descontos em compras e vendas de produtos.',
    '9. Apresentar e demonstrar a resolução de quatro exemplos de operações com números decimais, incluindo adição, subtração, multiplicação e divisão, utilizando métodos práticos de resolução.']);
  PERFORM pg_temp.set_req('CS-032', NULL, ARRAY[
    '1. Ter a especialidade de Habilidades em matemática I.',
    '2. Quais são as características de um polígono regular? Citar exemplos.',
    '3. Fazer o desenho dos seguintes polígonos regulares: quadrado, retângulo, pentágono, hexágono, heptágono e octógono.',
    '4. Qual é a diferença entre os triângulos equilátero, isósceles e escaleno?',
    '5. Qual é a diferença entre perímetro e área?',
    '6. Calcular o perímetro e a área de quatro polígonos regulares do requisito 2.',
    '7. O que são sólidos geométricos? Citar exemplos.',
    '8. Pegar um copo cilíndrico, fazer as medições do raio e de altura e calcular o seu volume em ml.',
    '9. O que é o Sistema Internacional de Unidades (SI)?',
    '10. Qual é a principal diferença na medição entre polígonos regulares e sólidos geométricos?',
    '11. Sobre a arca de Noé a Bíblia diz: “Deste modo a farás: de trezentos côvados será o comprimento; de cinquenta, a largura; e a altura de trinta” Gênesis 6:15. Sabendo que um côvado é igual a 0,66 m e sugerindo que a arca foi um paralelepípedo, qual é o volume da arca?']);
  PERFORM pg_temp.set_req('CS-019', '3', ARRAY[
    '1. O que é hereditariedade?',
    '2. Desenhar uma célula animal e identificar as seguintes partes: membrana plasmática, citoplasma, núcleo, carioteca e ribossomos.',
    '3. Explicar o seguinte:',
    'a) O que é um cromossomo e onde está localizado?',
    'b) O que é gene e onde ele é encontrado?',
    '4. Explicar o seguinte:',
    'a) O que é alelo?',
    'b) Qual a diferença entre alelo dominante e alelo recessivo?',
    'c) Determinar que tipo de alelo se tem nos seguintes traços genéticos (fenótipos): bico de viúva, lóbulo da orelha solto, covinhas, língua enrolada, miopia, ser canhoto e furo no queixo;',
    'd) Usando o quadrado de Punnet, prever a proporção dos seguintes cruzamentos: TT (alto) com tt (baixo); Tt (alto) com Tt (alto); Tt (alto) com tt (baixo).',
    '5. Explicar o seguinte:',
    'a) O que é mitose? Qual a sua função?',
    'b) Desenhar uma sequência de células mostrando o processo de mitose, incluindo: prófase, metáfase, anáfase e telófase;',
    'c) Explicar como o DNA é copiado no cromossomo durante este processo.',
    '6. Explicar o seguinte:',
    'a) O que é meiose? Qual a diferença entre mitose e meiose?',
    'b) Desenhar uma sequência de células mostrando o processo da meiose, incluindo: interfase, prófase I, metáfase I, anáfase I, telófase I, prófase II, metáfase II, anáfase II e telófase II;',
    'c) As células resultantes da meiose permanecem diploides? Explicar.',
    '7. Quais são os nucleotídeos envolvidos no processo de replicação do DNA? Descrever como ocorre a replicação de um DNA. Demonstrar seu conhecimento sobre esse assunto usando um diagrama ou modelo.',
    '8. O que é mutação? Usando o diagrama ou modelo criado na questão anterior, ilustrar o efeito de uma mutação no código genético.',
    '9. Descrever, pelo menos, três doenças genéticas e quais são as suas manifestações.',
    '10. A genética é o único fator que contribui para as suas características (físicas, mentais, sociais e espirituais)? Que outros fatores influenciam a sua vida e a sua personalidade?',
    '11. Encontrar três citações da Bíblia ou do Espírito de Profecia que se relacionem com a sua resposta da questão anterior.']);
  PERFORM pg_temp.set_req('CS-023', NULL, ARRAY[
    '1. Definir higiene oral.',
    '2. Por quantas dentições um ser humano passa?',
    '3. Para que servem os dentes de leite?',
    '4. Quais são os tipos de dentes? Descrever as funções de cada tipo.',
    '5. A partir de quando se deve iniciar a higiene oral? Como? Por quê?',
    '6. Que prejuízos a má escovação ou a falta de escovação podem trazer?',
    '7. Quais os meios de utilização do flúor? Em que formas ele é encontrado?',
    '8. O que é evidenciador?',
    '9. O que deve ser usado para fazer uma higiene oral completa?',
    '10. Demonstrar ao seu instrutor a forma correta de:',
    'a) Fazer a escovação;',
    'b) Usar fio dental.',
    '11. Por que devemos usar dentifrício fluoretado?',
    '12. Como se contrai a cárie?']);
  PERFORM pg_temp.set_req('CS-024', NULL, ARRAY[
    '1. Ter a especialidade de Higiene oral.',
    '2. Saber identificar as seguintes partes do dente, descrevendo a função de cada uma: esmalte, dentina, polpa, gengiva, cemento e ligamento periodontal.',
    '3. Descrever os seguintes problemas bucais:',
    'a) Placa;',
    'b) Tártaro;',
    'c) Gengivite;',
    'd) Periodontite.',
    '4. O que é pasta profilática?',
    '5. Descrever como realizar a fluoretação, explicando cada um dos passos a serem seguidos.',
    '6. O que fazer quando há um trauma em um dente por ocasião de uma queda?',
    '7. O que causa sensibilidade nos dentes? Como este problema pode ser resolvido?',
    '8. Quais os cuidados adicionais na higiene bucal uma pessoa que usa aparelho ortodôntico deve ter?',
    '9. Quais os cuidados adicionais na higiene bucal uma pessoa que usa prótese dentária deve ter?',
    '10. Criar uma estória que ilustre as formas de prevenir a cárie dentária e apresentá-la, de forma criativa, a um grupo de crianças.']);
  PERFORM pg_temp.set_req('CS-025', '2', ARRAY[
    '1. Descrever como os seguintes itens contribuem para o estudo:',
    'a) Escolha do lugar e ambiente ideal;',
    'b) Dicionário;',
    'c) Domínio do tempo de estudo;',
    'd) Pesquisa bibliográfica como complemento do estudo;',
    'e) Técnicas de assimilação e memorização;',
    'f) Uso da internet.',
    '2. Fazer uma ficha com o seu cronograma diário, incluindo nela o tempo de estudo. Segui-la durante duas semanas. Preencher a ficha com o tempo a ser gasto nas seguintes atividades:',
    'a) Sono;',
    'b) Escola;',
    'c) Transporte;',
    'd) Alimentação;',
    'e) Estudo;',
    'f) Lazer, atividades sociais e esportes;',
    'g) Outros.',
    '3. Descrever maneiras que ajudam o estudante a se concentrar durante os estudos:',
    'a) Em casa;',
    'b) Na biblioteca;',
    'c) Na escola.',
    '4. Demonstrar qual a melhor postura para se estudar e listar quais posições o estudante deve evitar ao estudar.',
    '5. Apresentar cinco dicas para o estudante que quer tirar boas notas em avaliações e trabalhos.',
    '6. Que atividades ajudam o estudante a melhorar sua capacidade de aprendizado?',
    '7. Escrever uma redação de 25 a 30 linhas com um dos seguintes temas:',
    'a) Onde vou estar e o que farei daqui a cinco anos?',
    'b) Qual carreira gostaria de seguir? Por quê?',
    'c) Como farei para seguir a profissão que escolhi?',
    'd) O que ainda quero aprender e como posso alcançar esse objetivo?',
    '8. Saber a diferença entre resumo e resenha, apresentando ambas em forma de esboço.',
    '9. Ler algum livro de sua escolha que trate sobre técnicas e metodologias de estudo e apresentar um esboço de, no mínimo, 30 linhas.']);
  PERFORM pg_temp.set_req('CS-014', NULL, ARRAY[
    '1. Conhecer os microscópios abaixo, identificando-os pessoalmente ou através de figuras e/ou fotos. Informar as principais características de cada um.',
    'a) Microscópio óptico;',
    'b) Microscópio eletrônico de varredura;',
    'c) Microscópio eletrônico de transmissão;',
    'd) Microscópio de força atômica.',
    '2. Ser capaz de identificar as seguintes partes de um microscópio e explicar e demonstrar a função de cada uma: ocular, objetiva, canhão, platina, condensador, base, foco (parafuso micrométrico e parafuso macrométrico) e braço.',
    '3. Saber como calcular a ampliação em um microscópio óptico composto. Calcular a ampliação do microscópio que você está usando para esta especialidade.',
    '4. Definir os seguintes termos:',
    'a) Lâmina;',
    'b) Lamínula;',
    'c) Exame direto a fresco (ou exame direto ou exame fresco);',
    'd) Fixador;',
    'e) Corantes;',
    'f) Óleo de imersão.',
    '5. Coletar amostras de água (de lagoas, riachos, rios, lagos, poças), prepará-las corretamente e procurar micro-organismos usando um microscópio com, pelo menos, 100x de ampliação. Desenhar, ao menos, dois desses organismos. No desenho, rotular as estruturas identificadas (incluindo a ampliação usada).',
    '6. Citar, pelo menos, um exemplo de como a microscopia é importante para:',
    'a) A alimentação humana;',
    'b) A saúde humana;',
    'c) Os medicamentos;',
    'd) Outros organismos.',
    '7. Citar um hábito de saúde que foi estabelecido após a invenção dos microscópios.']);
  PERFORM pg_temp.set_req('CS-008', NULL, ARRAY[
    '1. O que são nutrientes?',
    '2. O que são e quais são os macronutrientes? Quais as principais funções de cada um? Citar exemplos de alimentos em cada grupo.',
    '3. O que são micronutrientes?',
    '4. Qual a função das seguintes vitaminas? Fazer uma lista de, pelo menos, três alimentos fonte dos seguintes nutrientes:',
    'a) Vitamina A;',
    'b) Vitamina B12;',
    'c) Vitamina C;',
    'd) Vitamina D;',
    'e) Vitamina E;',
    'f) Vitamina K.',
    '5. Qual a função dos seguintes minerais no nosso organismo? Fazer uma lista de, pelo menos, três alimentos fonte de cada um:',
    'a) Ferro;',
    'b) Iodo;',
    'c) Cálcio;',
    'd) Sódio;',
    'e) Potássio;',
    'f) Zinco.',
    '6. Desenhar e descrever a pirâmide alimentar. Mencionar o número de porções diárias recomendadas de cada grupo.',
    '7. O que são Valores Diários de Referência (VDR) e qual a sua importância?',
    '8. O que é uma dieta balanceada?',
    '9. Explicar as diferenças entre as seguintes dietas:',
    'a) Ovolactovegetariana;',
    'b) Ovo-vegetariana;',
    'c) Vegetariana estrita.',
    '10. Comparar as informações nutricionais dos seguintes alimentos:',
    'a) Leite integral e leite desnatado;',
    'b) Farinha de trigo branca e farinha de trigo integral;',
    'c) Pão integral e pão branco;',
    'd) Arroz integral e arroz branco.',
    '11. Qual a diferença entre alimentos diet e alimentos light?',
    '12. Por que é importante beber bastante água diariamente? Qual a quantidade recomendada para cada dia?',
    '13. Citar o nome de três doenças comuns que podem ser controladas/evitadas com uma dieta apropriada.',
    '14. Por que o governo de alguns países determina a inclusão de iodo, ferro, ácido fólico e flúor em alimentos básicos como farináceos, sal e água? Qual o impacto desta medida na saúde da população?',
    '15. Planejar e executar um cardápio para dois dias, contendo uma dieta ovolactovegetariana balanceada, utilizando as informações da pirâmide alimentar. Utilizar vegetais comuns em sua região e de acordo com a época do ano.',
    '16. Quais foram as vantagens que Daniel e seus amigos tiveram por escolherem uma alimentação saudável e vegetariana?']);
  PERFORM pg_temp.set_req('CS-010', '3', ARRAY[
    '1. Ter a especialidade de Nutrição.',
    '2. O que é dieta? Explicar os seguintes tipos e em quais casos são indicados:',
    'a) Hipossódica;',
    'b) Hipocalórica;',
    'c) Diabética;',
    'd) Cetogênica;',
    'e) Restrição de gorduras;',
    'f) Rica em fibras;',
    'g) Livre de glúten.',
    '3. Qual vitamina não faz parte da dieta vegetariana estrita? Quais as principais funções desta vitamina? O que um vegetariano estrito deve fazer para obter esta vitamina?',
    '4. Qual é a diferença entre gorduras saturadas, gorduras insaturadas e gorduras trans? Qual delas é mais saudável e por quê?',
    '5. Qual a diferença entre os colesteróis HDL e LDL? Quais alimentos são ricos em cada um deles?',
    '6. Definir ômega 3 e ômega 6 e explicar seus benefícios para a saúde.',
    '7. Fazer um quadro listando as frutas, verduras e legumes comuns em sua região e em quais meses do ano ocorre sua safra. Qual a importância de se dar preferência aos vegetais da estação?',
    '8. O que são nutrição enteral e nutrição parenteral? Quais os casos em que elas são indicadas?',
    '9. Realizar o seguinte:',
    'a) Manter um diário alimentar baseado em sua própria alimentação durante uma semana;',
    'b) Qual a porção diária recomendada dos seguintes nutrientes para a sua idade e sexo?',
    '• Calorias;',
    '• Carboidratos;',
    '• Proteínas;',
    '• Gorduras;',
    '• Sódio;',
    '• Fibra alimentar;',
    '• Ferro;',
    '• Cálcio.',
    'c) Com base no diário feito no item “a”, comparar a quantidade diária recomendada dos nutrientes acima com a quantidade que você ingere. O que precisa/deve ser mudado em sua dieta?',
    '10. As seguintes doenças são causadas por que tipo de deficiência nutricional?',
    'a) Raquitismo;',
    'b) Anemia hemolítica;',
    'c) Anemia megaloblástica;',
    'd) Anemia ferropriva;',
    'e) Bócio;',
    'f) Escorbuto;',
    'g) Marasmo;',
    'h) Kwashiorkor.',
    '11. Quais prejuízos à saúde os seguintes hábitos alimentares podem causar?',
    'a) Uso excessivo do sal;',
    'b) Uso excessivo do açúcar;',
    'c) Dieta rica em gorduras;',
    'd) Uso excessivo de condimentos;',
    'e) Uso de alimentos ultraprocessados;',
    'f) Alimentos estimulantes, como: chá preto/verde, chá mate, erva mate, café, xarope de guaraná/guaraná em pó;',
    'g) Refrigerantes e sucos artificiais;',
    'h) Comer no intervalo das refeições;',
    'i) Comer em grandes quantidades;',
    'j) Dietas restritivas (por exemplo low carb).',
    '12. Estudar três das seguintes doenças e, sobre cada uma, explicar: como ocorre, sinais e sintomas, como preveni-las (quando for o caso) e quais as alterações necessárias na dieta de uma pessoa que as possui:',
    'a) Diabetes;',
    'b) Hipertensão arterial sistêmica (pressão alta);',
    'c) Osteoporose;',
    'd) Doença celíaca;',
    'e) Intolerância à lactose;',
    'f) Alergia à proteína do leite de vaca;',
    'g) Aterosclerose.',
    '13. O que são suplementos alimentares? Com a ajuda de um profissional, indicar os mais comuns e explicar em quais casos são realmente necessários. Mencionar quais os riscos de se utilizar cada um deles sem a devida orientação de um nutricionista ou médico.']);
  PERFORM pg_temp.set_req('CS-007', '2', ARRAY[
    '1. Definir e desenhar um gráfico dos seguintes sistemas ópticos:',
    'a) Centro óptico;',
    'b) Foco;',
    'c) Distância focal;',
    'd) Ponto antiprincipal;',
    'e) Lente convergente (positiva);',
    'f) Lente divergente (negativa);',
    'g) Lentes esféricas;',
    'h) Aberração cromática;',
    'i) Refração da luz;',
    'j) Reflexão da luz;',
    'k) Reflexão total.',
    '2. Explicar como a luz se comporta quando atinge ou atravessa água, óleo, metais e um espelho.',
    '3. Mencionar o nome e fazer diagramas de três tipos de lentes convergentes e três tipos de lentes divergentes.',
    '4. Fazer a construção geométrica das imagens em lentes convergentes, informando a natureza da imagem, sua localização, tamanho, orientação e dar exemplos:',
    'a) Objeto antes do ponto antiprincipal objeto (Ao);',
    'b) Objeto sobre o ponto antiprincipal objeto (Ao);',
    'c) Objeto entre o ponto antiprincipal objeto e o foco objeto (Ao e fo);',
    'd) Objeto sobre o foco objeto (fo);',
    'e) Objeto entre o foco objeto e o centro óptico (fo e O).',
    '5. Fazer a construção geométrica das imagens em lentes divergentes:',
    'a) Objeto sobre o ponto antiprincipal objeto (Ao);',
    'b) Objeto entre o ponto antiprincipal objeto e o foco objeto (Ao e fo);',
    'c) Objeto sobre o foco objeto (fo);',
    'd) Objeto entre o foco objeto e o centro óptico (fo e O).',
    '6. Demonstrar, através de gráficos, como funciona um prisma. Marcar os ângulos em que as cores aparecem e desaparecem.',
    '7. Demonstrar o que acontece quando a luz atravessa um vidro translúcido.',
    '8. Com uma lente convergente e os raios solares, acender uma fogueira e explicar por que isso acontece. Explicar também por que não é possível acender uma fogueira com uma lente divergente.',
    '9. Construir um instrumento óptico usando espelhos ou lentes, tais como um periscópio, um projetor de slides ou um telescópio simples.',
    '10. Explicar o que significa o termo 6x35 e 7x50 aplicado a binóculos.',
    '11. Definir o termo “número-f” usado em conexão com câmeras fotográficas.']);
  PERFORM pg_temp.set_req('CS-016', NULL, ARRAY[
    '1. Qual a diferença entre endoesqueleto e exoesqueleto? Qual desses tipos de esqueleto os humanos têm?',
    '2. Citar, pelo menos, três funções do sistema musculoesquelético.',
    '3. Definir:',
    'a) Esqueleto axial;',
    'b) Esqueleto apendicular.',
    '4. Descrever a classificação dos ossos de acordo com o seu formato, ilustrando-os.',
    '5. Quantos ossos um ser humano adulto tem?',
    '6. Desenhar ou colar uma figura de esqueleto humano, identificando, no mínimo, 10 ossos, sem repeti-los.',
    '7. Definir diáfise, metáfise e epífise, ilustrando-os.',
    '8. O que é disco epifisário e qual a sua importância?',
    '9. O que são articulações? Descrever os três tipos com as suas subdivisões, ilustrando todas.',
    '10. Fazer um modelo de uma das seis articulações sinoviais.',
    '11. O que é fratura óssea? Como é feita a correção médica?',
    '12. Ilustrar, com desenho ou gravuras, a coluna vertebral, dividindo-a em suas cinco regiões. Quantas vértebras formam cada região?',
    '13. O que é osteoporose? Quais os locais mais comuns de fratura? Qual é a idade de risco? Quem é o público mais afetado? Qual o melhor exame para detectá-la? Citar alguns cuidados que ajudam a prevenir a osteoporose.',
    '14. Quais são as principais funções dos músculos esqueléticos?',
    '15. Identificar os seguintes músculos: trapézio, deltoide, peitoral maior, bíceps, quadríceps, tríceps, reto abdominal, serrátil anterior, glúteo máximo, grande dorsal, gastrocnêmio e sóleo.',
    '16. Descrever o mecanismo de contração muscular.']);
  PERFORM pg_temp.set_req('CS-027', '2', ARRAY[
    '1. Definir o conceito de patrimônio histórico.',
    '2. Citar a diferença entre história e memória.',
    '3. Qual a importância do patrimônio histórico para:',
    'a) A identidade dos povos?',
    'b) A preservação da memória?',
    'c) A constituição humana?',
    '4. Explicar como se forma um patrimônio histórico e quais são os benefícios de sua criação.',
    '5. Como a história pode influenciar as decisões de uma sociedade?',
    '6. Definir as categorias abaixo:',
    'a) Patrimônio histórico material;',
    'b) Patrimônio histórico imaterial.',
    '7. Qual o papel do ser humano como agente ativo na construção da história?',
    '8. Investigar três elementos de uma cultura imaterial em sua comunidade.',
    '9. Entrevistar uma pessoa com mais idade sobre suas memórias em relação à sua comunidade.',
    '10. Fazer um levantamento dos monumentos que existem na região que você mora. Descobrir a razão de eles estarem lá e qual a história que os monumentos pretendem preservar.',
    '11. Montar uma coleção de 10 elementos que tenham valor necessário para se tornarem históricos para você.']);
  PERFORM pg_temp.set_req('CS-039', NULL, ARRAY[
    '1. O que são plantas medicinais?',
    '2. Por que é importante identificar as plantas medicinais pelo seu nome científico e não pelo nome popular?',
    '3. O que é tratamento fitoterápico?',
    '4. Citar uma planta medicinal para cada parte a ser utilizada:',
    'a) Flor;',
    'b) Raiz;',
    'c) Caule;',
    'd) Folha;',
    'e) Fruto/semente.',
    '5. Falar sobre os benefícios para a saúde de cada planta abaixo:',
    'a) Allium sativum;',
    'b) Matricaria recutita;',
    'c) Annona muricata;',
    'd) Anacardium occidentale;',
    'e) Melissa officinalis;',
    'f) Cinnamomum zeylanicum;',
    'g) Schinus terebinthifolius;',
    'h) Bauhinia fortificata;',
    'i) Maytenus spp;',
    'j) Fragaria vesca;',
    'k) Phyllanthus spp;',
    'l) Punica granatum;',
    'm) Aloe vera.',
    '6. Citar três formas de preparo caseiro de chá medicinal e preparar um chá utilizando uma dessas formas.',
    '7. Qual rei na Bíblia teve a saúde restabelecida após ter usado uma pasta de figos?',
    '8. Qual a função das folhas da árvore da vida (Apocalipse 22:2)?']);
  PERFORM pg_temp.set_req('CS-026', NULL, ARRAY[
    '1. O que são doenças tropicais?',
    '2. Listar, pelo menos, cinco doenças tropicais comuns em sua região.',
    '3. Pesquisar e explicar as seguintes doenças, informando: transmissão, sinais e sintomas, tratamento, como preveni-las e combatê-las:',
    'a) Malária;',
    'b) Febre amarela;',
    'c) Leishmaniose;',
    'd) Dengue;',
    'e) Doença de Chagas.',
    '4. Explicar como eliminar os seguintes depósitos, evitando proliferação dos mosquitos:',
    'a) Pneus;',
    'b) Garrafas;',
    'c) Vasilhas de animais;',
    'd) Caixa d''água;',
    'e) Bromélias ou plantas que acumulam água;',
    'f) Pratinho de vasos de planta;',
    'g) Tonel ou dorna;',
    'h) Calhas;',
    'i) Tampinhas, latas e pequenas vasilhas descartáveis;',
    'j) Bandeja externa de geladeira.',
    '5. Completar duas das seguintes atividades:',
    'a) Participar, junto com o Clube, unidade ou escola, de uma campanha contra a dengue (ou outra doença tropical) em sua comunidade;',
    'b) Fazer uma coleta de recipientes que possam acumular água parada em praças e ruas da sua comunidade e eliminá-los corretamente;',
    'c) Adquirir ou confeccionar folhetos com informações sobre as principais doenças tropicais e distribuir em seu bairro ou escola;',
    'd) Eliminar corretamente o lixo de sua casa por uma semana;',
    'e) Ajudar uma pessoa do seu bairro a manter sua residência livre de depósitos que acumulem água, realizando as seguintes tarefas:',
    '• Orientar como manter a residência livre de possíveis focos de mosquitos;',
    '• Informar sobre cuidados e sintomas das doenças pesquisadas;',
    '• Fazer limpeza da residência, coletar e eliminar depósitos inservíveis.',
    '6. Com a ajuda do seu instrutor ou conselheiro, fazer uma apresentação, debate ou encenação para seu Clube ou unidade sobre as doenças tropicais estudadas nesta especialidade.']);
  PERFORM pg_temp.set_req('CS-003', NULL, ARRAY[
    '1. Definir primeiros socorros e descrever a sua finalidade.',
    '2. Saber como obter ajuda em uma emergência.',
    '3. Demonstrar a manobra adequada caso uma vítima esteja engasgada.',
    '4. Saber os primeiros socorros prestados a uma vítima de envenenamento/intoxicação.',
    '5. Saber quais situações podem levar a uma intoxicação por monóxido de carbono (CO). Descrever a forma de resgate e os primeiros socorros para este tipo de intoxicação.',
    '6. Quais os primeiros socorros prestados a uma pessoa que esteja com as roupas em chamas?',
    '7. Quais são os princípios básicos para a prevenção de incêndios em sua casa?',
    '8. Saber os primeiros socorros prestados a uma vítima com hemorragia externa.',
    '9. Saber os primeiros socorros prestados a vítimas de queimaduras de primeiro, segundo e terceiro graus. Através de desenhos ou modelos, demonstrar a porcentagem de área corporal das seguintes partes do corpo: cabeça, membros superiores, membros inferiores, dorso, tórax e abdome.',
    '10. Saber os primeiros socorros prestados a uma vítima de queimadura química.',
    '11. Saber os primeiros socorros prestados a uma vítima que foi picada por uma serpente. Saber qual o centro de saúde referência em acidentes ofídicos em sua região.',
    '12. Saber os primeiros socorros prestados a uma vítima que foi mordida por um animal. Definir o que é raiva e qual a classe de animais que pode transmitir a raiva.',
    '13. Saber os primeiros socorros prestados a uma vítima que foi picada por insetos ou aranhas.',
    '14. Saber os primeiros socorros prestados a vítimas com ferimentos internos.',
    '15. Quais os princípios básicos de segurança em rios, mares e piscinas?',
    '16. Quais as maneiras de salvar uma vítima de afogamento sem nadar?']);
  PERFORM pg_temp.set_req('CS-004', '2', ARRAY[
    '1. Ter a especialidade de Primeiros socorros - básico.',
    '2. O que são EPIs (equipamentos de proteção individual)? Qual a sua importância para os atendimentos de primeiros socorros?',
    '3. O que significa o protocolo ABCDE? Quando deve ser usado?',
    '4. Conhecer os primeiros socorros que devem ser prestados nas seguintes situações:',
    'a) Ferimentos na cabeça;',
    'b) Hemorragia interna;',
    'c) Ferimentos à bala;',
    'd) Ferimentos nos olhos;',
    'e) Desmaio e convulsão;',
    'f) Efeitos do calor ou frio extremos.',
    '5. Qual a diferença entre desidratação e insolação? Quais primeiros socorros devem ser prestados em cada situação?',
    '6. Saber como aplicar adequadamente as seguintes ataduras:',
    'a) Espiral;',
    'b) Cruzada ou em oito;',
    'c) Frontal, para a cabeça.',
    'Nota: Demonstrar habilidade aplicando as ataduras acima nas seguintes regiões do corpo: cabeça, antebraço, mão, joelho e tornozelo.',
    '7. Quais materiais podem ser usados como talas em situações de emergência? Saber como aplicar talas às seguintes partes do corpo:',
    'a) Braço;',
    'b) Antebraço;',
    'c) Joelho;',
    'd) Tornozelo.',
    '8. O que é torniquete? Por que seu uso pode ser tão prejudicial? Quando esta técnica poderá ou não ser usada?',
    '9. O que é choque? Quais são os principais tipos? Quais as principais causas? Quais primeiros socorros devem ser prestados a vítimas com choque hipovolêmico? E anafilático?',
    '10. Qual é a diferença entre infarto agudo do miocárdio (IAM) e acidente vascular encefálico (AVE)? Quais os primeiros socorros devem ser prestados em cada situação?',
    '11. Saber os primeiros socorros que devem ser prestados a uma vítima de acidente com eletricidade.',
    '12. Quais são os princípios básicos de segurança com eletricidade?',
    '13. Saber como escapar de um incêndio.']);
  PERFORM pg_temp.set_req('CS-005', NULL, ARRAY[
    '1. Ter a especialidade de Primeiros socorros - intermediário.',
    '2. Quais primeiros socorros devem ser prestados a vítimas de acidente de trânsito? Quais os cuidados com o local do acidente? Quais os cuidados com as vítimas?',
    '3. Ensinar a especialidade de Primeiros socorros - básico ou Primeiros socorros - intermediário a um grupo de desbravadores ou alunos.',
    '4. Montar um portfólio de materiais de primeiros socorros, para deixar na biblioteca do seu Clube.',
    '5. Quais são os aspectos éticos e legais, em seu país, envolvidos na prestação de primeiros socorros?',
    '6. Definir os seguintes termos:',
    'a) Omissão de socorro;',
    'b) Abandono;',
    'c) Negligência;',
    'd) Imperícia;',
    'e) Imprudência.']);
  PERFORM pg_temp.set_req('CS-002', NULL, ARRAY[
    '1. Definir os seguintes termos:',
    'a) Compostos;',
    'b) Soluções;',
    'c) Transformação química;',
    'd) Transformação física;',
    'e) Átomo;',
    'f) Próton;',
    'g) Nêutron;',
    'h) Elétron;',
    'i) Molécula;',
    'j) Ácido;',
    'k) Sal;',
    'l) Destilação;',
    'm) Destilação fracionária;',
    'n) Filtragem;',
    'o) Combustão;',
    'p) Dissolução fracionada;',
    'q) Indicadores ácido/base;',
    'r) Base;',
    's) Óxido.',
    '2. Responder as seguintes questões:',
    'a) O que são elementos químicos?',
    'b) O que é tabela periódica e qual a sua importância?',
    'c) Como os elementos químicos estão agrupados na tabela?',
    'd) O que é número atômico?',
    'e) De que forma os elementos são representados na tabela?',
    '3. Quais gases podem causar morte? Como?',
    '4. Mencionar duas fontes comuns de monóxido de carbono. Por que é uma substância perigosa?',
    '5. Quais os estados físicos da matéria?',
    '6. Explicar o fenômeno químico que está envolvido em cinco das alternativas a seguir:',
    'a) Tentar acender um cubo de açúcar, primeiro sem e depois com algumas cinzas aplicadas ao cubo, demonstrando a ação catalisadora;',
    'b) Colocar um cubo de gelo num copo com água, colocar um barbante de 10 centímetros em cima do gelo no copo, então solucionar o problema de tirar o cubo de gelo da água sem tocá-lo;',
    'c) Usando água, aguarrás e sabão, transferir uma foto de jornal para uma folha de papel em branco;',
    'd) Usando uma bacia de água, fósforos de madeira, um torrão de açúcar e um pouco de sabão, demonstrar a ação do açúcar e do sabão sobre fósforos que boiam na água;',
    'e) Colocar um ovo fresco em água doce e depois salgar a mesma, anotando a diferença;',
    'f) Fazer uma tinta invisível;',
    'g) Usando três pedaços de velas de tamanho diferentes e um recipiente de vidro, explicar correntes de convecção e densidade dos gases;',
    'h) Usando uma vela, um pedaço de papel e um anteparo de vidro, explicar a combustão incompleta através do composto formado. Quantos e quais fenômenos estão envolvidos quando uma vela está acesa?',
    'i) Demonstrar a capacidade térmica da água usando alguns dos seguintes materiais: uma vela, um balão ou bexiga, água, álcool 20%, acetona, papel, tripé de arame, papel pregueado;',
    'j) Usando raspas de magnésio, vela e indicador ácido/base, indicar o tipo de reação envolvida e demonstrar a acidez ou a basicidade do composto formado;',
    'k) Usando dois tubos de vidro, dois espetos de madeira, bicarbonato de sódio, vinagre, iodeto de potássio e água oxigenada, demonstrar a combustão em presença e na ausência de oxigênio;',
    'l) Utilizando alguns indicadores ácido/base, demonstrar a acidez ou basicidade de alguns produtos encontrados em nosso dia a dia. E também demonstrar uma reação reversível;',
    'm) Em um acampamento, por um descuido, um desbravador derramou o açúcar que deveria ser utilizado para adoçar o suco da refeição na areia. Utilizando-se do que se tem no acampamento, proponha os passos de um método para separar os componentes da mistura em questão. Em seguida, informe se houve alguma transformação química ou física;',
    'n) Quantos e quais fenômenos estão envolvidos quando uma vela está acesa?']);
  PERFORM pg_temp.set_req('CS-011', NULL, ARRAY[
    '1. Através de desenhos ou modelo, identificar o coração e os pulmões e descrever a função de cada um. Saber onde se localizam em seu corpo.',
    '2. Definir reanimação cardiopulmonar e mencionar quando deve ser utilizada.',
    '3. Completar um curso ministrado por um instrutor qualificado para aprender corretamente, e demonstrar, o processo de reanimação cardiopulmonar. Isso deve ser feito no máximo um ano antes desta especialidade.',
    '4. Saber como manter o coração saudável. Relacionar cinco coisas que uma pessoa pode fazer para manter um coração saudável.',
    '5. Aprender o significado das cores e desenho utilizados na insígnia desta especialidade, de acordo com o seguinte:',
    'a) A pessoa que precisa de reanimação cardiopulmonar pode estar pálida (branca), o que significa que não há circulação;',
    'b) A pessoa que está fazendo a reanimação cardiopulmonar está vermelha, o que significa que está bem ativa;',
    'c) A borda dourada representa o valor da vida humana;',
    'd) Um coração é formado pela cabeça, ombros e membros superiores da pessoa que está fazendo a reanimação cardiopulmonar, o que significa compaixão pelo próximo.']);
  PERFORM pg_temp.set_req('CS-040', NULL, ARRAY[
    '1. Conhecer os oito remédios da natureza.',
    'ALIMENTAÇÃO SAUDÁVEL',
    '2. Desenhar e descrever a pirâmide alimentar. Mencionar o número de porções diárias recomendadas de cada grupo.',
    '3. Qual a importância de uma alimentação saudável para o nosso organismo? Quais os prejuízos de uma alimentação não balanceada?',
    'ÁGUA',
    '4. Qual a importância da água para o nosso organismo? Quais cuidados devemos ter com a água que ingerimos e que usamos para higiene e limpeza?',
    '5. Qual quantidade de água deve ser ingerida por dia?',
    'AR PURO',
    '6. Qual a importância de se respirar ar puro? Que fatores podem influenciar na qualidade do ar?',
    'LUZ SOLAR',
    '7. Quais os benefícios de uma exposição adequada à luz solar?',
    '8. Quais cuidados devemos ter ao nos expormos à luz solar?',
    'EXERCÍCIOS FÍSICOS',
    '9. Qual a importância de se praticar exercícios físicos regularmente? Preparar um plano para uma semana, com 30 minutos de exercícios físicos por dia.',
    'REPOUSO',
    '10. Quanto tempo devemos dormir por dia? Qual a importância de uma boa noite de sono? Quais os prejuízos de não dormir bem?',
    '11. Que fatores podem influenciar na qualidade do sono?',
    'TEMPERANÇA',
    '12. O que é temperança e qual a sua importância para a saúde?',
    '13. Fazer um voto de se abster de álcool, cigarro e outras drogas.',
    'CONFIANÇA EM DEUS',
    '14. Qual a importância da confiança em Deus para a nossa saúde?',
    '15. Preparar e colocar em prática um plano diário de comunhão com Deus, iniciado nas primeiras horas da manhã.']);
  PERFORM pg_temp.set_req('CS-012', NULL, ARRAY[
    '1. O que é resgate de emergência?',
    '2. Demonstrar como resgatar, com segurança, uma pessoa em três das seguintes situações:',
    'a) Em contato com cabo elétrico;',
    'b) Em ambiente cheio de fumaça ou gás;',
    'c) Com as roupas em chamas;',
    'd) Afogando-se, sem qualquer equipamento de resgate;',
    'e) Um acidente no gelo.',
    '3. Conhecer três maneiras de atrair e comunicar-se com um resgate aéreo.',
    '4. Conhecer seis indicadores de necessidade de um resgate imediato.',
    '5. Conhecer o procedimento a se seguir antes de remover uma vítima de situação que apresenta risco de morte.',
    '6. Conhecer as maneiras apropriadas de ajudar uma vítima em perigo, nas seguintes situações:',
    'a) Puxar a vítima;',
    'b) Içar/levantar a vítima;',
    'c) Ajudar a vítima a caminhar.',
    '7. Conhecer a forma adequada de ajudar uma vítima, com ajuda de outros, em três das seguintes situações:',
    'a) Carregar uma pessoa sentada;',
    'b) Carregar uma pessoa deitada;',
    'c) Carregar com cobertor;',
    'd) Transportar uma vítima em uma rede;',
    'e) Carregar em três ou quatro pessoas.',
    '8. Fazer uma maca improvisada e carregar uma pessoa nela.',
    '9. Cumprir os seguintes itens:',
    'a) Atar, pelo menos, três nós para juntar cordas;',
    'b) Atar um nó para diminuir corda;',
    'c) Atar um nó para usar ao redor de alguém num resgate;',
    'd) Enrolar e jogar corretamente uma corda leve e uma pesada, de 15 metros cada.',
    '10. Que passos devem ser dados antes de comunicar que alguém está desaparecido? Que informações serão necessárias ao informar à polícia o desaparecimento de alguém?']);
  PERFORM pg_temp.set_req('CS-018', NULL, ARRAY[
    '1. Nomear os dois componentes do sangue. Qual a porcentagem aproximada de cada um?',
    '2. Desenhar ou colar fotos dos seguintes tipos celulares do sangue, identificando todos: hemácia, plaqueta, neutrófilo, linfócito, eosinófilo, basófilo e monócito. Qual(ais) a(s) principal(ais) função(ões) de cada um?',
    '3. Onde as células sanguíneas são produzidas? Onde são hemolisadas? Qual é o tempo médio que uma hemácia vive?',
    '4. Fazer uma das seguintes opções:',
    'a) Observar algum profissional de saúde retirando o sangue de alguém e descrever quais são os cuidados necessários;',
    'b) Visitar um laboratório onde são feitos exames de sangue. Se informar sobre quais exames são realizados lá e quais os procedimentos necessários para pelo menos três deles;',
    'c) Visitar um banco de sangue. Perguntar como é feito o armazenamento do sangue, qual é o prazo de validade e quais os tipos com menor estoque.',
    '5. Quais gases são transportados pelas hemácias?',
    '6. Explicar o processo de coagulação do sangue. Qual é o primeiro socorro utilizado em caso de hemorragia externa?',
    '7. O que é hemofilia?',
    '8. O que é preciso para ser um doador de sangue? Quais são os cuidados e recomendações principais? Quem não pode doar sangue?',
    '9. Fazer uma tabela mostrando a compatibilidade sanguínea entre todos os tipos sanguíneos.',
    '10. Além das células estudadas no item dois, quais são as outras células envolvidas na defesa do nosso organismo? Ilustrar cada uma delas.',
    '11. O que são anticorpos? Como eles atuam? São produzidos por quais células?',
    '12. Citar dois textos bíblicos em que o sangue está envolvido. Depois de estudar sobre o sangue, por que você acha que a Bíblia usa o sangue como símbolo do poder salvador de Deus?',
    '13. Listar 10 hábitos de saúde que podem ajudar o seu corpo a se manter saudável e combater infecções.',
    '14. Descrever como funcionam as vacinas e os soros.']);
  PERFORM pg_temp.set_req('CS-001', NULL, ARRAY[
    '1. Aprender, através da Bíblia e/ou do Espírito de Profecia, como Jesus curou os doentes e o procedimento usado pelos anciãos da igreja para ungir o doente e pedir a Deus pela cura. Apresentar um relatório oral sobre o que você aprendeu ou escrever um relatório com, no mínimo, 250 palavras.',
    '2. Qual a importância da educação contínua para os profissionais de saúde?',
    '3. Entrevistar pelo menos duas pessoas que trabalham na área de saúde. Uma delas deve ter outra profissão que não médico(a) ou enfermeiro(a), como por exemplo, dentista, fisioterapeuta, psicólogo, nutricionista, etc. Em suas entrevistas, fazer as seguintes perguntas:',
    'a) Por que escolheu esta profissão?',
    'b) Que faculdade (ou cursos) é preciso fazer para trabalhar em sua profissão?',
    'c) Além da conclusão da faculdade/curso, que outros requisitos são necessários para exercer a sua profissão?',
    'd) Qual é o aspecto que você mais gosta em seu trabalho? O que gosta menos?',
    'e) Que dias da semana, e quantas horas diárias, você tem que trabalhar?',
    'f) Que tipos de promoção você pode ter em sua carreira?',
    'g) Que outros cursos você poderia fazer para completar seus conhecimentos sobre sua profissão?',
    'h) Quais algumas instituições em sua cidade que oferecem cursos na sua área?',
    '4. Completar uma das seguintes atividades:',
    'a) Visitar um consultório médico ou odontológico e fazer o seguinte:',
    '• Observar as áreas de operação, tais como a área administrativa, laboratório, salas de exames, salas de raios-X, etc.;',
    '• Pedir ajuda para alguém lhe apresentar os equipamentos usados naquele consultório;',
    '• Aprender os passos de uma consulta, desde o momento em que o paciente chega à sala de espera até o momento em que deixa o consultório;',
    '• Aprender como o médico/dentista examina o paciente, desde as anotações da história clínica até o diagnóstico e conduta.',
    'b) Fazer uma visita com um enfermeiro(a) ou técnico(a) de enfermagem que trabalhe a domicílio, e:',
    '• Aprender os passos de uma visita em domicílio, desde quando o enfermeiro/técnico de enfermagem descobre algo sobre o paciente, até o momento em que relata o caso a um médico;',
    '• Observar o enfermeiro/técnico de enfermagem aferir os sinais vitais do paciente;',
    '• Observar o enfermeiro/técnico de enfermagem dando instruções e administrando medicamentos.',
    'c) Visitar um laboratório ou qualquer instituição que realize exames complementares (como radiografia, ultrassonografia, eletrocardiograma, etc.) e fazer o seguinte:',
    '• Observar as diferentes áreas de atuação do laboratório;',
    '• Quais exames são realizados?',
    '• Quais as orientações aos pacientes para realizarem estes exames?',
    '• Pedir que alguém lhe apresente o equipamento usado no laboratório, e como funciona;',
    '• Aprender os passos dados por um paciente quando vai àquele laboratório;',
    '• Quantas pessoas trabalham no laboratório?',
    '• O laboratório funciona à noite?',
    '5. Através de pesquisa na internet ou visita a uma faculdade/universidade da sua cidade ou estado, descobrir algumas matérias e a duração dos seguintes cursos da área da saúde:',
    'a) Biomedicina;',
    'b) Enfermagem;',
    'c) Farmácia;',
    'd) Medicina;',
    'e) Nutrição;',
    'f) Odontologia;',
    'g) Psicologia.']);
  PERFORM pg_temp.set_req('CS-028', NULL, ARRAY[
    '1. O que são transtornos mentais?',
    '2. Definir os seguintes termos:',
    'a) Cognitivo;',
    'b) Terapia;',
    'c) Fator de proteção;',
    'd) Fator de risco;',
    'e) Psicologia;',
    'f) Psiquiatria.',
    '3. O que é saúde mental e qual a sua importância? Citar algumas práticas que colaboram com a saúde mental.',
    '4. O que é ansiedade? O que você pode fazer para ajudar alguém que sofre desse transtorno?',
    '5. O que é depressão? O que você pode fazer para ajudar alguém que sofre desse transtorno?',
    '6. Que versos bíblicos ou citações do Espírito de Profecia você pode utilizar para ajudar uma pessoa com ansiedade ou depressão?',
    '7. Escolher um transtorno mental e preparar uma apresentação com recursos audiovisuais para apresentá-lo em sua igreja, escola, clube ou comunidade. Incluir as seguintes informações:',
    'a) Características diagnósticas;',
    'b) Desenvolvimento e curso;',
    'c) Fatores de risco;',
    'd) Tratamento;',
    'e) Prognóstico.',
    '8. O que são psicofármacos e quando são indicados?',
    '9. Que relação existe entre o 4º mandamento da Lei do Desbravador e a saúde mental? Fazer um voto prometendo cuidar e manter sua mente livre das influências perturbadoras dos dias atuais.']);
  PERFORM pg_temp.set_req('CS-029', NULL, ARRAY[
    'Nota: Necessário o acompanhamento de um instrutor qualificado. Essa especialidade deve ser instruída em grupos separados por sexo e faixa etária aproximada. Somente pessoas do sexo masculino podem instruí-la para os garotos e somente as do sexo feminino podem instruí-la para as garotas.',
    '1. O que é sexualidade humana?',
    '2. Qual é o modelo divino para a sexualidade?',
    '3. O que é sexo biológico? Quantos tipos existem?',
    '4. Através de desenhos ou figuras escolhidos previamente e trazidas pelo seu instrutor, representar os órgãos sexuais masculinos e femininos e responder:',
    'a) Quais são os órgãos sexuais/reprodutivos internos?',
    'b) Quais são os órgãos sexuais/reprodutivos externos?',
    'c) Qual é a função de cada um desses órgãos?',
    'd) Por que é tão importante chamar esses órgãos pelos nomes corretos?',
    '5. O que é puberdade? Quando ela se inicia nos homens e nas mulheres? Quais as mudanças físicas e psicológicas que ocorrem?',
    '6. O que é menstruação e polução noturna? Em que idade se iniciam e quando terminam?',
    '7. Por que a higiene genital, tanto masculina quanto feminina, é importante?',
    '8. O que é gravidez, como ela ocorre e quanto tempo dura?',
    '9. O que é aborto? Quais são as consequências físicas e psicológicas envolvidas? Em quais casos o aborto é permitido em seu país?',
    '10. Como reconhecer e se proteger de possíveis abusos sexuais e seus perigos? A quem devemos recorrer em caso de alguém (desconhecido, amigo ou familiar) ter sido abusado? Por que é importante não ficar calado?',
    '11. O que são Infecções Sexualmente Transmissíveis (ISTs)? Responder o seguinte:',
    'a) O que é HIV?',
    'b) O que é AIDS?',
    'c) Como se contrai o HIV?',
    'd) Quanto tempo leva do contágio até o início dos sintomas?',
    'e) Que testes ou exames médicos podem ser feitos para saber se uma pessoa está infectada?',
    'f) Quais cuidados uma pessoa soropositiva necessita? Quais e quantos medicamentos toma por dia?',
    'g) Pesquisar outras cinco Infecções Sexualmente Transmissíveis e responder sobre cada uma delas: forma(s) de contágio(s), sintomas, agente etiológico e se há tratamento.',
    '12. Quando temos uma dúvida sobre sexualidade, a quem devemos procurar pedindo ajuda? Por que amigos da minha idade são “pouco confiáveis” para o assunto?',
    '13. O que é paixão e o que é namoro? Quando são saudáveis? Quando estão distorcidos e são prejudiciais? Como saber o momento correto para se terminar um namoro? Como terminar uma relação adequadamente?']);
  PERFORM pg_temp.set_req('CS-017', '3', ARRAY[
    '1. Fazer um diagrama ou modelo do sistema nervoso central, incluindo as seguintes partes: cérebro, cerebelo, ponte, medula espinhal. Descrever a função básica de cada um.',
    '2. O que é um neurônio? Desenhar um neurônio e identificar as suas partes. O que é sinapse?',
    '3. Quais são as principais diferenças do sistema nervoso somático e sistema nervoso autônomo? Diferenciar sistema nervoso autônomo simpático e sistema nervoso autônomo parassimpático, descrevendo as principais atividades relacionadas a cada um deles.',
    '4. Explicar como as drogas afetam a função dos neurônios, especialmente a sinapse. Fazer um compromisso de nunca usar drogas.',
    '5. O que é reflexo? Fazer o teste do reflexo patelar em alguém. (Instruções: pedir para alguém ficar sentado com os pés sem encostar no chão. Gentilmente, dar uma pequena batida abaixo do joelho). Explicar por que esse reflexo ocorre (usar no seu relatório os seguintes termos: neurônio sensorial, neurônio motor, medula espinhal). Por que os médicos usam esse teste num exame físico?',
    '6. O que são neurônios sensoriais? O que é adaptação? Demonstrar o que é adaptação fazendo o seguinte:',
    'a) Descansar o seu braço numa mesa e colocar uma tampa (ou algo muito leve) sobre ele. Notar o que você está sentindo naquele momento e um minuto depois, sem mover o braço de lugar;',
    'b) Colocar um dedo de uma mão numa tigela com água fria e outro dedo de outra mão numa com água morna. Depois de 30 segundos, colocar os dois dedos numa tigela com água em temperatura ambiente. O que você sentiu em cada dedo?',
    'c) Qual a lição espiritual que você pode tirar do conceito de adaptação?',
    '7. Fazer uma das seguintes atividades:',
    'a) Observar um eletroencefalograma e explicar a sua função;',
    'b) Observar uma ressonância nuclear magnética ou uma tomografia computadorizada do encéfalo ou da coluna vertebral e explicar a sua função;',
    'c) Explicar como uma anestesia funciona.',
    '8. Listar, pelo menos, cinco coisas que você pode fazer para proteger o seu cérebro de danos.',
    '9. Escolher dois dos seguintes, detalhando como ocorre, fatores de risco, sinais e sintomas e tratamento:',
    'a) Doença de Alzheimer;',
    'b) Doença de Parkinson;',
    'c) Esclerose múltipla;',
    'd) Epilepsia;',
    'e) Acidente vascular encefálico;',
    'f) Enxaqueca;',
    'g) Síndrome de Down;',
    'h) Tetraplegia;',
    'i) Paraplegia.']);
  PERFORM pg_temp.set_req('CS-030', NULL, ARRAY[
    '1. Quais são as estruturas que formam o sistema respiratório? Ilustrar e descrever as principais funções de cada uma.',
    '2. Quais são os dois principais gases do nosso organismo? O que é troca gasosa? Descrever as vias condutoras do ar até o momento da troca gasosa.',
    '3. O que é alvéolo e qual a sua função? Através de desenhos ou figuras, ilustrar um alvéolo demonstrando o momento da troca gasosa.',
    '4. Qual a principal função das células ciliadas, com cílios móveis?',
    '5. Qual a relação entre respiração celular e respiração pulmonar?',
    '6. Explicar como os sistemas circulatório e respiratório estão intimamente ligados.',
    '7. Qual a importância da hemoglobina e do ferro para a oxigenação do organismo?',
    '8. Descrever os movimentos de inspiração e expiração. Qual a importância do músculo diafragma para estes movimentos?',
    '9. Qual órgão do sistema nervoso central controla a respiração? Por quê?',
    '10. Qual é a frequência respiratória normal dos seguintes:',
    'a) Recém-nascidos;',
    'b) Crianças;',
    'c) Adultos.',
    '11. Definir os seguintes termos:',
    'a) Eupneia;',
    'b) Taquipneia;',
    'c) Bradipneia;',
    'd) Dispneia;',
    'e) Apneia.',
    '12. Estudar duas das seguintes doenças respiratórias e dizer, sobre cada uma, como ocorre, como é adquirida, transmissão (se for o caso), sinais e sintomas, tratamento e prevenção:',
    'a) Asma;',
    'b) Tuberculose pulmonar;',
    'c) Pneumonia;',
    'd) Gripe;',
    'e) Bronquiolite viral aguda;',
    'f) Enfisema pulmonar;',
    'g) Tromboembolismo pulmonar;',
    'h) Fibrose cística;',
    'i) Covid-19.',
    '13. Pesquisar os efeitos do cigarro no sistema respiratório. Apresentar seus resultados de uma das seguintes maneiras:',
    'a) Relatório escrito, com no mínimo 250 palavras;',
    'b) Apresentação oral, de no mínimo cinco minutos;',
    'c) Exposição de cartazes e faixas;',
    'd) Poema ou música.']);
  PERFORM pg_temp.set_req('CS-041', NULL, ARRAY[
    '1. Definir o que é direção defensiva.',
    '2. Quais são os cinco fundamentos da direção defensiva?',
    '3. O que deve ser verificado em um automóvel antes de colocá-lo em circulação?',
    '4. Como se deve conduzir um veículo automotor prudentemente (automóvel e motocicleta)?',
    '5. Qual a responsabilidade hierárquica no trânsito?',
    '6. Explicar por onde e como o pedestre deve circular nas vias públicas e nas estradas.',
    '7. Quais são os equipamentos obrigatórios para os condutores de motocicletas, motonetas ou ciclomotores?',
    '8. Qual a idade mínima para se transportar passageiros em motocicletas e similares?',
    '9. Qual a idade mínima para se transportar um passageiro no banco dianteiro de um automóvel?',
    '10. Em relação às crianças, quais os dispositivos auxiliares de segurança para automóveis?',
    '11. Por que é importante manter os pneus dos veículos automotores em bom estado de conservação?',
    '12. Como ajudar uma vítima de acidente de trânsito?',
    '13. Fazer um projeto com seu Clube de Desbravadores com o título “Trânsito Seguro”, produzindo e distribuindo folhetos explicativos sobre o tema ou apresentando qualquer outro material de divulgação.']);
  PERFORM pg_temp.set_req('CS-042', NULL, ARRAY[
    '1. Explicar como as vacinas funcionam e qual o significado da palavra vacina.',
    '2. Contar a história do surgimento da primeira vacina.',
    '3. Explicar as características, vantagens e desvantagens das vacinas abaixo:',
    'a) Atenuada;',
    'b) Inativada;',
    'c) Vetor viral;',
    'd) Subunidades;',
    'e) RNA.',
    '4. Qual a primeira doença erradicada no mundo em decorrência da vacinação?',
    '5. Fazer uma tabela com as vacinas disponibilizadas pelo serviço público de saúde do seu país. Quais doenças elas previnem e quando elas devem ser aplicadas?',
    '6. Explicar as etapas para o desenvolvimento de uma nova vacina.',
    '7. Qual a importância de ter um número grande de pessoas vacinadas? O que é imunidade de rebanho ou imunidade coletiva?']);
  PERFORM pg_temp.set_req('CS-043', NULL, ARRAY[
    '1. O que são zoonoses?',
    '2. O que é um Centro de Controle de Zoonoses? Quais suas atribuições?',
    '3. Qual a diferença entre zoonoses e arboviroses? Dar exemplos de cada tipo.',
    '4. Citar duas zoonoses que podem ser transmitidas por ratos e citar medidas preventivas.',
    '5. A raiva pode ser transmitida por quais animais? O que deve ser feito ao ser mordido por um animal?',
    '6. O que é toxoplasmose e quais os principais grupos de risco dessa zoonose? Como ela é transmitida?',
    '7. Explicar como as seguintes zoonoses são transmitidas e como podemos evitá-las:',
    'a) Tuberculose;',
    'b) Brucelose;',
    'c) Leishmaniose;',
    'd) Criptococose.',
    '8. Fazer um esquema mostrando o ciclo da teníase/cisticercose, demonstrando as formas de contaminação, os hospedeiros e formas de prevenção.',
    '9. O que é febre maculosa e como é transmitida? Como ela pode ser evitada?',
    '10. Quais cuidados precisamos ter com nossos animais de estimação para que tenham uma vida saudável e para evitar que fiquem doentes?']);
END $$;
