-- Requisitos das especialidades conforme o Manual de Especialidades 2025 (transcricao compilada em Word).
-- Substitui os requisitos de cada especialidade (a linha de cada requisito/subitem na ordem do manual) e
-- atualiza a quantidade de requisitos. Ortografia e acentos revisados. Estudos da Natureza e Habilidades Domesticas (so as que o Word reproduz fielmente). Parte 1 de 1.
-- Tudo ou nada: se alguma especialidade nao for encontrada pelo codigo, nada e alterado.
CREATE OR REPLACE FUNCTION pg_temp.set_req(p_codigo text, p_nivel text, p_linhas text[]) RETURNS void
LANGUAGE plpgsql AS $f$
DECLARE
  v_prog integer := (SELECT id FROM public.programas WHERE nome ILIKE '%desbravador%' ORDER BY id LIMIT 1);
  em public.especialidades_modelo%ROWTYPE;
BEGIN
  SELECT * INTO em FROM public.especialidades_modelo WHERE programa_id = v_prog AND codigo = p_codigo;
  IF NOT FOUND THEN RAISE EXCEPTION 'Especialidade % nao encontrada.', p_codigo; END IF;

  DELETE FROM public.mda_requisitos_modelo
   WHERE programa_id = v_prog AND item_tipo = 'Especialidade'
     AND (especialidade_id = em.id OR (especialidade_id IS NULL AND item_url IS NOT NULL AND item_url = em.item_url));

  INSERT INTO public.mda_requisitos_modelo (programa_id, item_tipo, item_nome, item_codigo, item_url, especialidade_id, secao, ordem, texto)
  SELECT v_prog, 'Especialidade', em.nome, em.codigo, COALESCE(em.item_url, 'manual-2025/' || em.codigo), em.id, NULL, t.ord::integer, t.txt
    FROM unnest(p_linhas) WITH ORDINALITY AS t(txt, ord);

  UPDATE public.especialidades_modelo
     SET quantidade_requisitos = array_length(p_linhas, 1),
         nivel = COALESCE(p_nivel, nivel),
         updated_at = now()
   WHERE id = em.id;
END
$f$;

DO $$
BEGIN
  PERFORM pg_temp.set_req('EN-096', '1', ARRAY[
    '1. A que ordem pertencem as abelhas, vespas e marimbondos? Quais as características dessa ordem? Que outro inseto comum pertence a essa mesma ordem?',
    '2. O que significa o termo holometábolo? Ilustrar o ciclo de vida de um inseto holometábolo.',
    '3. Qual o nome científico da abelha conhecida como Europa?',
    '4. Como as abelhas são classificadas em uma colônia?',
    '5. Responder o seguinte sobre as abelhas:',
    'a) Qual a maior espécie de abelha?',
    'b) Por que as abelhas são tão sociáveis entre si e as vespas não?',
    'c) Qual o nome da profissão de criador de abelhas?',
    'd) Por que a abelha morre logo após ferroar uma pessoa ou animal?',
    'e) De onde foi trazida a espécie de abelha Apis mellifera ligustica para a América do Sul?',
    'f) O que faz as abelhas seguirem sua rainha?',
    'g) O que as abelhas coletam nas flores?',
    '6. Citar cinco espécies de abelhas que não possuem ferrão.',
    '7. Quais os possíveis benefícios e malefícios das abelhas ao ser humano e à natureza?',
    '8. Como as abelhas realizam a polinização das flores? Ilustrar.',
    '9. Quais as diferenças entre vespas e marimbondos?',
    '10. Descrever as características das vespas e dos marimbondos, incluindo hábitos, alimentação e reprodução.',
    '11. Ilustrar e descrever o ciclo de vida da vespa Pepsis formosa pationii.',
    '12. Quais os possíveis benefícios e malefícios das vespas e marimbondos ao ser humano e à natureza?',
    '13. Qual espécie de ave só constrói seus ninhos onde há casas de marimbondos/vespas?',
    '14. Completar os requisitos a seguir:',
    'a) Encontrar um texto bíblico contendo a palavra vespa;',
    'b) Citar três personagens bíblicos que comeram mel;',
    'c) A que povo pertenciam os dois reis que foram expulsos de suas terras por vespões?',
    'd) Segundo a Bíblia, o que é mais doce do que o mel?',
    'e) Qual a responsabilidade do ser humano com a natureza? (Gênesis 1:27 e 28; 2:15)']);
  PERFORM pg_temp.set_req('EN-036', '3', ARRAY[
    '1. Definir o que são algas. Qual a sua importância para o ecossistema?',
    '2. Onde as algas podem ser encontradas?',
    '3. Como é chamado o órgão de fixação ao substrato? Que diferenças e semelhanças podem ser encontradas entre uma alga e uma planta?',
    '4. Explicar por que há uma variação de tamanho entre as algas marinhas.',
    '5. Citar, pelo menos, quatro grupos de algas marinhas. Para cada grupo mencionar as seguintes informações:',
    'a) Nome popular;',
    'b) Nome científico;',
    'c) Estrutura (unicelular, pluricelular ou ambos).',
    '6. O que são diatomáceas? Onde são encontradas?',
    '7. Onde as algas marinhas crescem com mais frequência: zona polar, temperada ou tropical? Explicar.',
    '8. Onde as algas marrons ou pardas são mais comumente encontradas, em água doce ou salgada?',
    '9. Qual a maior profundidade em que as algas marinhas crescem no oceano? Explicar o motivo das algas não se desenvolverem em águas profundas.',
    '10. Nomear três partes de uma alga marinha de grande porte. Como elas podem ser comparadas a uma folha, a um caule e a uma raiz de uma planta?',
    '11. Explicar, pelo menos, duas formas de reprodução das algas marinhas.',
    '12. Citar algumas vantagens comerciais que as algas marinhas podem contribuir ao homem.',
    '13. Montar um álbum de fotografias/imagens contendo, pelo menos, 20 espécimes de algas. Identificá-las pelo nome popular e, se possível, o nome científico.']);
  PERFORM pg_temp.set_req('EN-023', '2', ARRAY[
    '1. Quais as características dos anfíbios?',
    '2. Dar o nome das três ordens pertencentes à classe Amphibia e citar as principais diferenças entre elas.',
    '3. Como os anfíbios se protegem?',
    '4. Onde os anfíbios passam o inverno ou a estação seca?',
    '5. Por meio de imagens, fotos, desenhos ou pessoalmente, identificar sapos, rãs e pererecas. Como diferenciá-los?',
    '6. Descrever e esquematizar o ciclo de vida de um anuro.',
    '7. Qual parte do corpo é utilizada para amplificar o som que os anuros produzem? Tanto machos quanto fêmeas são capazes de coaxar? Para que os anuros utilizam seus coaxos?',
    '8. Explicar do que e como a maioria dos anuros se alimenta.',
    '9. Identificar, por meio de fotos ou imagens, 10 diferentes espécies de anfíbios encontrados em seu estado ou país.',
    '10. Observar um anfíbio em seu habitat natural ou em cativeiro, ao vivo ou em vídeo, por alguns minutos e escrever um relatório sobre o que você observou.']);
  PERFORM pg_temp.set_req('EN-054', '3', ARRAY[
    '1. Ter a especialidade de Anfíbios.',
    '2. Como é chamado o estudo dos anfíbios?',
    '3. Qual a diferença entre animais peçonhentos e animais venenosos? Os anfíbios podem ser classificados em qual desses grupos? Todos os anfíbios possuem toxinas?',
    '4. Realizar uma pesquisa simples com base na observação natural ou em cativeiro de um ou mais anfíbios e escrever uma redação de, no mínimo, 500 palavras com os resultados da sua observação. Sugestões de temas para estudo:',
    'a) Habitat;',
    'b) Metamorfose;',
    'c) Efeitos da temperatura e umidade;',
    'd) Alimentação;',
    'e) Reprodução.',
    'Ao realizar o estudo, ter certeza de estar em conformidade com as leis ambientais de seu Estado e país.']);
  PERFORM pg_temp.set_req('EN-058', '2', ARRAY[
    '1. Definir os seguintes termos:',
    'a) Habitat;',
    'b) Bioma;',
    'c) Cadeia alimentar;',
    'd) Caçador ilegal.',
    '2. Qual é a lista de espécies ameaçadas mundialmente mais conhecida? Descrever as categorias existentes nesta lista e citar uma espécie para cada categoria.',
    '3. Listar quatro fatores que fazem os animais se tornarem ameaçados de extinção.',
    '4. Dar o nome de quatro animais que estão extintos agora, preferencialmente espécies do seu estado ou país.',
    '5. Listar quatro coisas que estão sendo feitas para salvar animais ameaçados de extinção em seu país. Caso seu país não esteja fazendo pelo menos quatro coisas para salvar espécies ameaçadas, pesquisar medidas adotadas em países próximos e que poderiam ser adotadas no seu país.',
    '6. Listar quatro atividades que você pode fazer para ajudar animais silvestres.',
    '7. Listar 10 espécies de animais ameaçados, sendo no mínimo quatro do seu estado ou país. Dizer onde eles vivem, por que se tornaram ameaçados de extinção e o que você pode fazer para ajudá-los.',
    '8. Fazer duas das seguintes atividades:',
    'a) Visitar um zoológico que tenha um ou mais animais ameaçados residentes no local. Listar que animais você viu, onde eles vivem normalmente e por que eles se tornaram ameaçados de extinção;',
    'b) Assistir a um vídeo sobre um animal ameaçado de extinção. Listar qual animal ou quais animais você viu, onde eles normalmente vivem e por que ele se tornou ameaçado de extinção;',
    'c) Escolher um animal ameaçado de extinção e escrever ou apresentar oralmente um curto relatório sobre o assunto. Dizer onde ele vive normalmente, por que se tornou ameaçado de extinção, o que está sendo feito para salvá-lo e qualquer outro detalhe especial que você aprendeu sobre este animal em particular;',
    'd) Fazer um álbum de recortes sobre animais ameaçados de extinção. Isso pode incluir artigos de jornais, histórias, fotos, selos ou desenhos. Este pode ser um projeto em grupo;',
    'e) Fazer uma teia da vida, ou outra dinâmica de grupo sobre ecossistemas.',
    '9. Conhecer as principais leis relacionadas às espécies ameaçadas de extinção em seu país. Essas leis podem ser encontradas na seção de legislação dos sites da Presidência da República e do Ministério do Meio Ambiente.',
    '10. Explicar Gênesis 1:26-28 e Gênesis 2:15 com suas próprias palavras.']);
  PERFORM pg_temp.set_req('EN-097', '1', ARRAY[
    '1. Qual a diferença entre migração, imigração e emigração?',
    '2. Por quais motivos os animais migram?',
    '3. Quais os perigos encontrados no curso da migração?',
    '4. Citar um exemplo de animal migratório para cada uma das seguintes classes:',
    'a) Mamíferos;',
    'b) Insetos;',
    'c) Peixes;',
    'd) Aves.',
    '5. Para cada animal do requisito 4, descrever todo o processo de migração, o motivo da migração, os perigos encontrados, etc.',
    '6. Qual a maior e a menor espécie de animais migratórios?',
    '7. Qual espécie realiza a maior distância de migração?',
    '8. Fazer um pequeno estudo sobre o animal que concentra a maior quantidade de indivíduos em migração.']);
  PERFORM pg_temp.set_req('EN-071', '1', ARRAY[
    '1. O que são animais nocivos?',
    '2. Qual a diferença entre animais nocivos e animais peçonhentos?',
    '3. Saber como alguns animais nocivos podem estar diretamente ligados a alguns tipos de surtos, epidemias e pandemias. Citar três exemplos.',
    '4. Conhecer, no mínimo, quatro tipos de doenças transmitidas por animais nocivos.',
    '5. Como os animais podem prejudicar plantações e a vida de outros animais?',
    '6. Escolher e apresentar as seguintes características de dois animais nocivos:',
    'a) Habitat;',
    'b) Forma de reprodução;',
    'c) Alimentação;',
    'd) Doenças ou danos causados aos seres humanos;',
    'e) Forma de prevenção.',
    '7. Citar, pelo menos, três animais nocivos em cada uma das classes abaixo:',
    'a) Mamíferos;',
    'b) Insetos;',
    'c) Répteis;',
    'd) Anfíbios.',
    '8. Descobrir como alguns animais nocivos são importantes para o equilíbrio do ecossistema.',
    '9. Aprender quatro maneiras de se proteger contra animais nocivos que são encontrados em casas ou empresas.',
    '10. Realizar uma das atividades abaixo:',
    'a) Visitar um zoológico ou local de pesquisa em que você possa observar animais nocivos e apresentar um relatório;',
    'b) Com a orientação do seu líder, identificar, no mínimo, 10 animais nocivos e apresentar uma relação com: nome científico, nome popular, foto e local onde é encontrado.',
    '11. Descobrir três animais nocivos citados na Bíblia, com seus respectivos versos.']);
  PERFORM pg_temp.set_req('EN-070', '1', ARRAY[
    '1. O que são animais noturnos?',
    '2. Como os animais noturnos são influenciados pelo clima em que estão inseridos?',
    '3. Escolher e apresentar as seguintes características de dois animais noturnos:',
    'a) Habitat;',
    'b) Forma de reprodução;',
    'c) Alimentação;',
    'd) Hábitos.',
    '4. Ser capaz de identificar, pelo menos, três animais noturnos das classes abaixo:',
    'a) Mamíferos;',
    'b) Insetos;',
    'c) Anfíbios;',
    'd) Aves;',
    'e) Répteis.',
    '5. Explicar como os sentidos dos animais noturnos são fundamentais para se viver na escuridão.',
    '6. Realizar uma das atividades abaixo:',
    'a) Observar por, no mínimo, dois dias um animal noturno doméstico e fazer um relatório do seu comportamento;',
    'b) Realizar uma visita noturna em um aquário ou zoológico e apresentar um relatório do seu contato com os animais noturnos;',
    'c) Assistir a um documentário sobre um ou mais animais noturnos e apresentar um relatório do que aprendeu.',
    '7. O que são quirópteros e quais seus benefícios e malefícios para o ser humano?',
    '8. Descobrir, pelo menos, três versos que citem animais noturnos na Bíblia.']);
  PERFORM pg_temp.set_req('EN-069', '1', ARRAY[
    '1. O que são animais peçonhentos?',
    '2. Descobrir a quantidade de acidentes causados por animais peçonhentos em seu país ou região no último ano (caso esse dado não esteja disponível, pegar o último ano disponível).',
    '3. Escolher e apresentar as seguintes características de dois animais peçonhentos:',
    'a) Habitat;',
    'b) Alimentação;',
    'c) Danos causados aos seres humanos;',
    'd) Forma de prevenção.',
    '4. Citar, pelo menos, três animais peçonhentos em cada uma das classes abaixo:',
    'a) Répteis;',
    'b) Insetos;',
    'c) Aracnídeos.',
    '5. Saber como os animais peçonhentos são importantes para o equilíbrio do ecossistema.',
    '6. Aprender quatro maneiras de se proteger contra animais peçonhentos que são encontrados em casas, empresas ou acampamentos.',
    '7. Os animais peçonhentos geralmente atacam por maldade ou por defesa?',
    '8. Aprender os primeiros socorros que devem ser prestados às vítimas de picadas de animais peçonhentos.',
    '9. O que é soroterapia?',
    '10. Saber para qual picada de animal serve cada tipo de soro abaixo:',
    'a) Antibotrópico;',
    'b) Anticrotálico;',
    'c) Antibotrópico-laquético;',
    'd) Antielapídico;',
    'e) Antiaracnídico;',
    'f) Antiescorpiônico;',
    'g) Antilonômico.',
    '11. Realizar uma das atividades abaixo:',
    'a) Visitar um zoológico ou local de pesquisa em que você possa observar animais peçonhentos e apresentar um relatório;',
    'b) Com a orientação do seu líder, identificar, no mínimo, 10 animais peçonhentos e apresentar uma relação com: nome científico, nome popular, foto e local de origem.',
    '12. Descobrir, no mínimo, dois versos que citem animais peçonhento na Bíblia.']);
  PERFORM pg_temp.set_req('EN-068', '3', ARRAY[
    'Nota: todos os espécimes utilizados para o cumprimento desta especialidade devem ser adquiridos em concordância com as leis vigentes em seu país.',
    '1. Ter a especialidade de Peixes.',
    '2. O que é aquarismo ou aquariofilia?',
    '3. Apresentar a história do aquarismo, primeiros povos a praticar, desenvolvimento das técnicas, evidências históricas, etc.',
    '4. Explicar o que é, como funciona e qual a utilidade dos seguintes:',
    'a) Termostato;',
    'b) Cascalho;',
    'c) Substrato;',
    'd) Ração de férias;',
    'e) Placa biológica;',
    'f) Bio Ball;',
    'g) Rede coletora;',
    'h) Filtro fluidizado;',
    'i) Filtro externo;',
    'j) Filtro UV;',
    'k) Ozonizadores;',
    'l) Reator de cálcio;',
    'm) Skimmer;',
    'n) Incentivadores bacterianos ("aceleradores de biologia");',
    'o) Alimentador automático.',
    '5. Citar algumas vantagens e desvantagens de um aquário de água salgada em relação a um de água doce.',
    '6. Identificar, ao vivo ou por foto, 10 peixes ornamentais de água salgada e 15 peixes ornamentais de água doce, comumente utilizados em aquários.',
    '7. Conhecer 10 plantas aquáticas de água doce, comumente utilizadas em aquários. Identificá-las por meio de foto ou ao vivo.',
    '8. Identificar, ao vivo ou por fotos, cinco corais utilizados em aquários marinhos.',
    '9. Listar e identificar, ao vivo ou por fotos, cinco animais comuns em aquários marinhos. (Não incluir peixes ou corais na lista).',
    '10. Listar e identificar, ao vivo ou por fotos, cinco animais comuns em aquários de água doce. (Não incluir peixes na lista).',
    '11. Listar cinco diferentes testes de água, explicar a importância de utilizá-los e demonstrar o uso de, ao menos, um deles.',
    '12. Completar o seguinte:',
    'a) Montar um aquário de, ao menos, 20 litros, com quantidade equilibrada de plantas e peixes e mantê-lo por, no mínimo, um mês;',
    'b) Durante a montagem, observar o seguinte:',
    '• Demonstrar habilidade em montar e explicar o funcionamento de um sistema de filtragem adequado;',
    '• Explicar a escolha e instalar um sistema de iluminação compatível;',
    '• Escolher o tipo de solo mais indicado para o ambiente desejado;',
    '• Plantas: analisar as espécies que melhor se adequam ao modelo;',
    '• Peixes: explicar sobre as espécies escolhidas, a relação espaço versus tamanho adulto e quantidade de espécimes; temperatura ideal para o crescimento, temperamento, tipo de ração, reprodução, principais doenças e problemas;',
    'c) Durante este período, tomar nota dos efeitos, nos peixes e no aquário em geral, das seguintes condições:',
    '• Luz demais;',
    '• Luz de menos;',
    '• Alimento demais;',
    '• Mudanças na temperatura da água;',
    '• Poucas plantas para muitos peixes.']);
  PERFORM pg_temp.set_req('EN-001', '2', ARRAY[
    '1. Quais são as principais características das aranhas? Quais são as principais diferenças entre as aranhas e os insetos?',
    '2. Qual a utilidade da teia para as aranhas? Qual a utilidade da teia de aranha para o ser humano?',
    '3. Fazer um desenho de uma teia esférica.',
    '4. Descrever outros tipos de teia existentes além da esférica ou orbicular.',
    '5. Do que se alimentam as aranhas? Observar teias de aranhas e listar as presas encontradas.',
    '6. Quais são os principais predadores das aranhas? Além de seus predadores, qual o principal inimigo das aranhas e por quê?',
    '7. Qual é a maior aranha do mundo?',
    '8. Fazer um dos seguintes:',
    'a) Coletar, identificar e preservar, pelo menos, 16 espécies de aranhas. Cada vidro deve conter uma etiqueta com o local e data de captura, nome do coletor e nome da aranha. (Ao cumprir este requisito, esteja certo de não estar infringindo nenhuma lei de seu país).',
    'b) Desenhar e identificar, pelo menos, 16 espécies de aranhas, com suas cores naturais e em tamanho real ou ampliado.',
    'c) Tirar fotografias coloridas e identificar, pelo menos, 16 espécies de aranhas. Colocar local e data onde a fotografia foi tirada.',
    '9. Escrever uma descrição de, pelo menos, 40 palavras sobre uma espécie de aranha conhecida em sua região ou país.',
    '10. Quantas espécies de aranhas peçonhentas existem no mundo? E em sua região? O que fazer em caso de picada de aranha?',
    '11. Como as aranhas podem ser benéficas ao homem? Como as aranhas podem ser prejudiciais ao homem?',
    '12. Encontrar duas referências bíblicas às aranhas e suas teias.']);
  PERFORM pg_temp.set_req('EN-073', '1', ARRAY[
    '1. As araras, os papagaios e os periquitos pertencem a qual ordem e a qual família de aves? Quais são as principais características que diferenciam esta ordem dos outros pássaros?',
    '2. Dar o nome de 15 espécies de araras, papagaios e periquitos comuns em seu país e ser capaz de identificá-los ao ar livre, em cativeiro ou em fotos. (Caso não existam 15 espécies em seu país, considerar o continente.)',
    '3. Onde as araras, os papagaios e os periquitos constroem seus ninhos?',
    '4. Quais são as características destas aves que chamam atenção e as tornam bons animais de estimação? Quais aves deste grupo são as mais criadas em seu país?',
    '5. Quais são as maiores ameaças enfrentadas pelas araras, papagaios e periquitos? Citar quatro espécies que estão ameaçadas de extinção.',
    '6. Escolher uma espécie entre as ameaçadas de extinção e dizer:',
    'a) Nome popular e nome científico;',
    'b) Habitat e distribuição geográfica;',
    'c) Alimentação;',
    'd) Principais ameaças;',
    'e) Estratégias de conservação.',
    '7. Escolher uma espécie não ameaçada de extinção e dizer:',
    'a) Nome popular e nome científico;',
    'b) Habitat e distribuição geográfica;',
    'c) Alimentação.',
    '8. Onde é possível adquirir uma arara, um papagaio ou periquito com origem legal? Por que não se recomenda comprar animais que não tenham origem legal?']);
  PERFORM pg_temp.set_req('EN-074', '2', ARRAY[
    '1. O que significa a palavra briófita?',
    '2. Citar quatro características deste grupo de plantas.',
    '3. Através de figuras ou ao natural, identificar os rizoides, cauloides e filoides.',
    '4. Pesquisar e esquematizar o ciclo de vida de uma briófita.',
    '5. Por qual motivo as briófitas apresentam grande dependência da água?',
    '6. Em qual tipo de ambiente é comum encontrarmos briófitas?',
    '7. Qual nome popular é usado para identificar o grupo?',
    '8. Como ocorre a absorção de água em briófitas? Qual a relação existente entre o tamanho da planta e a absorção de água?',
    '9. Realizar as atividades a seguir:',
    'a) Observar, ao natural, pelo menos um tipo de briófita com lupa. Fazer um relatório sobre o observado.',
    'b) Possuir uma coleção de imagens ou figuras de, pelo menos, 10 tipos diferentes de briófitas.']);
  PERFORM pg_temp.set_req('EN-107', '1', ARRAY[
    '1. Quais as principais características das bromélias?',
    '2. Por que as bromélias receberam esse nome e como elas eram chamadas?',
    '3. A que família pertencem as bromélias?',
    '4. Fazer um desenho de uma bromélia indicando suas partes.',
    '5. As bromélias epífitas podem ser consideradas como parasitas? Explicar.',
    '6. Qual o habitat das bromélias? As bromélias são nativas de quais continentes?',
    '7. Citar exemplos de espécies de bromélias:',
    'a) Epífitas;',
    'b) Rupestres;',
    'c) Terrestres;',
    'd) Ornamentais;',
    'e) Carnívoras;',
    'f) Comestíveis;',
    'g) Medicinais.',
    '8. Qual a relação entre as bromélias e os pernilongos e entre as bromélias e os anuros que vivem em florestas/matas?',
    '9. Por que a bromélia-imperial (Alcantarea imperialis) é tão resistente, a ponto de sobreviver mesmo se tiver suas raízes cortadas?',
    '10. A que tamanho pode chegar a maior bromélia do mundo?',
    '11. Quais são os principais polinizadores das bromélias?',
    '12. Quais os principais problemas no cultivo das bromélias e como solucioná-los?',
    '13. Por que não se deve coletar as bromélias na natureza? Qual a importância ecológica das bromélias?',
    '14. Fazer uma coleção de fotos de, no mínimo, 15 espécies diferentes de bromélias, com seus respectivos nomes populares e científicos.']);
  PERFORM pg_temp.set_req('EN-015', '1', ARRAY[
    '1. Citar as principais características de um cacto.',
    '2. A qual família pertencem os cactos?',
    '3. O que são os espinhos presentes nos cactos? Por que os cactos apresentam essas estruturas?',
    '4. Mencionar três utilidades dos cactos ao homem e/ou ao ambiente.',
    '5. Em que região há mais quantidade de cactos? Por quê?',
    '6. Qual a diferença e a relação entre cactos e suculentas?',
    '7. Esquematizar um cacto e identificar suas partes.',
    '8. Conhecer e identificar, ao natural ou em fotografias, 10 espécies de cactos.',
    '9. Cultivar, pelo menos, uma espécie de cacto durante um mês. Explicar os cuidados necessários.']);
  PERFORM pg_temp.set_req('EN-053', '3', ARRAY[
    '1. O que são suculentas?',
    '2. Identificar ao natural ou por fotografia cinco suculentas que não sejam cactos. Como elas se diferenciam dos cactos?',
    '3. Explicar os seguintes termos referentes aos cactos/suculentas:',
    'a) Aréola ou auréola;',
    'b) Cefálio;',
    'c) Cochonilha;',
    'd) Corimbo;',
    'e) Diurno;',
    'f) Epífita;',
    'g) Estolão ou estolho;',
    'h) Gloquídeo;',
    'i) Noturno;',
    'j) Panícula;',
    'k) Ramo;',
    'l) Zigomórfica.',
    '4. Quando as suculentas (incluindo os cactos) crescem, elas podem ser atacadas por doenças. Quais são as mais comuns e como você pode prevenir ou curar os problemas?',
    '5. Propagar, pelo menos, uma planta usando um dos seguintes métodos:',
    'a) A partir de sementes;',
    'b) Por estacas;',
    'c) Por enxertia.']);
  PERFORM pg_temp.set_req('EN-034', '1', ARRAY[
    '1. Dar o nome científico do cão doméstico.',
    '2. Citar cinco características peculiares da família Canidae.',
    '3. Identificar, a partir de fotografias/figuras, ou observação natural, cinco membros selvagens da família Canidae.',
    '4. Identificar, a partir de fotografias/figuras, ou observação natural, 15 diferentes raças de cães.',
    '5. Mencionar cinco contribuições da família dos cães ao homem.',
    '6. Escrever ou descrever oralmente a importância, para o homem, dos seguintes grupos de cães e mencionar algumas raças equivalentes:',
    'a) Cães-guia;',
    'b) Cães farejadores;',
    'c) Cães pastores;',
    'd) Cães companheiros para crianças;',
    'e) Cães guardas;',
    'f) Cães que auxiliam polícia e bombeiros em sua região.',
    '7. Dar o nome da menor e da maior raça de cães.',
    '8. Identificar, pessoalmente ou por fotografias/figuras, cinco cães que são classificados como "toy" (anões).',
    '9. Quais as duas raças de cão que têm a língua inteiramente azul ou preta?',
    '10. Qual a raça mais rápida?',
    '11. Quais cuidados deve-se tomar com os cães para que tenham uma vida saudável.',
    '12. Ajudar a cuidar de um cão por, pelo menos, um mês.',
    '13. Qual a importância das vacinas em cães domésticos?']);
  PERFORM pg_temp.set_req('EN-076', '2', ARRAY[
    '1. Explicar as diferenças entre o dromedário e o camelo-bactriano. Por que ambos são reconhecidos e importantes?',
    '2. Descrever as seguintes características dos camelos:',
    'a) Três utilidades que lhe são atribuídas;',
    'b) Quantidade de água que bebem;',
    'c) Três qualidades de sobrevivência;',
    'd) Procedência.',
    '3. Mencionar três camelos sul-americanos e analisar o seguinte:',
    'a) Região onde vivem;',
    'b) Utilidade que lhe é atribuída;',
    'c) Características físicas;',
    'd) Tipo de alimentação.',
    '4. Fazer uma pesquisa sobre a predação dos camelos sul-americanos. Por que esses animais estão em risco de extinção?',
    '5. Fazer um estudo do texto de Mateus 19:24 dando ênfase nas palavras de Jesus. Escrever um relatório do que você aprendeu com essa lição (usar comentários bíblicos para entender o contexto; é necessário ler todo o capítulo de Mateus 19).']);
  PERFORM pg_temp.set_req('EN-037', '2', ARRAY[
    '1. De que maneira a ordem dos cetáceos é diferente da maioria dos outros seres marinhos?',
    '2. Explicar a diferença entre baleias verdadeiras (misticetos) e baleias com dentes (odontocetos).',
    '3. De que formas as baleias e os golfinhos têm sido um benefício para o homem?',
    '4. Sabendo que as baleias são animais homeotérmicos (de sangue quente), assim como os seres humanos, explicar como as baleias que se reproduzem nas águas quentes dos trópicos também podem sobreviver nas águas geladas da Antártida, para onde elas vão para se alimentar.',
    '5. Escrever e ler para um grupo, ou contar de memória, a história de Jonas.',
    '6. Desenhar, com sucesso, uma baleia verdadeira e identificar onde ficam as seguintes partes do corpo:',
    'a) Barbatanas;',
    'b) Orifícios respiratórios (espiráculos);',
    'c) Nadadeira dorsal;',
    'd) Ouvido;',
    'e) Olho;',
    'f) Sulcos ventrais;',
    'g) Lobos caudais;',
    'h) Nadadeiras peitorais;',
    'i) Abertura genital;',
    'j) Intersecção dos lobos caudais;',
    'k) Pedúnculo caudal.',
    '7. Ser capaz de identificar, pelo menos, 15 espécies de cetáceos, ao vivo, por fotografia, ilustração ou documentário.']);
  PERFORM pg_temp.set_req('EN-099', '2', ARRAY[
    '1. Ter a especialidade de Astronomia.',
    '2. Quais são as três unidades de medida de distância astronômica classicamente utilizadas?',
    '3. Qual é o nome e o tamanho da galáxia em que vivemos? Qual é a galáxia mais próxima da nossa?',
    '4. O que é nuvem cósmica e qual a sua relação com a formação de novas estrelas e planetas?',
    '5. O que é a nuvem de Oort?',
    '6. Dar as seguintes características dos planetas do sistema solar:',
    'a) Revolução sideral;',
    'b) Gravidade relativa;',
    'c) Quantidade de luas.',
    '7. Qual é a importância dos meteoritos para o estudo do universo?',
    '8. Utilizando um telescópio (que pode ser caseiro ou construído a partir de um kit), observar o céu noturno e identificar os planetas visíveis.']);
  PERFORM pg_temp.set_req('EN-100', '1', ARRAY[
    '1. Quais são os nomes da ordem e da família das cigarras?',
    '2. Ilustrar o ciclo de vida da cigarra.',
    '3. Onde ficam localizados os aparelhos estridulatórios (órgãos sonoros) das cigarras?',
    '4. Onde ficam localizados os ouvidos das cigarras?',
    '5. Responder as seguintes perguntas:',
    'a) De qual idioma é derivada a palavra cigarra?',
    'b) Onde a cigarra passa a maior parte da sua vida?',
    'c) Quais os principais predadores da cigarra enquanto ela vive no subsolo?',
    'd) Quantos anos, em média, as cigarras vivem?',
    'e) Do que as cigarras se alimentam?',
    'f) Qual o principal motivo do canto das cigarras?',
    'g) É correto afirmar que apenas o macho da cigarra canta? Por quê?',
    '6. Como as cigarras podem causar prejuízos nas lavouras? Que animal pode ajudar no combate às ninfas das cigarras?',
    '7. Apresentar fotos das seguintes espécies de cigarras:',
    'a) Quesada gigas;',
    'b) Neotibicen linnei.',
    '8. Que relação existe entre a vida da cigarra e o texto de Salmo 150:6?']);
  PERFORM pg_temp.set_req('EN-077', '2', ARRAY[
    '1. Dizer quais são as três partes de uma célula eucarionte e citar suas principais funções.',
    '2. O que é uma célula procarionte?',
    '3. Citar três diferenças entre uma célula animal e uma célula vegetal.',
    '4. O que são células-tronco? Qual sua importância?',
    '5. Citar três funções da membrana plasmática.',
    '6. Explicar as seguintes formas de permeabilidade seletiva: osmose e difusão.',
    '7. Explicar as seguintes formas de permeabilidade não seletiva: fagocitose e pinocitose.',
    '8. O que é transporte ativo e transporte passivo?',
    '9. Quais as quatro partes de um núcleo celular? Qual a importância de cada um?',
    '10. Citar as funções das seguintes organelas citoplasmáticas:',
    'a) Mitocôndria;',
    'b) Centríolo;',
    'c) Complexo de Golgi;',
    'd) Retículo endoplasmático rugoso;',
    'e) Retículo endoplasmático liso;',
    'f) Lisossomo;',
    'g) Ribossomo;',
    'h) Peroxissomo.',
    '11. Qual a importância dos cílios e dos flagelos?',
    '12. Identificar, por meio de fotos ou desenhos, cinco diferentes tipos de células (como muscular, óssea, cartilaginosa, adiposa, leucócito, hemácia, neurônio, etc.).']);
  PERFORM pg_temp.set_req('EN-016', '2', ARRAY[
    '1. Explicar como os seguintes fenômenos são formados: neblina, chuva, orvalho, neve, granizo e geada.',
    '2. Identificar no céu ou em fotos, os seguintes tipos de nuvens: cirros, cúmulos, estratos e nimbos. Que tipo de clima está associado a cada uma delas?',
    '3. Explicar como funciona um termômetro de mercúrio, barômetro de mercúrio, barômetro aneroide e um pluviômetro.',
    '4. Por que é possível haver chuva de um lado de uma montanha e estar seco do outro lado? Dar uma ilustração em seu país ou região.',
    'a) Por que é mais fresco e úmido nas montanhas do que nos vales?',
    'b) De que direção geralmente vêm a chuva e o tempo bom em sua região?',
    '5. Demonstrar, com ajuda de um diagrama, como a relação entre a Terra e o Sol produz as diferentes estações.',
    '6. O que causa os raios e trovões? Quais os diferentes tipos de raios existentes?',
    '7. Com auxílio de um diagrama, demonstrar o que é convecção e qual é sua relação com o vento.',
    '8. Explicar como radares, satélites e computadores são usados na previsão do tempo.',
    '9. Explicar como os itens a seguir podem afetar o tempo:',
    'a) Correntes de jato;',
    'b) Erupções vulcânicas.',
    '10. Fazer um desenho mostrando o ciclo da água na meteorologia.',
    '11. Fazer um cata-vento simples ou um pluviômetro.',
    '12. Manter um quadro meteorológico durante uma semana e registrar a leitura do tempo em intervalos de 12 horas. Incluir o seguinte:',
    'a) Temperatura;',
    'b) Umidade (orvalho, neblina, chuva, geada ou neve);',
    'c) Formação de nuvens;',
    'd) Direção do vento.',
    '13. Completar a leitura das seguintes passagens: Gênesis 1, Jonas 1 e 2, e Mateus 8:23-27. Após a leitura, participar de um debate sobre o porquê da criação do clima, qual a relação entre o clima e a vontade de Deus e como o clima pode ser usado por Deus como ferramenta de Salvação.']);
  PERFORM pg_temp.set_req('EN-028', '3', ARRAY[
    '1. Ter a especialidade de Climatologia.',
    '2. Explicar o que são áreas ciclonais e anticiclonais e mostrar quais as mudanças que elas provocam no tempo.',
    '3. O que são frentes frias e frentes quentes? Como se movem e que condições meteorológicas produzem?',
    '4. Explicar os seguintes fenômenos meteorológicos: vento adiabático, ventos alísios, zona de calmaria, furacão, linha de instabilidade, tornado e nevasca.',
    '5. Explicar a ação dos registros termométricos, barográficos, higrométricos e anemométricos.',
    '6. Ler corretamente um mapa do tempo diário, como o publicado pelo Serviço Meteorológico, explicando os símbolos e dizendo como as previsões são feitas.',
    '7. O que significa umidade relativa do ar e ponto de condensação?',
    '8. Desenhar um corte transversal da atmosfera, mostrando suas cinco camadas e descrevendo cada uma delas.',
    '9. Fazer um diagrama do tempo durante três semanas. Incluir o seguinte:',
    'a) Precipitação pluviométrica (conseguir esta informação em seu próprio pluviômetro caseiro ou a partir de relatórios oficiais);',
    'b) Leitura de barômetro;',
    'c) Formação de nuvens;',
    'd) Direção e velocidade dos ventos;',
    'e) Temperaturas (mínima e máxima);',
    'f) Umidade (orvalho, neblina, chuva, geada ou neve);',
    'g) Previsões de tempo e comparação com a realidade.',
    '10. Explicar o que são os fenômenos El Niño e La Niña e quais são as principais consequências para a América do Sul.',
    '11. Realizar uma pesquisa sobre as diferenças entre os ventos anabático e catabático. Descobrir as características peculiares de cada um, como são formados e a que tipo de processo termodinâmico cada um está associado.',
    '12. Debater o seguinte junto ao grupo da especialidade de Climatologia (básico ou avançado):',
    'a) Alguns benefícios para o homem adquiridos através da criação do clima;',
    'b) Qual a relação entre o clima e a vontade de Deus;',
    'c) Quais os efeitos do pecado sobre o clima;',
    'd) Como o clima pode ser usado por Deus, como ferramenta de Salvação.']);
  PERFORM pg_temp.set_req('EN-101', '1', ARRAY[
    '1. O que é compostagem? Qual a importância da compostagem para as grandes cidades?',
    '2. Como acontece o processo da compostagem? Qual o papel dos microrganismos nesse processo? Qual a importância da aeração adequada?',
    '3. Ao realizar uma compostagem doméstica, quais elementos são essenciais para que a decomposição do resíduo aconteça de forma correta?',
    '4. Quais elementos não devem fazer parte de uma composteira caseira?',
    '5. Montar uma compostagem doméstica utilizando materiais reutilizáveis e apresentar relatório fotográfico com todo o processo desenvolvido por no mínimo 45 dias.',
    '6. Citar duas formas de como se pode acelerar o processo de compostagem.',
    '7. Relatar a utilidade do composto formado após o processo de compostagem.',
    '8. Explicar como utilizar o chorume coletado durante o processo.']);
  PERFORM pg_temp.set_req('EN-046', '3', ARRAY[
    '1. Explicar a diferença entre ecologia e conservação ambiental.',
    '2. Escrever uma redação com, no mínimo, 500 palavras com o tema: O aumento da população humana e como isso é uma ameaça à sua própria existência na Terra.',
    '3. O que significa a expressão morte de um lago ou rio? Há algum lago ou rio em sua região ou cidade que é classificado como morto?',
    '4. Realizar um estudo num pequeno riacho ou corpo hídrico que passe dentro ou perto da sua cidade. Apresentar um relatório de, no mínimo, 300 palavras sobre a sua observação nos seguintes itens:',
    'Sinais de pureza:',
    'a) Abundância de pequenos peixes;',
    'b) Água visualmente clara e com odor agradável;',
    'c) Margens do riacho, ou corpo hídrico, cobertas de vegetação até perto da água;',
    'd) Pequenas quantidades de microalgas verdes na água;',
    'e) Existência de algumas plantas aquáticas como a taboa, erva do campo ou pontedéria;',
    'f) Existência de animais aquáticos (como lagostins sob as pedras, tartarugas, etc.);',
    'g) Crescimento de ervas daninhas na areia das margens, indicando um nível de água relativamente estável.',
    'Sinais de deterioração e morte:',
    'a) Presença de grandes massas de microalga azul-verde;',
    'b) Margens marcadas por nível de água durante as chuvas;',
    'c) Água com odor pútrido;',
    'd) Presença de espuma de detergentes/agentes químicos;',
    'e) Lixo nas margens e dentro da água, perto das margens;',
    'f) Água repleta de sedimentos;',
    'g) Ausência de insetos aquáticos e peixes;',
    'h) Presença de esgoto;',
    'i) Presença de óleo na superfície da água;',
    'j) Resíduos jogados nas águas do riacho ou corpo hídrico por depósitos ou fábricas.',
    '5. Após a investigação do requisito anterior, realizar um dos itens abaixo:',
    'a) Se o riacho ou corpo hídrico demonstrar sinais de pureza, descrever quais são as medidas que devem ser tomadas para a sua preservação;',
    'b) Se o riacho ou corpo hídrico demonstrar sinais de deterioração, fazer, pelo menos, dois dos itens abaixo:',
    '• Realizar um projeto comunitário para despoluí-lo;',
    '• Em grupo, recolher o lixo das margens do riacho ou corpo hídrico;',
    '• Conseguir o fornecimento de caminhões ou pick-ups para ajudar na despoluição;',
    '• Descobrir qual a posição e projetos que sua prefeitura/administração tem para despoluir este local e cobrar as providências.',
    '6. Realizar um dos itens abaixo:',
    'a) Visitar uma usina ou aterro sanitário. Nesta visita, realizar os itens abaixo:',
    '• Desenhar um diagrama detalhado do que acontece com o lixo líquido e sólido, do momento em que entram na usina até saírem;',
    '• Em que estado sai o lixo desta usina?',
    '• Há qualquer outra utilidade para este lixo?',
    'b) Visitar um depósito de lixo e ver como o lixo é tratado. Descobrir:',
    '• Quantas toneladas de lixo são jogadas diariamente;',
    '• Que tentativas são feitas para se reciclar parte desse lixo;',
    '• Parte do lixo é queimada ou é todo enterrado?',
    '• O que acontece com os carros abandonados que não servem mais para nada em sua região.',
    'c) Visitar uma estação de tratamento de água:',
    '• Construir um diagrama dos passos para a purificação da água, do momento em que entra na usina até sair para ser distribuído em residências e estabelecimentos comerciais;',
    '• Descobrir como você e sua comunidade podem preservar e reduzir o consumo de água;',
    '• Fazer uma campanha com seu clube/unidade para evitar o desperdício de água.',
    'd) Ter as especialidades de Reciclagem e Reciclagem - avançado.']);
  PERFORM pg_temp.set_req('EN-078', '2', ARRAY[
    '1. Citar, pelo menos, quatro características de um crustáceo.',
    '2. O que é um exoesqueleto?',
    '3. A qual filo pertence este grupo?',
    '4. Como é dividido o corpo destes animais?',
    '5. Em qual livro da Bíblia, capítulo e versículo encontramos informações para não nos alimentarmos de crustáceos?',
    '6. Como podemos diferenciar um siri de um caranguejo? Em quais ambientes encontramos esses animais?',
    '7. Citar um exemplo de crustáceo terrestre.',
    '8. Como podemos diferenciar entre siris (ou caranguejos) machos e fêmeas? Por que isso é importante?',
    '9. Qual a importância dos microcrustáceos para o ambiente?',
    '10. Realizar dois dos itens a seguir, apresentado relatório ilustrado:',
    'a) Por meio de imagens/fotografias/desenho, indicar as principais partes morfológicas de um camarão;',
    'b) Assistir a um vídeo sobre diversas espécies de crustáceos e esquematizar, pelo menos, duas espécies diferentes;',
    'c) Fazer uma observação de, pelo menos, três espécies de crustáceos em seus ambientes naturais, durante um período mínimo de 10 minutos de observação para cada uma das espécies;',
    'd) Conseguir diferenciar entre caranguejo e siri e saber diferenciar entre macho e fêmea.',
    '11. Ser capaz de identificar, pessoalmente ou através de imagens, os seguintes animais:',
    'a) Cracas;',
    'b) Paguro (ermitão);',
    'c) Tatu de jardim;',
    'd) Lagosta;',
    'e) Camarão;',
    'f) Caranguejo;',
    'g) Siri.']);
  PERFORM pg_temp.set_req('EN-079', '1', ARRAY[
    '1. Qual o significado do termo dinossauro? Quem usou este termo pela primeira vez?',
    '2. Quais os indícios de que estas criaturas realmente existiram?',
    '3. Explicar o surgimento e desaparecimento dos dinossauros de acordo com as seguintes teorias:',
    'a) Criacionista;',
    'b) Evolucionista.',
    '4. Quais as evidências que apontam para a morte dos dinossauros através do dilúvio? Identificar e listar trechos da Bíblia que falem sobre a criação de répteis.',
    '5. Explicar por que os répteis marinhos e voadores não são considerados dinossauros. Dar exemplos destas criaturas.',
    '6. De que maneira os dinossauros nasciam? Em que ano e onde isso foi comprovado?',
    '7. Como supostamente seria a pele dos dinossauros?',
    '8. Definir e caracterizar cada um dos grupos de dinossauros abaixo:',
    'a) Saurópodes;',
    'b) Terópodes;',
    'c) Ceratopsídeos;',
    'd) Anquilosaurídeos.',
    '9. Fazer um diagrama da suposta cadeia alimentar dos dinossauros. Quem supostamente está no topo? Por que este dinossauro supostamente se encontra lá?',
    '10. O que são sauropodomorfos? Quais os dois grupos em que se dividem?',
    '11. Quem é considerado o rei dos dinossauros?',
    '12. Escolher um dinossauro e escrever, no mínimo, 150 palavras sobre ele, onde seus fósseis foram achados, que hábitos possuía, como se alimentava e tudo o que conseguir saber sobre este animal.',
    '13. Fazer uma coleção de 10 imagens de fósseis de dinossauros, identificando:',
    'a) Nome;',
    'b) Local onde o fóssil foi encontrado;',
    'c) Ano da descoberta;',
    'd) Características gerais.']);
  PERFORM pg_temp.set_req('EN-044', '2', ARRAY[
    '1. Saber o significado dos seguintes termos:',
    'a) Ecologia;',
    'b) Plâncton;',
    'c) Populações;',
    'd) Comunidade;',
    'e) Ecossistemas;',
    'f) Conservação;',
    'g) Cadeia alimentar;',
    'h) Comunidade clímax;',
    'i) Comensalismo;',
    'j) Autotrofismo;',
    'k) Sucessão ecológica;',
    'l) Bioma;',
    'm) Habitat.',
    '2. O que é uma pirâmide ecológica? Por que ela tem esse formato? Escolher um mamífero, um pássaro, um réptil e um anfíbio comuns na região em que você mora e construir para cada um deles um diagrama de sua pirâmide ecológica.',
    '3. Definir o que é ecossistema. Falar sobre os fatores biológicos e físicos que o mantêm equilibrado.',
    '4. Utilizando-se de fotografias ou figuras, elaborar um cartaz ou quadro formando um diagrama ilustrando um ecossistema de um pequeno lago de água doce.',
    '5. Pesquisar sobre como se faz a coleta de lixo em seu bairro e qual o destino do lixo coletado. Elaborar um relatório com as informações de quanto lixo sua família joga por dia e como poderiam lidar melhor com isto.',
    '6. Pesquisar nos jornais ou em algum site especializado, por uma semana, os níveis de poluição atmosférica de uma cidade grande (a mais perto da sua, se você não morar numa cidade grande). Fazer um gráfico demonstrando a curva deste nível durante a semana. Descobrir o que causa os pontos altos de sua curva do gráfico.',
    '7. Relacionar 10 maneiras de trabalhar ativamente em favor do meio ambiente de sua comunidade e cidade. Colocar quatro delas em prática.',
    '8. Pesquisar um texto do Espírito de Profecia e um texto bíblico relacionados à ecologia. Apresentar uma explicação sobre sua relevância e aplicação aos nossos dias.']);
  PERFORM pg_temp.set_req('EN-045', '3', ARRAY[
    'Nota: para esta especialidade, é recomendável o acompanhamento de um instrutor. Falar com seu líder de desbravadores ou instrutor antes de começar o requisito 8.',
    '1. Ter a especialidade de Ecologia.',
    '2. Definir os seguintes termos:',
    'a) Matéria-prima;',
    'b) Fotossíntese;',
    'c) Quimiossíntese;',
    'd) Autotrófico;',
    'e) Heterotrófico;',
    'f) Equilíbrio ecológico;',
    'g) Saprófagos;',
    'h) Decompositores;',
    'i) Produtor;',
    'j) Consumidor;',
    'k) Fator limitante.',
    '3. Explicar o que são níveis tróficos e dar exemplos de organismos para cada nível.',
    '4. Citar a primeira e a segunda leis da termodinâmica e explicar como são importantes para a ecologia.',
    '5. Apresentar um diagrama que contenha os passos básicos do fluxo de energia através do sistema biótico de um ecossistema. Começar o diagrama pelo sol.',
    '6. Elaborar um diagrama dos três tipos de pirâmides ecológicas existentes na rede alimentar. Apresentar, pelo menos, um exemplo em cada camada da pirâmide.',
    '7. Explicar o que são os ciclos bioquímicos e fazer um diagrama sobre todos os componentes básicos do ciclo.',
    '8. Cumprir um dos itens abaixo:',
    'a) Escolher uma comunidade biológica de sua região, como, por exemplo, uma floresta ou bosque, pântano, lago ou açude, pasto ou campo, desfiladeiro ou riacho, etc., que esteja de alguma forma alterado ecologicamente. Descrever o local, incluindo como se deu e até que ponto o equilíbrio foi alterado. Depois, apresentar recomendações sobre como aquela comunidade pode ser melhorada e direcionar seus esforços para o acompanhamento e ajuda no trabalho de melhoria;',
    'b) Participar ativamente em um projeto ecológico. Isto pode ser feito individualmente ou em grupo. Elaborar um esboço do projeto e seus objetivos, bem como relatar detalhadamente a parte que você desempenhou no mesmo.',
    '9. Encontrar um trecho do Espírito de Profecia e um texto bíblico, diferentes dos utilizados na especialidade Ecologia, relacionados à ecologia e explicar sua relevância e aplicação aos nossos dias.']);
  PERFORM pg_temp.set_req('EN-081', '2', ARRAY[
    '1. O que são energias renováveis? Qual é o seu papel na conservação do meio ambiente?',
    '2. Definir os seguintes tipos de energia, citando as vantagens e desvantagens para cada um deles:',
    'a) Energia solar;',
    'b) Energia eólica.',
    '2. (continuação)',
    'c) Hidrogênio;',
    'd) Biocombustíveis;',
    'e) Energia hidráulica;',
    'f) Energia maremotriz;',
    'g) Energia azul;',
    'h) Energia geotérmica;',
    'i) Biomassa;',
    'j) Biogás.',
    '3. O que é energia não renovável? Como esse tipo de energia pode prejudicar o meio ambiente?',
    '4. Qual o papel da energia solar na obtenção de outros tipos de energia?',
    '5. Para algumas energias renováveis a localização da usina é um fator de grande influência no rendimento. Como essa localização pode influenciar no rendimento?',
    '6. Que impactos sociais e ambientais podem ser causados pela implementação de usinas de algumas energias renováveis?',
    '7. Escolher uma usina de uma energia renovável que esteja em atividade e fazer um relatório contendo:',
    'a) Nome e localização;',
    'b) Capacidade de geração de energia;',
    'c) Tipo de energia;',
    'd) Vantagens e desvantagens do tipo de energia;',
    'e) Impacto ambiental e social da implementação.',
    '8. Pesquisar e praticar, pelo menos, três formas de economizar energia em seu lar, escola ou trabalho.',
    '9. Segundo Apocalipse 11:18, qual é o futuro dos que destroem a terra?']);
  PERFORM pg_temp.set_req('EN-080', '2', ARRAY[
    '1. O que significa a palavra Echinodermata, nome que caracteriza o filo dos equinodermos?',
    '2. Citar quatro características pertencentes ao filo Echinodermata.',
    '3. Qual tipo de simetria os equinodermos possuem? O que isso significa?',
    '4. Em qual ambiente podemos encontrar os equinodermos?',
    '5. Como as estrelas do mar se alimentam?',
    '6. Citar principais características e exemplos das cinco classes:',
    'a) Asteroidea;',
    'b) Echinoidea;',
    'c) Ophiuroidea;',
    'd) Holothuroidea;',
    'e) Crinoidea.',
    '7. O que fazer em caso de acidente com ouriços?',
    '8. Identificar, esquematizar e explicar a função de:',
    'a) Em estrelas do mar:',
    '• Pódios/pés ambulacrários;',
    '• Placa madrepórica;',
    '• Boca;',
    '• Ânus.',
    'b) Em ouriços do mar:',
    '• Lanterna de Aristóteles;',
    '• Espinhos;',
    '• Boca;',
    '• Endoesqueleto.',
    '9. Identificar 10 espécies por figuras, fotos ou pessoalmente. Além do nome popular, citar o nome científico e a classe.']);
  PERFORM pg_temp.set_req('EN-038', '2', ARRAY[
    '1. Relacionar 25 ervas culinárias e o uso de cada uma.',
    '2. Relacionar 25 ervas medicinais e o uso de cada uma.',
    '3. Preparar um prato e uma bebida (suco ou chá) usando ervas.',
    '4. Usando ervas conhecidas da sua região, fazer dois dos produtos a seguir:',
    'a) Creme;',
    'b) Almofada ou travesseiro (com enchimento de ervas);',
    'c) Sabonete;',
    'd) Papel;',
    'e) Vela decorativa;',
    'f) Sachê.',
    '5. Fazer um pote decorativo com mistura de ervas secas.',
    '6. Fazer uma caixa com substâncias aromáticas.',
    '7. Citar e identificar cinco ervas silvestres que crescem na região que você mora.',
    '8. Citar cinco ervas que podem ser usadas como tintura e mencionar a cor que produzem.',
    '9. Citar cinco ervas que podem ser usadas no controle de insetos.',
    '10. Cultivar cinco ervas culinárias durante, pelo menos, 3 meses.',
    '11. Citar cinco ervas que atraem abelhas.',
    '12. Citar cinco ervas mencionadas na Bíblia. Mencionar os textos bíblicos onde podem ser encontradas e quais as finalidades de seu uso.']);
  PERFORM pg_temp.set_req('EN-082', '1', ARRAY[
    '1. O que é um estuário?',
    '2. Listar três tipos de estuário e dar um exemplo para cada tipo.',
    '3. Como é definido o comprimento de um estuário?',
    '4. Que fatores tornam o estuário um dos biomas mais vulneráveis do mundo?',
    '5. Explicar as razões da grande produtividade e diversidade ecológica nos estuários.',
    '6. Qual a importância dos estuários para o equilíbrio do ecossistema?',
    '7. Citar, ao menos, um processo de formação de estuário.',
    '8. Conhecer, no mínimo, três benefícios dos estuários aos homens.',
    '9. Em estuários existe a presença de água doce e salgada. Qual o nome dado aos peixes que têm a capacidade de sobreviver nesses dois ambientes? Citar cinco exemplos.',
    '10. Listar três pássaros e um mamífero comuns nos estuários de sua região ou país.',
    '11. Citar, ao menos, dois fatores que indicam a presença da vegetação de mangue nos estuários tropicais.',
    '12. Listar, ao menos, três gêneros de mangue comuns em estuários tropicais.',
    '13. Citar cinco atividades recreativas que podem ser realizadas em regiões estuarinas, sem lhes causar dano ou prejuízo.',
    '14. Qual o estuário mais próximo de sua cidade?',
    '15. Completar uma das seguintes atividades:',
    'a) Fazer uma visita a um estuário. Durante a visita, observar sinais de conservação ou de degradação desse ambiente. Em conjunto com o grupo, sob a orientação de seu líder, organizar um projeto de preservação desse estuário e colocar o projeto em prática.',
    'b) Ler um livro, ou assistir a um vídeo sobre estuários. Realizar uma pesquisa e escrever um relatório sobre oito diferentes estuários ao redor do mundo. Nessa pesquisa devem constar: nome do estuário, localização, estado de conservação atual e possíveis motivos para esse estado, fotos, etc. Citar as fontes de pesquisa.']);
  PERFORM pg_temp.set_req('EN-039', '2', ARRAY[
    '1. Quantas espécies diferentes de eucaliptos existem em seu país?',
    '2. Qual a origem do nome eucalipto?',
    '3. Os eucaliptos pertencem a que família?',
    '4. Em que partes do mundo os eucaliptos podem ser encontrados? Em quais dos países listados eles são considerados plantas nativas?',
    '5. Responder o seguinte:',
    'a) Qual país tem as angiospermas mais altas?',
    'b) Onde elas crescem?',
    'c) Que altura elas alcançam?',
    '6. Como os eucaliptos estão adaptados a:',
    'a) Frequentes incêndios florestais?',
    'b) Regiões áridas?',
    '7. Responder o seguinte, com relação à extração de óleo:',
    'a) De que espécies se extraem óleos de eucalipto?',
    'b) Existe extração de óleo em seu país? Que espécie é utilizada? Onde esse processo é realizado em seu país?',
    'c) Que finalidades os óleos de eucalipto possuem?',
    '8. Que utilidades o eucalipto possui para o homem? Além de seu uso, que outros benefícios ele pode trazer ao homem e ao meio ambiente?',
    '9. Fazer um dos seguintes:',
    'a) Coletar, prensar e identificar ramos de cinco espécies diferentes de eucaliptos. Anotar quaisquer características importantes para a identificação e ser capaz de identificar outros indivíduos das espécies coletadas.',
    'b) Desenhar ou fotografar 10 espécies diferentes de eucaliptos, mostrando os ramos e outras características importantes para a identificação e ser capaz de identificar outros indivíduos das espécies retratadas.']);
  PERFORM pg_temp.set_req('EN-008', '1', ARRAY[
    '1. Que características podem ser usadas para diferenciar mariposas e borboletas?',
    '2. Definir os seguintes termos:',
    'a) Antena;',
    'b) Ovo;',
    'c) Larva;',
    'd) Pupa;',
    'e) Crisálida;',
    'f) Casulo;',
    'g) Imago.',
    '3. Distinguir três espécies diferentes a partir de seus casulos.',
    '4. O que é o pó colorido que fica grudado nas mãos ao pegar nas asas de uma borboleta ou mariposa? Examinar o pó da asa de uma borboleta ou mariposa com lentes de aumento e descrever o que foi observado.',
    '5. Que benefícios as mariposas e borboletas trazem ao homem e ao meio ambiente?',
    '6. Que danos as mariposas e borboletas podem causar? Em que estágio da vida elas podem causar danos? Citar três exemplos de mariposas e/ou borboletas que causem danos.',
    '7. Que borboleta é famosa por seu ciclo migratório?',
    '8. Completar um dos seguintes:',
    'a) Identificar por meio de fotografias 20 espécies de mariposas e borboletas. Identificar a ordem e a família de cada espécime;',
    'b) Fazer desenhos ou pinturas coloridas de 15 espécies de mariposas e borboletas. Os desenhos ou pinturas precisam ser do tamanho natural ou maior e em coloração natural. Identificar a ordem e a família dos espécimes retratados.',
    '9. Descrever o ciclo de vida de uma mariposa ou borboleta e aprender uma lição relacionada com o batismo.']);
  PERFORM pg_temp.set_req('EN-061', '2', ARRAY[
    '1. O que são marsupiais? Quais as diferenças entre eles e os outros mamíferos?',
    '2. Distinguir entre os mamíferos: placentários, marsupiais e monotremados.',
    '3. Explicar a diferença entre a reprodução dos monotremados, dos marsupiais e dos mamíferos verdadeiros (ou seja, placentários).',
    '4. Descrever a distribuição, habitat, dieta, comportamento reprodutivo, assim como quaisquer outras informações interessantes de uma espécie de cada uma das sete ordens de marsupiais e das duas de monotremados.',
    '5. Descrever a distribuição, habitat, dieta, comportamento reprodutivo, assim como quaisquer outras informações interessantes de quatro espécies que ocorram em seu país.',
    '6. Dizer por que os marsupiais são considerados tão importantes na Austrália.',
    '7. Fazer um dos seguintes:',
    'a) Observar um marsupial (ou um grupo de marsupiais) em seu habitat natural. Escrever um relatório de no mínimo 100 palavras, sobre as suas observações;',
    'b) Visitar um museu de história natural, zoológico, etc. Escrever um relatório de no mínimo 100 palavras sobre os marsupiais que foram observados;',
    'c) Falar por pelo menos três minutos para um grupo de pessoas sobre marsupiais ou um marsupial em particular;',
    'd) Guiar (ou ajudar a guiar) um grupo de desbravadores em uma visita a um museu ou zoológico onde existam marsupiais.',
    '8. Explicar a necessidade de proteger os marsupiais de seu país.']);
  PERFORM pg_temp.set_req('EN-102', '1', ARRAY[
    '1. O que é mimetismo, o que é camuflagem e para o que servem?',
    '2. Citar, pelo menos, um exemplo de mimetismo para cada:',
    'a) Insetos;',
    'b) Aves;',
    'c) Répteis.',
    '3. Dar, pelo menos, um exemplo de camuflagem para cada:',
    'a) Insetos;',
    'b) Répteis;',
    'c) Animais marinhos.',
    '4. Responder as seguintes perguntas:',
    'a) Qual a vantagem da cobra coral-falsa em apresentar cores praticamente idênticas às da coral-verdadeira?',
    'b) No mundo animal, quais os reis da camuflagem na terra e no mar?',
    'c) Qual a forma dos ovos do bicho-pau (Phibalosoma phyllinum)?',
    'd) Como é o andar dos insetos especialistas em mimetismo?',
    'e) Quais as vantagens e desvantagens dos insetos que se assemelham a folhas?',
    'f) Como o inseto-assassino (Acanthaspis petax) faz para se esconder de predadores?',
    '5. Dar exemplos de animais que apresentam características contrárias ao mimetismo, e explicar por que isso acontece na natureza.',
    '6. Ilustrar o mimetismo das seguintes espécies:',
    'a) Louva-a-deus orquídea (Hymenopus coronatus);',
    'b) Urutau-comum (Nyctibius griseus);',
    'c) Sapo-de-chifres ou sapo-folha (Proceratophrys boiei).',
    '7. Ver vídeos ou fotografias/imagens que registrem a camuflagem das seguintes espécies:',
    'a) Polvo-mímico (Mimic octopus);',
    'b) Goniurellia tridens;',
    'c) Jequitiranaboia (Fulgora laternaria).']);
  PERFORM pg_temp.set_req('EN-042', '1', ARRAY[
    '1. Definir as características de uma orquídea.',
    '2. Quais são os dois principais grupos de orquídeas? Dar o nome e mostrar exemplos de cada, a partir das próprias plantas ou de fotografias.',
    '3. Quais as diferenças entre as orquídeas epífitas, rupícolas, terrestres e humícolas? Citar exemplos.',
    '4. Discorrer sobre a distribuição geográfica das orquídeas. Qual a sua origem? Fazer uma referência especial às espécies comuns em sua região.',
    '5. Citar o principal gênero de orquídeas cultivadas. Identificar três espécies pessoalmente ou por fotografias.',
    '6. Quais as principais utilidades das orquídeas? Que orquídea é mais popular comercialmente falando?',
    '7. Discutir os seguintes pontos a serem observados no cultivo de orquídeas:',
    'a) Luz;',
    'b) Temperatura;',
    'c) Umidade;',
    'd) Nutrientes;',
    'e) Ventilação;',
    'f) Vasos e substratos.',
    '8. Cultivar uma orquídea durante, no mínimo, um mês.',
    '9. Identificar, por meio de imagens, fotos ou pessoalmente, 10 espécies de orquídeas.']);
  PERFORM pg_temp.set_req('EN-065', '1', ARRAY[
    '1. Explicar o seguinte:',
    'a) O que é um verme;',
    'b) Onde os vermes vivem;',
    'c) O que os vermes comem;',
    'd) Em que reinos os vermes são encontrados.',
    '2. O que significam os termos vida livre e parasita?',
    '3. Dar o nome dos três principais filos (segunda maior categoria de classificação) que contêm vermes e descrevê-los. Quais são de vida livre e quais são parasitas?',
    '4. Responder as seguintes perguntas sobre minhocas:',
    'a) Onde elas vivem?',
    'b) O que elas comem?',
    'c) Como elas são benéficas ao ser humano?',
    'd) Qual o tamanho mínimo e máximo que elas podem ter?',
    'e) Quantas espécies existem?',
    'f) O que é o clitelo?',
    '5. Encontrar uma minhoca e fazer o seguinte:',
    'a) Ser capaz de distinguir as seguintes partes: extremidade anterior, extremidade posterior e clitelo;',
    'b) Observar e descrever como ela se move;',
    'c) Observar quanto tempo ela leva para percorrer 10 cm.',
    '6. Responder as seguintes perguntas sobre sanguessugas:',
    'a) Onde elas vivem?',
    'b) O que elas comem?',
    'c) Como elas são prejudiciais ao ser humano?']);
  PERFORM pg_temp.set_req('EN-066', '2', ARRAY[
    '1. Ter a especialidade de Vermes.',
    '2. Descrever as três principais classes de platelmintos.',
    '3. Dar um exemplo de nematoide e descrever seu ciclo de vida.',
    '4. Quais são as três principais classes de anelídeos? Como eles se movem?',
    '5. Fazer o seguinte:',
    'a) Distinguir entre as seguintes estruturas corporais: celomados, pseudocelomados e acelomados;',
    'b) Que estruturas corporais são comuns em cada um dos três filos de vermes?',
    '6. Completar um dos itens a seguir:',
    'a) A partir do que você aprendeu sobre os vermes, fazer uma apresentação sobre por que a disponibilidade de água potável é tão importante para a saúde humana, especialmente em países em desenvolvimento;',
    'b) Organizar uma angariação de fundos para apoiar alguma organização que trabalhe para fornecer água potável para países subdesenvolvidos.',
    '7. Escrever uma lição espiritual sobre a água viva da Bíblia.']);
  PERFORM pg_temp.set_req('EN-095', '3', ARRAY[
    '1. O que significa a palavra vírus? Explicar por que há uma controvérsia se ele é um ser vivo ou não.',
    '2. Citar as características distintivas dos vírus e por que eles não são incluídos em nenhum reino.',
    '3. Citar algumas formas morfológicas de vírus e dar exemplos.',
    '4. Descrever as formas de replicação viral e como pode ocorrer a diferenciação genética que promove as mutações e resistência viral.',
    '5. Diferenciar as seguintes doenças exantemáticas:',
    'a) Rubéola;',
    'b) Sarampo;',
    'c) Catapora (Varicela).',
    '6. Escolher três das doenças virais abaixo e descrever a forma de contágio, os sintomas e formas de prevenção:',
    'a) Raiva;',
    'b) Herpes;',
    'c) AIDS/SIDA;',
    'd) Caxumba;',
    'e) Poliomielite;',
    'f) Meningite;',
    'g) Hepatite;',
    'h) Dengue;',
    'i) Covid-19.',
    '7. Diferenciar gripe e resfriado. Por que o vírus Influenza causa epidemias periódicas (como a gripe espanhola, gripe aviária, gripe A, etc.)?',
    '8. Qual a diferença entre vírus e príon? Citar uma doença causada por um príon.',
    '9. Explicar a importância das vacinas no combate aos vírus. Como elas funcionam?',
    '10. Alguma doença viral já foi erradicada? Por que é tão difícil o tratamento de doenças virais?',
    '11. Fazer um breve relatório sobre uma pandemia viral e o impacto que ela causou ao mundo.']);
  PERFORM pg_temp.set_req('EN-106', '2', ARRAY[
    '1. O que é vulcanismo? Ilustrar o ciclo natural dos vulcões.',
    '2. Desenhar um diagrama da anatomia de um vulcão.',
    '3. Qual a relação entre o vulcanismo e a tectônica de placas?',
    '4. Definir os seguintes termos:',
    'a) Magma;',
    'b) Lava;',
    'c) Ponto quente (hotspot);',
    'd) Fluxo piroclástico;',
    'e) Rocha ígnea;',
    'f) Xenólito;',
    'g) Dique;',
    'h) Estratovulcões;',
    'i) Vulcões-escudo;',
    'j) Caldeira;',
    'k) Necks;',
    'l) Lahar;',
    'm) Círculo de fogo.']);
  PERFORM pg_temp.set_req('HD-001', '2', ARRAY[
    '1. Saber operar devidamente o tipo de fogão que há em sua casa. Saber como prevenir pequenos incêndios por óleo ou gordura em seu fogão e saber como apagá-los. Conhecer as medidas de segurança enquanto estiver cozinhando, incluindo a preocupação com crianças pequenas.',
    '2. Saber como usar devidamente utensílios de medidas (colheres, xícaras e copo medidor), batedor de claras, peneiras de farinha, e, se tiver, balança, batedeira ou mixer elétrico e liquidificador.',
    '3. Explicar as seguintes técnicas de preparo de alimentos:',
    'a) Cozer;',
    'b) Grelhar;',
    'c) Fritar;',
    'd) Refogar;',
    'e) Assar.',
    '4. Quais as maneiras mais saudáveis de cozinhar alimentos? E as menos saudáveis? Por quê?',
    '5. Preparar corretamente: dois tipos de cereais cozidos, uma bebida quente saudável, ovos feitos de duas maneiras que não a fritura.',
    '6. Preparar o seguinte, de maneira saudável:',
    'a) Batata, duas maneiras;',
    'b) Três vegetais de sua escolha.',
    '7. Preparar um almoço vegetariano balanceado, incluindo alimentos construtores, reguladores e energéticos, contendo:',
    'a) 1 prato principal;',
    'b) 3 acompanhamentos;',
    'c) 1 salada crua.',
    '8. Colocar a mesa corretamente e servir essa refeição para a sua família.',
    '9. Qual a importância de ingerir verduras cruas diariamente?',
    '10. Fazer um caderno (ou pasta) de receitas contendo, no mínimo, 10 receitas que você tenha feito.']);
  PERFORM pg_temp.set_req('HD-008', '3', ARRAY[
    '1. Ter a especialidade de Arte culinária.',
    '2. 1 litro contém quantos ml? 1 xícara contém quantas colheres de sopa? 1 colher de sopa contém quantas colheres de chá?',
    '3. Conhecer os diferentes tipos de forno disponíveis no mercado e as vantagens e desvantagens de cada um.',
    '4. O que é intoxicação alimentar? Como preveni-la?',
    '5. Saber por quanto tempo os seguintes alimentos podem ser guardados na geladeira:',
    'a) Leite;',
    'b) Ovos crus;',
    'c) Ovos cozidos;',
    'd) Maionese;',
    'e) Carne;',
    'f) Sobras de comida;',
    'g) Hortaliças.',
    '6. Conhecer e praticar as boas práticas de higiene ao preparar/manipular alimentos.',
    '7. Preparar três tipos de saladas. Como se faz para manter as verduras das saladas frescas?',
    '8. Planejar cardápios contendo café da manhã, almoço e jantar para uma semana, escolhendo, pelo menos, três pratos nos quais sobras de outras refeições possam ser utilizados.',
    '9. Preparar um desjejum equilibrado.',
    '10. Preparar o almoço ou o jantar balanceado para sua família durante, pelo menos, cinco dias. (Podem ser dias seguidos ou finais de semana).',
    '11. Saber cozinhar arroz integral e soja corretamente.',
    '12. Explicar por que devemos ter cuidado ao utilizar ingredientes pouco saudáveis, como:',
    'a) Vinagre;',
    'b) Shoyu ou molho de soja;',
    'c) Glutamato monossódico (presente em temperos prontos);',
    'd) Enlatados;',
    'e) Embutidos.',
    '13. O que a cafeína faz ao corpo? Fazer uma lista de, pelo menos, cinco alimentos que contêm cafeína.',
    '14. Preparar 15 receitas, sendo que, no máximo, cinco poderão ser de doces ou sobremesas. Adicioná-las ao seu caderno (ou pasta) de receitas. Obs.: As receitas preparadas na especialidade de Arte culinária não contam para esse requisito.']);
  PERFORM pg_temp.set_req('HD-010', '1', ARRAY[
    '1. Pesquisar ao menos um ingrediente originário para cada região do seu país.',
    '2. Conhecer alguns dos diferentes temperos utilizados em cada região do seu país.',
    '3. Conhecer, ao menos, três métodos peculiares de preparação de alimentos (ex. cozimento em folha de bananeira).',
    '4. Citar, ao menos, uma comida típica de cada um dos países que compõem a Divisão Sul-Americana.',
    '5. Descrever os ingredientes e o modo de preparo de cada uma das comidas típicas do requisito anterior.',
    '6. Preparar e servir, para sua unidade, uma comida típica que não seja do seu país.',
    '7. Conhecer, ao menos, uma comida típica de cada região de seu país e preparar duas delas para sua família ou unidade.']);
  PERFORM pg_temp.set_req('HD-011', '3', ARRAY[
    '1. Quais são as vantagens e desvantagens dos alimentos congelados?',
    '2. Definir os termos a seguir:',
    'a) Escaldar/branquear;',
    'b) Congelamento rápido;',
    'c) Queimadura de congelamento.',
    '3. Fazer uma lista de ao menos cinco alimentos que podem ser congelados.',
    '4. Quais os recipientes mais indicados para congelar alimentos? Por que não deve ser utilizado recipiente de vidro ou isopor?',
    '5. Que pontos essenciais devem ser considerados quando se seleciona alimentos para serem congelados?',
    '6. Demonstrar como fazer a correta higienização do freezer/congelador onde os alimentos serão armazenados.',
    '7. Por que é importante etiquetar os recipientes dos alimentos congelados? Que materiais devem ser utilizados para esse fim? Quais informações devem conter na etiqueta?',
    '8. O que é ácido ascórbico e qual sua utilidade no congelamento de frutas?',
    '9. Como se deve descongelar e servir os seguintes alimentos?',
    'a) Frutas;',
    'b) Verduras;',
    'c) Legumes;',
    'd) Massas.',
    '10. Congelar dois tipos de legumes e depois prepará-los e servi-los como demonstração.',
    '11. Congelar um tipo de fruta em calda.',
    '12. Congelar um tipo de fruta sem utilizar nenhuma espécie de adoçante.',
    '13. Congelar dois tipos de pratos prontos (ex. lasanha, estrogonofe, etc.). Que precauções especiais devem ser tomadas durante o preparo desses alimentos?',
    '14. Apresentar o período de validade de cada um dos alimentos dos requisitos 10 a 13.']);
  PERFORM pg_temp.set_req('HD-009', '2', ARRAY[
    '1. Descrever o uso apropriado do seguinte:',
    'a) Fita métrica;',
    'b) Tesouras;',
    'c) Agulhas de vários tamanhos e tipos (para costurar à mão ou à máquina);',
    'd) Giz.',
    '2. Familiarizar-se com uma máquina de costura. Identificar:',
    'a) Puxador de linha (se este estiver visível);',
    'b) Pé calcador;',
    'c) Levantador de pé calcador;',
    'd) Alimentador da bobina (se este estiver visível);',
    'e) Serrilha;',
    'f) Regulador ou tensor de ponto.',
    '3. Demonstrar como colocar a linha na máquina e fazê-la funcionar corretamente.',
    '4. Fazer barra numa toalha de mesa ou lençol, em que os pontos fiquem bem-feitos e por igual.',
    '5. Saber pregar botões, fazer casas de botões, pregar colchetes e ganchos, bainha com ponto invisível e alinhavar.',
    '6. Dizer o significado de:',
    'a) Orla;',
    'b) Viés;',
    'c) Direção do fio;',
    'd) Enviesado;',
    'e) Nesga.',
    '7. Saber como cerzir (remendar) corretamente.',
    '8. Fazer um dos seguintes:',
    'a) Avental;',
    'b) Par de fronhas;',
    'c) Sacola de pano.']);
  PERFORM pg_temp.set_req('HD-003', '2', ARRAY[
    '1. Até que idade uma criança é considerada um bebê?',
    '2. Ser capaz de cuidar de um bebê durante, no mínimo, cinco horas em, pelo menos, três dias de uma semana.',
    '3. Quais alimentos não devem ser dados a um bebê menor que um ano? Relacionar todas as precauções que devem ser tomadas ao se preparar alimentos para um bebê. Preparar um alimento e alimentar o bebê.',
    '4. Preparar o banho, dar banho, trocar o bebê, e vesti-lo. Explicar quais os cuidados são recomendados para vestir um bebê. Que tipos de tecidos devem ser evitados em contato com a pele e por quê?',
    '5. Explique quais são as recomendações dos especialistas para garantir um sono seguro para o bebê. Preparar o berço do bebê, e colocá-lo para dormir.',
    '6. Qual é o peso normal de um bebê ao nascer? Qual é o esperado para 6 e 12 meses? Veja a curva de crescimento do bebê que você está cuidando (disponível na sua caderneta de saúde) e compare com os valores esperados. O que se deve fazer para que um bebê tenha um crescimento adequado? (Caso não tenha acesso à caderneta de saúde do bebê que está cuidando, você pode analisar a sua própria curva de crescimento, ou de algum familiar ou amigo próximo).',
    '7. Responder o seguinte:',
    'a) Quais são os benefícios da amamentação para a mãe e seu bebê?',
    'b) Quanto tempo um bebê deve mamar exclusivamente no seio da mãe? O que é desmamar?',
    'c) Quais são as recomendações da Organização Mundial da Saúde e da UNICEF sobre amamentação?',
    'd) Por que mamadeiras e chupetas devem ser evitadas?',
    '8. O que é fontanela (moleira)? Por volta de que idade ela desaparece?',
    '9. Entrevistar funcionários de uma creche e perguntar a respeito do trabalho ali, e da ajuda oferecida às mães.',
    '10. Conhecer o cartão de saúde da criança do seu país e dizer quais as informações básicas são encontradas nele.',
    '11. Conhecer o calendário de vacinação básica do seu país. Quais as vacinas fazem parte dele? Elas previnem quais doenças? Quando devem ser administradas? Conferir o seu cartão de vacinação e o do bebê que você está cuidado. Caso esteja incompleto, comunique à sua mãe e/ou à mãe do bebê para procurarem um centro de saúde e atualizá-lo.',
    '12. Citar quatro dificuldades ou sinais de alarme que um bebê pode apresentar e indicar a necessidade de uma consulta em um posto de saúde ou pronto socorro.',
    '13. Conhecer os principais números de emergência do seu país, como, por exemplo, polícia, bombeiros e serviço médico.']);
  PERFORM pg_temp.set_req('HD-004', '3', ARRAY[
    '1. Fazer uma lista dos produtos e utensílios de limpeza usados em uma casa.',
    '2. Descrever como manter fogões, fornos micro-ondas e/ou elétricos e geladeiras limpos.',
    '3. Sob que condições os micro-organismos e pragas de insetos se desenvolvem? Saber limpar cada um dos itens a seguir: armário de roupas, armário de cozinha, pias e sanitários.',
    '4. Descrever a maneira adequada de preparar a louça para ser lavada, quer na pia quer na máquina lava-louças. Lavar corretamente a louça da sua casa diariamente por, no mínimo, 1 mês.',
    '5. Saber como limpar tapetes, carpetes, travesseiros, móveis estofados, paredes com acabamento de papel de parede, paredes pintadas, pisos e janelas.',
    '6. Saber como é o sistema de coleta de lixo em sua região. Separar corretamente o lixo em sua casa.',
    '7. Como manter uma casa segura para crianças? Cite, pelo menos, 5 atitudes, envolvendo cuidados com eletricidade, produtos químicos, objetos perfurocortantes e cuidados ao cozinhar.',
    '8. Manter a sua casa limpa e organizada por, no mínimo, 1 mês, incluindo:',
    'a) Lavar o chão;',
    'b) Tirar o pó;',
    'c) Trocar as roupas de cama, capas de almofadas e forros e toalhas de mesa;',
    'd) Arrumar as camas;',
    'e) Guardar tudo em seu devido lugar;',
    'f) Lavar o banheiro;',
    'g) Tirar o lixo.']);
  PERFORM pg_temp.set_req('HD-012', '3', ARRAY[
    '1. O que é desidratação de alimentos? Quais suas vantagens?',
    '2. Relacionar e descrever, pelo menos, três maneiras diferentes de desidratar alimentos.',
    '3. Demonstrar como selecionar os alimentos para a desidratação.',
    '4. Descrever como armazenar corretamente os alimentos desidratados.',
    '5. Como se faz a reconstituição de alimentos desidratados?',
    '6. Desidratar os seguintes alimentos e fornecer amostras para degustação:',
    'a) Fruta;',
    'b) Vegetal;',
    'c) Carne vegetal;',
    'd) Ervas.',
    '7. Reconstituir uma fruta ou legume e prepará-lo para degustação.']);
  PERFORM pg_temp.set_req('HD-006', '2', ARRAY[
    '1. O que é orçamento familiar e qual a importância de fazê-lo?',
    '2. Fazer uma lista das despesas de sua família e classificá-las em necessárias, úteis e supérfluas.',
    '3. Verificar a lista de compras de mantimentos e produtos de higiene e limpeza de sua família. Escrever quais itens você considera extremamente importantes e que não podem ser esquecidos e quais não são tão significativos e que poderiam ser trocados ou mesmo excluídos.',
    '4. Descobrir qual é o melhor dia e local para se adquirir hortaliças, frutas e verduras em seu bairro.',
    '5. O que você e sua família podem fazer para economizar água e energia elétrica?',
    '6. Que impostos sua família precisa pagar? Em qual mês eles devem ser pagos?',
    '7. Que tipos de compras nunca deveriam ser feitas a prazo? Por quê?',
    '8. O que são juros? Como devem ser calculados?',
    '9. Pesquisar qual a taxa de juros e encargos financeiros nas linhas de crédito a seguir:',
    'a) Cartão de crédito;',
    'b) Empréstimo pessoal.',
    '10. Que medidas devem ser tomadas quando a família está endividada?',
    '11. Qual porcentagem da renda de uma família deve ser poupada? Por quê?',
    '12. Pesquisar, ao menos, dois métodos, além da caderneta de poupança, para investir o dinheiro poupado. Quais as vantagens e desvantagens de cada um?',
    '13. Saber fazer o seguinte:',
    'a) Preencher recibos;',
    'b) Pagar boletos e/ou faturas em um terminal de autoatendimento ou por smartphones;',
    'c) Arquivar recibos de pagamentos;',
    'd) Interpretar um extrato de conta corrente/poupança;',
    'e) Pagar contas e fazer compras pela Internet.',
    '14. Manter um orçamento pessoal e relatório de entrada e saída de dinheiro durante, pelo menos, um mês.',
    '15. Montar um orçamento familiar e manter um relatório preciso de entradas e saídas durante um mês (desbravadores mais jovens podem fazer isto em conjunto com os pais); os garotos e garotas que vivem em fazendas, podem fazer relatórios ligados à agricultura, laticínios ou gado.',
    '16. Ler Malaquias 3:8-12 e escrever, no mínimo, 250 palavras sobre o que significa, para você, ser um mordomo fiel.']);
  PERFORM pg_temp.set_req('HD-007', '3', ARRAY[
    '1. Explicar a diferença entre o valor nutricional da farinha integral e da farinha branca.',
    '2. Comparar o fermento biológico e o fermento químico. Como é a ação de cada um deles na massa? Para quais receitas cada um deles é mais indicado?',
    '3. Citar uma passagem do Velho Testamento e uma do Novo Testamento onde o fermento é mencionado. Explicar qual o significado do fermento na celebração da Páscoa.',
    '4. Preparar um pão com grãos inteiros (pode ser trigo, centeio, aveia, linhaça, etc.).',
    '5. Preparar duas das opções a seguir:',
    'a) Biscoitos salgados;',
    'b) Biscoitos doces;',
    'c) Pães asmos (sem fermento);',
    'd) Baguetes;',
    'e) Pão italiano;',
    'f) Pão sovado.',
    '6. Explicar por que a mistura de leite, açúcar e ovos é prejudicial à saúde.',
    '7. Como testar se um bolo está pronto? Como evitar que o bolo “abaixe”?',
    '8. Preparar duas das opções a seguir:',
    'a) Bolo de ingredientes básicos (qualquer sabor);',
    'b) Bolo feito com mistura pronta de bolo (qualquer sabor);',
    'c) Bolo de frutas ou castanha;',
    'd) Bolo sem a utilização de leite ou derivados;',
    'e) Bolo que não contenha glúten.',
    '9. Fazer uma torta em cada uma das categorias a seguir (não usar muito açúcar, creme de leite ou leite condensado):',
    'a) Assada, de qualquer fruta, incluindo limão;',
    'b) Não assada (apenas de massa assada no forno): frutas frescas, gelatina, etc.;',
    'c) Salgada (vegetariana de qualquer sabor).',
    '10. Fazer e assar uma receita de biscoitos. Usar ingredientes saudáveis como frutas, aveia, castanhas, etc.',
    '11. Demonstrar como utilizar corretamente colheres e xícaras de medida. Por que é importante seguir atentamente as receitas na panificação?',
    '12. Preparar um arquivo de receitas para todos os itens exigidos acima e quaisquer outros que desejar. Veja quantas receitas é capaz de encontrar que usem frutas sem grandes quantidades de açúcar.']);
  PERFORM pg_temp.set_req('HD-013', '1', ARRAY[
    '1. Fazer uma breve pesquisa sobre a história da pizza.',
    '2. Fazer uma lista dos ingredientes básicos da massa de pizza.',
    '3. Descrever o processo de fermentação.',
    '4. Qual é a diferença entre a pizza napolitana e a romana?',
    '5. Quais são as três maneiras diferentes de assar uma pizza. Descrever as diferenças em detalhes.',
    '6. Qual é a temperatura ideal para assar uma pizza em: forno à lenha e em forno elétrico?',
    '7. Preparar uma pizza margherita.']);
  PERFORM pg_temp.set_req('HD-005', '3', ARRAY[
    '1. Descrever os seguintes métodos para a conservação de alimentos:',
    'a) Pasteurização;',
    'b) Esterilização;',
    'c) Tindalização;',
    'd) Apertização;',
    'e) Solução salina (salinização);',
    'f) Compota.',
    '2. Listar os utensílios necessários para preparar conservas domésticas.',
    '3. Quais são as técnicas para a higienização de:',
    'a) Alimentos;',
    'b) Utensílios;',
    'c) Superfície de trabalho.',
    '4. Fazer uma lista dos alimentos comuns em sua região que são bons para fazer conservas.',
    '5. Demonstrar como selecionar, descascar e picar os alimentos para preparar a conserva.',
    '6. Demonstrar como esterilizar, encher, fechar e testar para ver se os frascos estão bem fechados.',
    '7. Como fechar hermeticamente ou a vácuo um pote de conserva em casa?',
    '8. O que é pectina? Quando ela deve ser utilizada?',
    '9. Quais são os sinais de que uma conserva não está mais adequada para o consumo?',
    '10. O que é botulismo? Pelo que é causado? Quais são os sinais e sintomas dessa doença?',
    '11. Fazer duas das seguintes conservas e apresentar ao instrutor para degustação:',
    'a) Suco de frutas;',
    'b) Verdura ou legume;',
    'c) Fruta;',
    'd) Doce ou geleia.']);
  PERFORM pg_temp.set_req('HD-002', '3', ARRAY[
    '1. Saber interpretar os símbolos usados em etiquetas de roupas. Desenhar os símbolos correspondentes a:',
    'a) Temperatura máxima de lavagem;',
    'b) Lavar à mão;',
    'c) Não lavar;',
    'd) Temperatura máxima da base do ferro de passar a 200°;',
    'e) Temperatura máxima da base do ferro de passar a 150°;',
    'f) Temperatura máxima da base do ferro de passar a 110°;',
    'g) Não passar;',
    'h) Secagem em varal;',
    'i) Secagem na horizontal;',
    'j) Secagem por gotejamento;',
    'k) Permitido alvejante com cloro;',
    'l) Não alvejar / não branquear;',
    'm) Não limpar a seco.',
    '2. Saber preparar e separar as roupas para lavar. Quais tipos de tecido não podem ser lavados à máquina?',
    '3. Saber como identificar se um tecido desbota. Caso desbote, quais os cuidados necessários ao lavá-lo e secá-lo?',
    '4. Por que não se deve deixar as roupas sujas guardadas, especialmente se estiverem úmidas?',
    '5. Descrever os principais cuidados ao utilizar os seguintes alvejantes ou substâncias para tirar manchas:',
    'a) Cloro (água sanitária);',
    'b) Produtos à base de peróxido de hidrogênio (água oxigenada);',
    'c) Amônia;',
    'd) Thinner;',
    'e) Aguarrás;',
    'f) Vinagre.',
    '6. Por que não se deve usar, numa mesma lavagem, mais de um tipo das substâncias acima?',
    '7. Quais aspectos devem ser considerados ao se escolher uma máquina de lavar roupas para a sua família?',
    '8. Saber como lavar os seguintes tipos de tecidos:',
    'a) Lã;',
    'b) Couro natural ou artificial;',
    'c) Camurça;',
    'd) Renda.',
    '9. Saber como remover manchas de: tinta, frutas, ferrugem, grama, chocolate, gordura, sangue, chiclete. Por que as manchas devem ser totalmente removidas antes da roupa ser lavada?',
    '10. Por que é importante retirar as roupas de uma máquina de lavar/secadora imediatamente após o ciclo de lavagem/secagem terminar?',
    '11. Comparar um ferro de passar comum e um ferro a vapor. Quais as vantagens e desvantagens de cada um deles?',
    '12. Passar, dobrar e guardar corretamente os seguintes tipos de roupas:',
    'a) Roupas de cama;',
    'b) Calça jeans;',
    'c) Calça social;',
    'd) Saia;',
    '12. (continuação)',
    'e) Camisa;',
    'f) Camiseta;',
    'g) Uniforme oficial.',
    '13. Cumprir os seguintes requisitos:',
    'a) Lavar, dobrar e guardar as roupas de sua família por um mês (caso use máquina de lavar) ou por uma semana (caso seja à mão).',
    'b) Lavar à mão (no tanque, na bacia, no rio) corretamente, pelo menos, duas peças de roupa (peças íntimas não contam).',
    'c) Passar, dobrar e guardar corretamente as suas roupas durante, pelo menos, duas semanas.',
    'd) Manter o seu guarda-roupa ou cômoda organizados por, no mínimo, um mês.',
    '14. Apresentar relatório com suas observações sobre facilidades e dificuldades no processo.',
    'Página em branco.']);
END $$;
